newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
getPlace: column=3, hight=0
getPhone: 221
isMember: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: 0
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
getPlace: column=23, hight=0
getPhone: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
getPlace: column=9, hight=0
getExpenses: 0
getPhone: 101
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: True
makeMember: DOESNT_EXISTS
isMember: False
getExpenses: 0
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPhone: INVALID_INPUT
makeMember: SUCCESS
isMember: False
getPlace: column=6, hight=0
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: 0
addPrize: INVALID_INPUT
getExpenses: 0
addCostumer: SUCCESS
getPhone: 147
isMember: True
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 6
getPlace: column=2, hight=17
addCostumer: SUCCESS
putOnTop: SUCCESS
getPlace: column=16, hight=0
getPhone: 242
addCostumer: SUCCESS
makeMember: INVALID_INPUT
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
getPhone: 108
isMember: False
putOnTop: SUCCESS
isMember: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
getPlace: column=13, hight=31
makeMember: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: INVALID_INPUT
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
getPlace: column=14, hight=0
putOnTop: SUCCESS
getPlace: column=13, hight=13
getPlace: INVALID_INPUT
addPrize: SUCCESS
newMonth: SUCCESS
getPhone: 151
makeMember: INVALID_INPUT
getPlace: column=28, hight=0
addCostumer: INVALID_INPUT
getPlace: column=17, hight=0
buyRecord: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: SUCCESS
getPlace: column=17, hight=0
addCostumer: SUCCESS
getExpenses: 0
getPhone: 113
addPrize: SUCCESS
addPrize: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: False
putOnTop: SUCCESS
getPlace: column=19, hight=17
putOnTop: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
getPhone: 172
getPlace: column=26, hight=0
isMember: DOESNT_EXISTS
getPlace: column=28, hight=0
buyRecord: SUCCESS
getPlace: column=6, hight=6
makeMember: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: True
makeMember: SUCCESS
putOnTop: INVALID_INPUT
getPlace: column=28, hight=0
isMember: False
makeMember: SUCCESS
getPlace: column=14, hight=0
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
getPhone: 97
putOnTop: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
newMonth: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=17, hight=0
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
getPhone: 10
putOnTop: SUCCESS
getPlace: column=16, hight=0
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 242
getPlace: column=1, hight=0
addPrize: SUCCESS
getExpenses: -26
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
getPlace: column=19, hight=0
putOnTop: FAILURE
addPrize: INVALID_INPUT
buyRecord: INVALID_INPUT
putOnTop: SUCCESS
getPlace: column=21, hight=0
getPlace: column=0, hight=0
getPlace: column=1, hight=0
getPlace: column=4, hight=0
putOnTop: SUCCESS
getPhone: 97
getPhone: 47
getPlace: column=27, hight=0
getPhone: DOESNT_EXISTS
getPhone: 34
makeMember: ALREADY_EXISTS
isMember: True
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
getPlace: column=23, hight=0
makeMember: SUCCESS
getPlace: column=1, hight=0
isMember: False
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
isMember: True
getPhone: 67
buyRecord: INVALID_INPUT
getPhone: INVALID_INPUT
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: True
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
getPlace: column=21, hight=10
getExpenses: 136
isMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 66
isMember: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
getPhone: 97
addPrize: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -81
isMember: True
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: -81
getPlace: column=18, hight=0
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
getPhone: 66
getPhone: 47
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
isMember: True
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: DOESNT_EXISTS
getPlace: column=23, hight=0
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: True
addCostumer: SUCCESS
isMember: INVALID_INPUT
addCostumer: INVALID_INPUT
isMember: False
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getExpenses: -65
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
makeMember: INVALID_INPUT
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=7, hight=0
getExpenses: INVALID_INPUT
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=29, hight=0
addCostumer: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
getPhone: 151
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 6
getPhone: 67
buyRecord: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 227
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: column=15, hight=24
getPlace: column=28, hight=0
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: -156
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPhone: 221
getExpenses: -22
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 98
getExpenses: 52
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
isMember: True
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
isMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: DOESNT_EXISTS
getPlace: column=24, hight=0
getPlace: column=2, hight=0
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=23, hight=0
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: 0
addCostumer: SUCCESS
getPlace: column=24, hight=0
getPhone: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=15, hight=14
getExpenses: INVALID_INPUT
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
getPlace: column=0, hight=0
getExpenses: 52
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
isMember: True
addCostumer: SUCCESS
getPlace: column=27, hight=0
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
getExpenses: 0
getPlace: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
isMember: True
getPhone: 39
makeMember: SUCCESS
isMember: True
getPlace: column=23, hight=0
putOnTop: DOESNT_EXISTS
isMember: False
putOnTop: SUCCESS
getPhone: 5
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: -113
getPlace: column=17, hight=124
makeMember: SUCCESS
getPhone: 6
addPrize: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: True
addCostumer: SUCCESS
isMember: True
getExpenses: -135
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 104
isMember: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: -205
buyRecord: SUCCESS
getPhone: 221
putOnTop: SUCCESS
getPhone: 6
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: 65
putOnTop: SUCCESS
getPhone: 87
getPhone: 124
isMember: False
putOnTop: DOESNT_EXISTS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=22, hight=0
getPlace: column=1, hight=133
putOnTop: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 65
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 66
makeMember: ALREADY_EXISTS
getPhone: 241
addCostumer: SUCCESS
addPrize: INVALID_INPUT
putOnTop: FAILURE
addCostumer: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
getPhone: 87
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
getPhone: 87
addCostumer: INVALID_INPUT
isMember: True
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: False
getPlace: column=22, hight=0
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=18, hight=14
putOnTop: SUCCESS
isMember: False
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
getPhone: 241
addPrize: SUCCESS
getExpenses: 18
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: False
buyRecord: DOESNT_EXISTS
newMonth: SUCCESS
getExpenses: 0
buyRecord: SUCCESS
getExpenses: 0
isMember: True
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: SUCCESS
getPhone: 5
putOnTop: SUCCESS
getPlace: column=31, hight=0
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
getPlace: column=32, hight=0
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: True
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: False
getPhone: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
getPhone: 98
getPhone: 71
putOnTop: DOESNT_EXISTS
makeMember: INVALID_INPUT
putOnTop: SUCCESS
isMember: False
getExpenses: 0
isMember: False
getPhone: 39
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 121
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: False
getPhone: 47
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
getPhone: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
makeMember: INVALID_INPUT
isMember: True
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=25, hight=0
putOnTop: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
isMember: False
getPhone: 26
addPrize: SUCCESS
getPhone: 238
getExpenses: -50
addPrize: INVALID_INPUT
buyRecord: INVALID_INPUT
getPhone: 6
buyRecord: DOESNT_EXISTS
isMember: True
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: column=19, hight=0
makeMember: ALREADY_EXISTS
getPhone: 56
isMember: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: True
getExpenses: DOESNT_EXISTS
getExpenses: -168
addCostumer: SUCCESS
isMember: True
getPhone: 8
getExpenses: -18
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: SUCCESS
isMember: True
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
isMember: True
getExpenses: -107
addPrize: SUCCESS
isMember: False
putOnTop: SUCCESS
getPlace: column=5, hight=0
getPhone: 147
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: 98
getPlace: column=35, hight=0
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=38, hight=0
buyRecord: INVALID_INPUT
isMember: DOESNT_EXISTS
isMember: False
buyRecord: INVALID_INPUT
getExpenses: -232
makeMember: ALREADY_EXISTS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=11, hight=0
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 221
isMember: False
addCostumer: SUCCESS
isMember: True
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
getExpenses: 0
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
isMember: DOESNT_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -239
getPhone: 101
getPhone: 87
addCostumer: ALREADY_EXISTS
isMember: False
getPhone: 98
addPrize: SUCCESS
getExpenses: -346
isMember: True
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 8
isMember: True
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: 154
isMember: False
getPhone: 98
isMember: False
isMember: True
buyRecord: SUCCESS
putOnTop: SUCCESS
getPlace: column=23, hight=0
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: -330
getPhone: DOESNT_EXISTS
getPhone: 100
getExpenses: -377
getExpenses: -422
getExpenses: -42
makeMember: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=37, hight=106
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
addPrize: INVALID_INPUT
isMember: True
getExpenses: DOESNT_EXISTS
getPhone: 242
makeMember: SUCCESS
getExpenses: -328
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
isMember: False
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
getExpenses: -387
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
makeMember: INVALID_INPUT
getExpenses: -321
putOnTop: FAILURE
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: column=19, hight=0
isMember: True
putOnTop: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getExpenses: -63
getPlace: column=29, hight=5
getExpenses: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: INVALID_INPUT
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=29, hight=0
addCostumer: SUCCESS
putOnTop: SUCCESS
getPlace: column=36, hight=83
makeMember: SUCCESS
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: False
isMember: False
getPhone: 172
getPhone: 69
isMember: False
makeMember: INVALID_INPUT
isMember: True
getExpenses: DOESNT_EXISTS
isMember: True
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
isMember: False
makeMember: ALREADY_EXISTS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=23, hight=0
putOnTop: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
getPhone: 170
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: column=35, hight=23
addCostumer: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=23, hight=0
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
makeMember: DOESNT_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
getExpenses: -438
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: INVALID_INPUT
isMember: True
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
getPhone: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: column=35, hight=72
buyRecord: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
getPlace: column=20, hight=0
addPrize: SUCCESS
makeMember: SUCCESS
getPlace: column=35, hight=88
getExpenses: INVALID_INPUT
getPlace: column=20, hight=11
addCostumer: SUCCESS
getPlace: column=35, hight=121
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 108
putOnTop: SUCCESS
getPhone: 41
makeMember: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: False
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
isMember: True
isMember: False
putOnTop: SUCCESS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
isMember: True
isMember: True
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: INVALID_INPUT
putOnTop: FAILURE
addPrize: INVALID_INPUT
putOnTop: FAILURE
getPhone: 65
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 205
addPrize: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
getPlace: column=22, hight=0
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPhone: 57
putOnTop: FAILURE
putOnTop: FAILURE
buyRecord: INVALID_INPUT
getPhone: 104
getPlace: INVALID_INPUT
getPlace: column=15, hight=268
getPlace: column=15, hight=206
getExpenses: -331
getExpenses: -331
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: FAILURE
isMember: False
buyRecord: SUCCESS
isMember: True
getPhone: 42
addPrize: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: INVALID_INPUT
getExpenses: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
getPlace: column=33, hight=0
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: 87
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: -417
isMember: False
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
isMember: False
makeMember: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
isMember: False
putOnTop: FAILURE
getPlace: column=13, hight=17
getExpenses: -741
addCostumer: ALREADY_EXISTS
isMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=13, hight=129
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=33, hight=0
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: -915
buyRecord: SUCCESS
getPhone: 196
putOnTop: FAILURE
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 113
addCostumer: SUCCESS
makeMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getPhone: 67
getPhone: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
isMember: True
getPhone: 104
buyRecord: SUCCESS
isMember: False
addPrize: SUCCESS
putOnTop: FAILURE
getExpenses: 5
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
