newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getPhone: 239
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=10, hight=0
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: 0
addPrize: INVALID_INPUT
isMember: False
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
getPhone: 203
getPhone: DOESNT_EXISTS
isMember: True
getExpenses: 0
isMember: False
buyRecord: INVALID_INPUT
isMember: DOESNT_EXISTS
isMember: False
getPhone: 227
getPlace: column=23, hight=0
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
newMonth: SUCCESS
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: 0
isMember: True
isMember: False
addPrize: SUCCESS
getExpenses: INVALID_INPUT
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getPhone: 176
isMember: True
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getExpenses: -9
getExpenses: -9
putOnTop: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=1, hight=0
getPhone: 176
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 227
addPrize: INVALID_INPUT
isMember: False
getExpenses: -74
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 36
getPlace: column=10, hight=0
makeMember: INVALID_INPUT
getPhone: INVALID_INPUT
getPhone: 176
getExpenses: -9
makeMember: SUCCESS
isMember: False
getPhone: 203
getExpenses: DOESNT_EXISTS
getPhone: 190
makeMember: SUCCESS
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
isMember: True
putOnTop: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
isMember: True
putOnTop: SUCCESS
getPlace: column=9, hight=0
