newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: 0
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 3
addCostumer: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: False
getPlace: column=8, hight=0
getPlace: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
getPlace: column=26, hight=0
makeMember: SUCCESS
getExpenses: 100
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 3
addPrize: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: 0
getExpenses: 100
getPlace: column=12, hight=6
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
buyRecord: INVALID_INPUT
putOnTop: FAILURE
makeMember: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 86
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 172
getPhone: 6
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: INVALID_INPUT
getPhone: 165
getExpenses: -180
addCostumer: SUCCESS
getPhone: 86
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=13, hight=0
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=13, hight=0
addCostumer: SUCCESS
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
putOnTop: SUCCESS
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
getExpenses: -37
