newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
buyRecord: SUCCESS
addCostumer: SUCCESS
isMember: False
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 179
getPlace: column=2, hight=0
addPrize: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getPhone: 179
putOnTop: SUCCESS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 50
makeMember: SUCCESS
isMember: False
getExpenses: INVALID_INPUT
getPhone: 248
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 192
buyRecord: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
getPlace: column=15, hight=0
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 50
getPlace: column=3, hight=0
addCostumer: SUCCESS
isMember: False
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=15, hight=0
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getPlace: column=0, hight=0
addCostumer: SUCCESS
getPlace: column=6, hight=0
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
addCostumer: SUCCESS
makeMember: SUCCESS
getPlace: column=1, hight=0
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
getPlace: INVALID_INPUT
makeMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
newMonth: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 32
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
getExpenses: 100
addPrize: INVALID_INPUT
getPlace: column=31, hight=0
buyRecord: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: column=21, hight=0
getExpenses: DOESNT_EXISTS
getPlace: column=12, hight=0
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
makeMember: INVALID_INPUT
putOnTop: SUCCESS
isMember: True
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getExpenses: 0
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 177
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: column=15, hight=0
isMember: False
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 84
addPrize: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: False
buyRecord: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
isMember: False
addPrize: INVALID_INPUT
getPhone: 192
getPlace: column=31, hight=0
getPhone: INVALID_INPUT
addPrize: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: SUCCESS
getPlace: column=5, hight=0
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
getPlace: column=5, hight=0
getExpenses: 57
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
isMember: False
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPhone: 103
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
isMember: DOESNT_EXISTS
getExpenses: -74
makeMember: SUCCESS
getPlace: column=17, hight=0
addCostumer: SUCCESS
getPhone: 177
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=0, hight=0
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
addPrize: SUCCESS
getPhone: 32
getExpenses: -115
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: INVALID_INPUT
makeMember: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: column=14, hight=0
isMember: False
getPhone: 177
isMember: True
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getPlace: column=28, hight=0
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: 0
makeMember: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
isMember: False
addCostumer: SUCCESS
isMember: True
getPlace: column=8, hight=0
addPrize: SUCCESS
putOnTop: SUCCESS
isMember: False
getExpenses: INVALID_INPUT
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
getPlace: column=25, hight=0
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
isMember: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 179
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -15
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 179
getPhone: 192
putOnTop: INVALID_INPUT
makeMember: SUCCESS
isMember: False
getExpenses: -115
makeMember: SUCCESS
getExpenses: -115
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -15
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=11, hight=0
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: INVALID_INPUT
isMember: True
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: True
isMember: True
putOnTop: SUCCESS
getPhone: 86
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: column=26, hight=0
getPlace: column=16, hight=20
makeMember: SUCCESS
isMember: False
getPlace: column=26, hight=0
addCostumer: SUCCESS
getPlace: column=27, hight=0
getPlace: column=1, hight=0
makeMember: SUCCESS
getPhone: 85
makeMember: ALREADY_EXISTS
getPlace: column=12, hight=0
getPhone: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPlace: column=27, hight=0
makeMember: INVALID_INPUT
isMember: True
getPhone: 85
getPhone: DOESNT_EXISTS
getPhone: 200
buyRecord: SUCCESS
getPhone: 179
makeMember: ALREADY_EXISTS
getExpenses: -151
addCostumer: SUCCESS
getPlace: column=20, hight=0
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
getPlace: column=26, hight=0
getPhone: 204
getPlace: column=4, hight=0
getPhone: 118
addPrize: SUCCESS
isMember: True
getExpenses: -355
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
addPrize: INVALID_INPUT
getPhone: 242
isMember: True
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: column=28, hight=19
addPrize: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=2, hight=0
addCostumer: SUCCESS
getExpenses: -17
getPlace: column=15, hight=0
getPhone: 246
getPhone: DOESNT_EXISTS
getExpenses: INVALID_INPUT
isMember: INVALID_INPUT
getPlace: column=28, hight=0
getPhone: 84
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
isMember: False
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
isMember: True
getPhone: 9
isMember: False
getExpenses: INVALID_INPUT
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: INVALID_INPUT
isMember: DOESNT_EXISTS
getPlace: column=28, hight=0
putOnTop: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
isMember: True
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: True
makeMember: SUCCESS
makeMember: SUCCESS
getPlace: column=2, hight=0
getPhone: 248
makeMember: ALREADY_EXISTS
getPhone: 177
isMember: True
buyRecord: DOESNT_EXISTS
buyRecord: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
getPhone: 22
putOnTop: SUCCESS
makeMember: SUCCESS
getExpenses: -741
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
getPhone: 32
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: 230
isMember: False
getPlace: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
isMember: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
getPhone: 13
addCostumer: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: 85
getPhone: 217
putOnTop: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 202
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: FAILURE
makeMember: DOESNT_EXISTS
getPhone: 202
getExpenses: DOESNT_EXISTS
getPlace: column=24, hight=36
getPlace: column=13, hight=0
getExpenses: -117
getExpenses: INVALID_INPUT
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
getPhone: 85
getExpenses: INVALID_INPUT
getExpenses: INVALID_INPUT
putOnTop: FAILURE
getExpenses: INVALID_INPUT
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: column=10, hight=0
addPrize: INVALID_INPUT
addPrize: SUCCESS
getExpenses: -55
isMember: True
putOnTop: SUCCESS
getPlace: column=5, hight=0
putOnTop: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -636
putOnTop: SUCCESS
isMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
isMember: True
addCostumer: SUCCESS
getPlace: column=25, hight=0
buyRecord: SUCCESS
isMember: True
getPlace: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPhone: 154
isMember: True
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: False
getPhone: 167
getPhone: 118
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
getPhone: 195
isMember: False
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=13, hight=0
getPlace: column=13, hight=14
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
isMember: True
isMember: True
addPrize: SUCCESS
getPlace: column=4, hight=0
isMember: True
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: column=13, hight=126
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: INVALID_INPUT
isMember: INVALID_INPUT
putOnTop: FAILURE
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: False
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 110
getExpenses: -238
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 168
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
isMember: True
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: -674
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: DOESNT_EXISTS
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=10, hight=153
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPlace: column=10, hight=152
putOnTop: FAILURE
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: False
buyRecord: DOESNT_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 84
isMember: True
isMember: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
buyRecord: INVALID_INPUT
getPlace: column=10, hight=160
isMember: False
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
addPrize: SUCCESS
getPhone: 79
putOnTop: SUCCESS
getPlace: column=10, hight=0
isMember: True
isMember: True
isMember: False
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getExpenses: 43
getPhone: 248
isMember: False
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPlace: column=4, hight=0
isMember: False
makeMember: SUCCESS
getPlace: column=10, hight=112
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: SUCCESS
getPlace: column=24, hight=68
addPrize: SUCCESS
isMember: INVALID_INPUT
addCostumer: INVALID_INPUT
getPhone: 6
getPhone: INVALID_INPUT
getPhone: 248
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
getPlace: column=24, hight=92
getPlace: DOESNT_EXISTS
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: SUCCESS
makeMember: INVALID_INPUT
isMember: True
getExpenses: DOESNT_EXISTS
makeMember: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getExpenses: INVALID_INPUT
isMember: False
getPlace: column=24, hight=142
makeMember: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=24, hight=16
getExpenses: -75
isMember: True
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: INVALID_INPUT
getExpenses: -456
putOnTop: FAILURE
getPlace: INVALID_INPUT
isMember: False
addCostumer: SUCCESS
addPrize: INVALID_INPUT
isMember: True
getPhone: 242
isMember: True
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
isMember: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: -643
getPlace: DOESNT_EXISTS
putOnTop: SUCCESS
makeMember: SUCCESS
getPhone: 196
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=7, hight=116
putOnTop: FAILURE
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: INVALID_INPUT
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
isMember: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: column=7, hight=89
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=7, hight=43
buyRecord: SUCCESS
getExpenses: -425
makeMember: ALREADY_EXISTS
getPhone: 154
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPhone: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
getPhone: 32
addCostumer: SUCCESS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=7, hight=0
isMember: False
buyRecord: INVALID_INPUT
isMember: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
getPhone: 123
getPlace: column=7, hight=170
addPrize: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
isMember: False
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 34
isMember: True
getPlace: column=7, hight=202
getPhone: 60
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 34
makeMember: SUCCESS
getPhone: 48
putOnTop: DOESNT_EXISTS
getPlace: column=7, hight=115
makeMember: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getPhone: 103
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getPhone: 152
addCostumer: SUCCESS
isMember: False
makeMember: SUCCESS
buyRecord: SUCCESS
getPhone: 118
makeMember: SUCCESS
getPlace: column=7, hight=89
makeMember: SUCCESS
addPrize: SUCCESS
getPlace: INVALID_INPUT
getPlace: column=7, hight=202
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getPlace: column=7, hight=262
makeMember: SUCCESS
addPrize: INVALID_INPUT
isMember: True
getPlace: column=4, hight=0
getExpenses: -179
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: True
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
putOnTop: FAILURE
getExpenses: -796
getPlace: column=2, hight=0
buyRecord: DOESNT_EXISTS
getPhone: 204
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
getPlace: column=7, hight=176
putOnTop: FAILURE
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
buyRecord: INVALID_INPUT
makeMember: SUCCESS
getPhone: 85
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
getPhone: DOESNT_EXISTS
getPhone: 118
getExpenses: 6
addPrize: INVALID_INPUT
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
makeMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
buyRecord: INVALID_INPUT
isMember: False
putOnTop: FAILURE
getPlace: column=5, hight=0
addPrize: SUCCESS
getPhone: 221
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -41
getPhone: 230
getPlace: column=7, hight=195
addPrize: SUCCESS
addPrize: SUCCESS
getExpenses: -762
isMember: False
getPlace: column=7, hight=136
isMember: True
makeMember: DOESNT_EXISTS
getPhone: 52
isMember: False
addPrize: SUCCESS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: INVALID_INPUT
isMember: False
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: -265
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: False
getPhone: 231
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: FAILURE
getExpenses: -95
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: 248
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: column=7, hight=21
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
addPrize: SUCCESS
getExpenses: -84
getExpenses: -134
addCostumer: SUCCESS
getPlace: column=5, hight=0
getExpenses: -724
getPlace: DOESNT_EXISTS
isMember: INVALID_INPUT
isMember: True
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: column=7, hight=202
getPhone: 18
addCostumer: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
putOnTop: FAILURE
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
getPhone: 237
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 107
isMember: False
getExpenses: -179
putOnTop: FAILURE
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 210
isMember: False
makeMember: ALREADY_EXISTS
getPlace: column=7, hight=282
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
makeMember: INVALID_INPUT
getPlace: DOESNT_EXISTS
makeMember: INVALID_INPUT
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getPhone: 167
isMember: False
addPrize: SUCCESS
getPhone: 191
buyRecord: SUCCESS
getPhone: 9
buyRecord: SUCCESS
getPlace: column=7, hight=267
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: 13
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPlace: column=7, hight=65
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
getExpenses: -995
getPlace: column=7, hight=99
makeMember: ALREADY_EXISTS
getPlace: column=7, hight=195
makeMember: ALREADY_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=7, hight=229
getPhone: 232
getPhone: 71
makeMember: INVALID_INPUT
