newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
isMember: False
buyRecord: SUCCESS
isMember: False
getPhone: 95
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: 0
getPhone: 15
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: False
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: INVALID_INPUT
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: INVALID_INPUT
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPhone: 32
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: column=27, hight=0
getPhone: 15
getPhone: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=10, hight=0
getPhone: 183
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
isMember: INVALID_INPUT
getPlace: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
getPlace: column=27, hight=0
getPhone: 115
putOnTop: SUCCESS
makeMember: SUCCESS
getPhone: 48
getExpenses: 0
getExpenses: INVALID_INPUT
isMember: True
isMember: False
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: 95
isMember: DOESNT_EXISTS
getPhone: 15
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getExpenses: 0
getPlace: column=1, hight=0
isMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 95
getPlace: column=7, hight=0
isMember: True
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: 184
makeMember: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
addCostumer: INVALID_INPUT
getPlace: column=10, hight=0
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPlace: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 11
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
isMember: True
isMember: False
addPrize: SUCCESS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 15
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
isMember: INVALID_INPUT
addPrize: SUCCESS
isMember: False
getPlace: column=25, hight=8
getPlace: column=27, hight=0
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: True
putOnTop: FAILURE
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 115
addCostumer: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
getPhone: 136
makeMember: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
getPlace: column=8, hight=0
isMember: INVALID_INPUT
getPhone: 95
addPrize: SUCCESS
getPlace: column=23, hight=0
getPlace: column=14, hight=0
addCostumer: SUCCESS
getPlace: column=7, hight=0
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=6, hight=12
addPrize: INVALID_INPUT
isMember: True
getPhone: 43
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 15
putOnTop: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 67
isMember: DOESNT_EXISTS
newMonth: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getPhone: 32
getExpenses: DOESNT_EXISTS
getExpenses: 0
isMember: False
isMember: False
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getPhone: 185
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 181
getPhone: 95
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=1, hight=0
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
getPlace: DOESNT_EXISTS
buyRecord: INVALID_INPUT
makeMember: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: True
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
getPlace: column=13, hight=0
getPlace: INVALID_INPUT
putOnTop: DOESNT_EXISTS
newMonth: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getPhone: 67
isMember: False
makeMember: SUCCESS
isMember: False
getPhone: 32
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 95
putOnTop: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: True
makeMember: SUCCESS
getExpenses: 0
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
buyRecord: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 132
getExpenses: DOESNT_EXISTS
isMember: False
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=17, hight=0
putOnTop: SUCCESS
getPhone: 226
addCostumer: SUCCESS
isMember: False
getPhone: 9
buyRecord: SUCCESS
getPhone: 11
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: False
getPhone: 56
isMember: True
getPhone: 92
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
isMember: False
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getPlace: column=6, hight=0
isMember: True
getExpenses: DOESNT_EXISTS
addCostumer: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 23
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: 23
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
isMember: False
getExpenses: 0
getPlace: column=17, hight=0
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPlace: column=4, hight=0
getPlace: column=17, hight=0
isMember: False
putOnTop: SUCCESS
putOnTop: SUCCESS
getPlace: column=22, hight=0
isMember: True
getExpenses: 0
getPlace: column=17, hight=17
isMember: False
putOnTop: FAILURE
addPrize: INVALID_INPUT
getExpenses: -120
isMember: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: True
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
isMember: True
addPrize: INVALID_INPUT
getExpenses: 1
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: 32
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPhone: 54
isMember: False
addCostumer: SUCCESS
getPhone: 4
getPhone: 11
addCostumer: SUCCESS
getPlace: column=13, hight=0
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: -333
addCostumer: SUCCESS
putOnTop: SUCCESS
makeMember: SUCCESS
getPlace: column=0, hight=0
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: -72
addPrize: SUCCESS
getPlace: column=21, hight=0
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
getPhone: 226
isMember: False
addPrize: SUCCESS
getPhone: 204
buyRecord: SUCCESS
isMember: False
getExpenses: INVALID_INPUT
putOnTop: SUCCESS
getPhone: 32
buyRecord: SUCCESS
isMember: False
getExpenses: -283
addPrize: INVALID_INPUT
getPlace: column=3, hight=0
getPhone: 124
getExpenses: -451
putOnTop: FAILURE
getPhone: INVALID_INPUT
putOnTop: SUCCESS
makeMember: SUCCESS
getPhone: 115
buyRecord: SUCCESS
getPhone: 230
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: True
getPlace: column=9, hight=0
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: INVALID_INPUT
getPlace: column=9, hight=40
getPlace: column=9, hight=0
buyRecord: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getPhone: 56
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
isMember: True
getPlace: column=15, hight=80
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
getPlace: column=21, hight=8
isMember: True
getPlace: column=15, hight=154
getPhone: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 67
isMember: False
buyRecord: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
isMember: False
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=15, hight=129
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=16, hight=0
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: True
getPhone: 92
isMember: False
buyRecord: DOESNT_EXISTS
buyRecord: INVALID_INPUT
putOnTop: FAILURE
addCostumer: SUCCESS
putOnTop: SUCCESS
getExpenses: -450
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: False
getExpenses: -615
addPrize: INVALID_INPUT
getPlace: column=21, hight=63
isMember: True
getPlace: column=21, hight=124
addPrize: SUCCESS
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: ALREADY_EXISTS
putOnTop: SUCCESS
makeMember: INVALID_INPUT
putOnTop: SUCCESS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getExpenses: -238
isMember: False
getPhone: 54
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: column=21, hight=106
addCostumer: SUCCESS
getPhone: 124
addCostumer: SUCCESS
getPhone: 181
getPhone: 43
isMember: False
isMember: True
putOnTop: DOESNT_EXISTS
addCostumer: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=21, hight=106
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=21, hight=143
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
getPlace: column=7, hight=0
getPhone: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getExpenses: -338
isMember: True
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getExpenses: -687
isMember: True
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: -450
putOnTop: FAILURE
isMember: True
addPrize: SUCCESS
getPhone: 18
isMember: False
makeMember: ALREADY_EXISTS
getPhone: 18
addCostumer: SUCCESS
getPhone: INVALID_INPUT
addCostumer: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: False
buyRecord: SUCCESS
putOnTop: FAILURE
isMember: True
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: INVALID_INPUT
getPhone: 54
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -463
putOnTop: FAILURE
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
isMember: False
buyRecord: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
getPhone: 11
addCostumer: SUCCESS
isMember: False
addPrize: INVALID_INPUT
getExpenses: -692
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=21, hight=0
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPhone: 95
addCostumer: SUCCESS
putOnTop: FAILURE
getPhone: 59
addPrize: INVALID_INPUT
getPlace: column=21, hight=180
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
isMember: False
getPlace: DOESNT_EXISTS
getPhone: INVALID_INPUT
isMember: False
isMember: True
addPrize: SUCCESS
isMember: False
addCostumer: SUCCESS
getPhone: 6
buyRecord: SUCCESS
getPlace: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPhone: 136
getPhone: 67
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=21, hight=155
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: INVALID_INPUT
getPhone: 192
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
isMember: True
putOnTop: FAILURE
getExpenses: -261
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getExpenses: -308
getPhone: 53
getExpenses: -482
putOnTop: FAILURE
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: column=21, hight=80
getPlace: column=21, hight=180
addPrize: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 95
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
buyRecord: INVALID_INPUT
getPhone: 244
putOnTop: FAILURE
isMember: True
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
isMember: True
getPhone: 192
buyRecord: SUCCESS
getPlace: column=21, hight=80
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 239
getExpenses: -51
addCostumer: SUCCESS
getExpenses: -357
putOnTop: FAILURE
makeMember: INVALID_INPUT
makeMember: SUCCESS
isMember: True
makeMember: SUCCESS
putOnTop: FAILURE
getPlace: column=21, hight=124
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: SUCCESS
getPhone: 183
addPrize: INVALID_INPUT
makeMember: SUCCESS
putOnTop: FAILURE
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
putOnTop: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -197
getExpenses: DOESNT_EXISTS
getPlace: column=21, hight=80
getPlace: column=21, hight=218
addCostumer: ALREADY_EXISTS
getPhone: 147
addPrize: INVALID_INPUT
getPlace: column=21, hight=26
putOnTop: SUCCESS
isMember: DOESNT_EXISTS
getPlace: column=3, hight=0
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: True
getPlace: column=21, hight=109
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 224
isMember: INVALID_INPUT
getExpenses: -779
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: 15
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 147
makeMember: SUCCESS
getPlace: column=21, hight=164
getPlace: column=21, hight=207
getPhone: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
isMember: INVALID_INPUT
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 92
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 108
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: True
getPlace: column=21, hight=26
getPlace: column=21, hight=89
getExpenses: -861
makeMember: SUCCESS
addPrize: SUCCESS
buyRecord: INVALID_INPUT
makeMember: SUCCESS
isMember: True
getPlace: column=21, hight=173
addPrize: INVALID_INPUT
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
getPhone: 197
getPhone: 250
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: column=21, hight=143
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPhone: 6
putOnTop: FAILURE
addCostumer: SUCCESS
getPlace: column=21, hight=180
isMember: True
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
makeMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
isMember: DOESNT_EXISTS
getPhone: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 224
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: False
getPlace: column=21, hight=40
putOnTop: FAILURE
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getPhone: 186
getPhone: 54
getPhone: 244
getPhone: 42
getPhone: 67
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPhone: 59
putOnTop: DOESNT_EXISTS
isMember: False
getPlace: column=3, hight=209
getPhone: 26
makeMember: SUCCESS
addPrize: SUCCESS
makeMember: INVALID_INPUT
getExpenses: 167
isMember: True
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getPhone: INVALID_INPUT
getExpenses: -1137
getExpenses: -40
putOnTop: FAILURE
addPrize: SUCCESS
isMember: False
getPhone: 48
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
isMember: False
getExpenses: -69
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 77
addPrize: SUCCESS
isMember: True
buyRecord: SUCCESS
getExpenses: -893
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: -1102
addCostumer: SUCCESS
isMember: True
putOnTop: FAILURE
buyRecord: SUCCESS
isMember: True
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPhone: 186
getPhone: 247
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: 106
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
isMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPlace: column=3, hight=157
addPrize: SUCCESS
makeMember: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: FAILURE
getPhone: 15
addPrize: INVALID_INPUT
getPhone: 230
isMember: False
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPhone: INVALID_INPUT
addPrize: SUCCESS
getPhone: INVALID_INPUT
buyRecord: SUCCESS
isMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
buyRecord: INVALID_INPUT
isMember: False
getPlace: column=3, hight=81
makeMember: INVALID_INPUT
getExpenses: -817
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
getPlace: column=3, hight=157
getExpenses: -91
addPrize: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 77
putOnTop: FAILURE
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 56
getPlace: column=3, hight=182
isMember: False
getExpenses: DOESNT_EXISTS
getPlace: column=3, hight=91
getExpenses: INVALID_INPUT
getPhone: 23
makeMember: SUCCESS
isMember: False
getPhone: 132
putOnTop: FAILURE
addCostumer: SUCCESS
getPhone: 23
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
isMember: True
getExpenses: -1418
getExpenses: -545
addCostumer: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
isMember: INVALID_INPUT
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getExpenses: -684
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: column=3, hight=251
isMember: False
getPlace: column=3, hight=190
getPlace: column=3, hight=251
newMonth: SUCCESS
isMember: False
getPlace: column=6, hight=0
