newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
getPlace: column=0, hight=0
isMember: False
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 153
buyRecord: SUCCESS
addCostumer: SUCCESS
isMember: False
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 153
getPlace: column=2, hight=0
getPhone: 243
putOnTop: DOESNT_EXISTS
isMember: False
isMember: INVALID_INPUT
putOnTop: SUCCESS
makeMember: INVALID_INPUT
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: column=7, hight=0
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: True
putOnTop: DOESNT_EXISTS
getPhone: 167
getPlace: column=21, hight=0
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: INVALID_INPUT
getPhone: 167
addPrize: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
isMember: INVALID_INPUT
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
getExpenses: -80
makeMember: DOESNT_EXISTS
isMember: False
getPlace: column=21, hight=0
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
isMember: False
getPlace: column=13, hight=0
addPrize: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
addPrize: SUCCESS
getPlace: column=11, hight=0
buyRecord: INVALID_INPUT
putOnTop: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: -200
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
getPlace: column=26, hight=0
addPrize: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
getPlace: column=1, hight=6
isMember: DOESNT_EXISTS
isMember: True
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
getPlace: column=17, hight=0
isMember: True
addCostumer: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
getExpenses: 148
buyRecord: SUCCESS
getPhone: 84
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: False
getPhone: 189
buyRecord: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
isMember: False
putOnTop: INVALID_INPUT
makeMember: INVALID_INPUT
makeMember: SUCCESS
getPhone: 4
isMember: True
isMember: False
isMember: True
getExpenses: INVALID_INPUT
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 206
getPhone: 149
getPhone: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPhone: 238
putOnTop: SUCCESS
buyRecord: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: False
putOnTop: SUCCESS
buyRecord: SUCCESS
getPlace: column=23, hight=0
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
putOnTop: SUCCESS
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: 0
putOnTop: SUCCESS
newMonth: SUCCESS
putOnTop: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
getPhone: 149
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 229
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: SUCCESS
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=10, hight=0
buyRecord: SUCCESS
getPlace: column=4, hight=1
addPrize: SUCCESS
getPhone: 90
buyRecord: SUCCESS
isMember: INVALID_INPUT
getPhone: 62
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: 3
addCostumer: SUCCESS
makeMember: INVALID_INPUT
isMember: False
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=4, hight=1
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 135
isMember: False
makeMember: SUCCESS
addPrize: INVALID_INPUT
buyRecord: INVALID_INPUT
isMember: True
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 135
putOnTop: DOESNT_EXISTS
isMember: False
getPhone: 158
getPlace: column=11, hight=0
isMember: True
getPhone: 238
isMember: INVALID_INPUT
getPhone: 167
putOnTop: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 158
makeMember: SUCCESS
getPlace: column=7, hight=13
addCostumer: ALREADY_EXISTS
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPhone: 206
buyRecord: SUCCESS
addCostumer: INVALID_INPUT
putOnTop: SUCCESS
isMember: False
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPhone: 153
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=19
buyRecord: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
isMember: False
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: INVALID_INPUT
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=1, hight=20
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
getExpenses: -94
isMember: False
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 19
getPlace: column=1, hight=0
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPhone: 90
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=1, hight=38
getExpenses: -94
getPlace: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
getExpenses: INVALID_INPUT
isMember: False
isMember: False
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 206
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -98
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPlace: column=10, hight=72
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -215
makeMember: DOESNT_EXISTS
getPhone: 218
makeMember: ALREADY_EXISTS
isMember: True
makeMember: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
isMember: True
addPrize: SUCCESS
getPhone: 90
getExpenses: -152
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: SUCCESS
getPhone: 218
getPhone: 208
getPhone: 208
getPlace: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -70
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPhone: 137
getPhone: 218
addCostumer: SUCCESS
putOnTop: FAILURE
putOnTop: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
getPhone: DOESNT_EXISTS
getPhone: 171
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -437
makeMember: SUCCESS
getPlace: column=2, hight=69
getPhone: 172
getExpenses: INVALID_INPUT
addCostumer: INVALID_INPUT
addPrize: SUCCESS
makeMember: INVALID_INPUT
putOnTop: FAILURE
isMember: False
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: 104
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: 93
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: False
isMember: False
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 167
getExpenses: DOESNT_EXISTS
getPhone: 84
isMember: True
getExpenses: INVALID_INPUT
getPlace: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: column=2, hight=79
isMember: False
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: INVALID_INPUT
isMember: False
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: INVALID_INPUT
getExpenses: -328
getPlace: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 154
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
putOnTop: FAILURE
getExpenses: -293
getPhone: 171
getExpenses: -4
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: True
getExpenses: 56
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: INVALID_INPUT
getExpenses: INVALID_INPUT
getExpenses: INVALID_INPUT
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: 4
getPlace: column=2, hight=62
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=2, hight=44
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getPlace: column=2, hight=79
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
putOnTop: INVALID_INPUT
makeMember: SUCCESS
getPlace: column=2, hight=69
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 104
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: INVALID_INPUT
getExpenses: -644
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: True
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: FAILURE
getPhone: 153
buyRecord: SUCCESS
makeMember: INVALID_INPUT
makeMember: SUCCESS
getPlace: column=2, hight=79
putOnTop: FAILURE
addCostumer: SUCCESS
getPlace: column=2, hight=50
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=2, hight=63
isMember: True
makeMember: INVALID_INPUT
getExpenses: -14
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPhone: 19
getPhone: 135
getPlace: column=2, hight=96
buyRecord: SUCCESS
getPlace: column=2, hight=105
isMember: False
getPhone: 102
getExpenses: DOESNT_EXISTS
getPlace: column=2, hight=105
makeMember: SUCCESS
getPlace: INVALID_INPUT
isMember: False
getExpenses: -14
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 189
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 218
getPhone: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: -563
putOnTop: FAILURE
putOnTop: FAILURE
addPrize: SUCCESS
getExpenses: 0
isMember: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 154
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
isMember: False
getExpenses: -781
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
addPrize: SUCCESS
getPhone: 86
getPlace: column=2, hight=7
getPhone: 86
isMember: True
getPlace: column=2, hight=63
makeMember: SUCCESS
isMember: False
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: INVALID_INPUT
addPrize: SUCCESS
isMember: True
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
getPhone: 198
getExpenses: DOESNT_EXISTS
getExpenses: -309
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
isMember: True
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: False
getExpenses: -77
getPlace: column=2, hight=69
putOnTop: FAILURE
putOnTop: FAILURE
getPlace: column=2, hight=62
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPlace: column=2, hight=82
buyRecord: SUCCESS
getPlace: column=2, hight=96
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
makeMember: INVALID_INPUT
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=2, hight=63
getPlace: column=2, hight=62
getExpenses: -116
getPhone: 149
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: 216
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=2, hight=96
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: False
isMember: False
getPhone: 154
addPrize: SUCCESS
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=2, hight=50
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=2, hight=0
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 64
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
getExpenses: -4
isMember: False
isMember: False
getPlace: column=2, hight=63
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
isMember: False
getPhone: 150
putOnTop: DOESNT_EXISTS
getPhone: 238
addCostumer: ALREADY_EXISTS
getPlace: column=2, hight=24
getPhone: 139
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
getPlace: column=2, hight=24
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 81
isMember: False
putOnTop: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getPlace: column=2, hight=96
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: -157
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: column=2, hight=7
getPhone: 102
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
isMember: INVALID_INPUT
getExpenses: -29
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
makeMember: INVALID_INPUT
getPlace: column=2, hight=24
isMember: False
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
isMember: False
putOnTop: FAILURE
addPrize: SUCCESS
getPhone: 221
makeMember: DOESNT_EXISTS
getPhone: 85
isMember: False
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
getPhone: 146
getPhone: INVALID_INPUT
getExpenses: -1094
putOnTop: FAILURE
getPhone: 50
putOnTop: FAILURE
getExpenses: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
isMember: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getPhone: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: -620
makeMember: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 106
getPhone: 218
makeMember: DOESNT_EXISTS
getPhone: 167
getPlace: column=2, hight=82
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
isMember: False
getPlace: INVALID_INPUT
getExpenses: -552
getPlace: INVALID_INPUT
getPlace: column=2, hight=96
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=2, hight=96
getPhone: 149
addCostumer: SUCCESS
getPhone: 149
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: -1233
addCostumer: ALREADY_EXISTS
buyRecord: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 106
isMember: False
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=2, hight=79
getPhone: 214
getPlace: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
addPrize: SUCCESS
getPhone: 50
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPlace: column=2, hight=105
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=2, hight=0
putOnTop: FAILURE
isMember: True
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: column=2, hight=62
getPhone: 216
getPlace: column=2, hight=0
putOnTop: FAILURE
getPlace: column=2, hight=7
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
isMember: False
addCostumer: ALREADY_EXISTS
getPlace: column=2, hight=24
makeMember: ALREADY_EXISTS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
putOnTop: DOESNT_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: FAILURE
getPlace: column=2, hight=63
getExpenses: -1111
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=2, hight=63
putOnTop: INVALID_INPUT
getPhone: 47
getPlace: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPhone: 135
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getPhone: 158
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 106
getExpenses: DOESNT_EXISTS
isMember: False
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addCostumer: INVALID_INPUT
getExpenses: -772
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
getPlace: column=2, hight=50
addCostumer: ALREADY_EXISTS
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
getPhone: 218
isMember: False
addCostumer: SUCCESS
getExpenses: -706
addPrize: SUCCESS
isMember: True
makeMember: SUCCESS
isMember: False
getPhone: 238
getExpenses: -1474
getPhone: 207
getPlace: DOESNT_EXISTS
getPlace: column=2, hight=62
buyRecord: SUCCESS
isMember: True
makeMember: SUCCESS
putOnTop: FAILURE
getExpenses: -1310
getPlace: column=2, hight=79
putOnTop: FAILURE
isMember: True
getPlace: column=2, hight=69
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
isMember: True
addPrize: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: -324
getPhone: 90
isMember: False
buyRecord: SUCCESS
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: column=2, hight=63
isMember: False
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
getPlace: column=2, hight=63
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
getPhone: 108
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
isMember: DOESNT_EXISTS
