newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
makeMember: SUCCESS
getExpenses: 0
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 36
getPlace: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 132
addCostumer: SUCCESS
makeMember: INVALID_INPUT
buyRecord: INVALID_INPUT
isMember: False
isMember: INVALID_INPUT
putOnTop: SUCCESS
getPhone: 121
isMember: INVALID_INPUT
makeMember: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: False
getPlace: INVALID_INPUT
isMember: False
putOnTop: SUCCESS
getExpenses: -15
getPhone: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=7, hight=13
getPhone: 110
getPhone: 121
getPhone: 105
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 73
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
addCostumer: SUCCESS
isMember: False
makeMember: DOESNT_EXISTS
getPhone: 104
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
getPhone: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
makeMember: SUCCESS
getPhone: 104
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 68
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=7, hight=0
getPhone: 78
getExpenses: -182
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: INVALID_INPUT
getPlace: column=7, hight=22
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getPlace: column=7, hight=28
getPhone: 110
getExpenses: DOESNT_EXISTS
isMember: True
makeMember: INVALID_INPUT
isMember: False
makeMember: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 132
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: INVALID_INPUT
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPhone: 114
getPhone: 175
addPrize: SUCCESS
getPlace: column=7, hight=13
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
addPrize: INVALID_INPUT
getPlace: column=6, hight=17
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: INVALID_INPUT
addPrize: SUCCESS
getExpenses: -207
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getPlace: INVALID_INPUT
isMember: False
putOnTop: FAILURE
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 73
addCostumer: SUCCESS
getPhone: 226
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: INVALID_INPUT
makeMember: SUCCESS
getPhone: 36
getPhone: 226
putOnTop: DOESNT_EXISTS
getPhone: 175
isMember: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getPlace: column=6, hight=0
getPhone: INVALID_INPUT
isMember: False
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: column=7, hight=28
getExpenses: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
putOnTop: SUCCESS
getPlace: column=4, hight=0
makeMember: ALREADY_EXISTS
isMember: False
putOnTop: FAILURE
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: 175
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPlace: column=6, hight=47
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -285
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 11
getPhone: 53
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 15
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=6, hight=38
putOnTop: DOESNT_EXISTS
getPhone: 53
getExpenses: -305
makeMember: SUCCESS
getPlace: column=6, hight=17
buyRecord: SUCCESS
getPlace: column=6, hight=17
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: INVALID_INPUT
putOnTop: FAILURE
getPlace: column=6, hight=47
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=6, hight=47
buyRecord: DOESNT_EXISTS
putOnTop: SUCCESS
getPhone: 38
getExpenses: -467
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 3
buyRecord: INVALID_INPUT
makeMember: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPlace: column=6, hight=47
isMember: True
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPlace: column=6, hight=40
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
getPhone: 177
isMember: True
addCostumer: SUCCESS
getPhone: 105
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
isMember: True
buyRecord: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: True
putOnTop: FAILURE
isMember: False
isMember: False
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: SUCCESS
getPhone: 68
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: False
putOnTop: INVALID_INPUT
getPlace: column=6, hight=0
putOnTop: FAILURE
isMember: False
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPhone: 55
isMember: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: INVALID_INPUT
getPlace: column=6, hight=40
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=6, hight=82
getPhone: 110
getPhone: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 82
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=6, hight=38
buyRecord: INVALID_INPUT
addPrize: SUCCESS
isMember: False
buyRecord: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
getPhone: 248
addPrize: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 60
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: -613
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 53
buyRecord: INVALID_INPUT
putOnTop: FAILURE
getPhone: 89
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 158
getPhone: INVALID_INPUT
getPhone: 60
isMember: False
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 60
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
isMember: False
isMember: True
putOnTop: FAILURE
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: INVALID_INPUT
getPlace: column=6, hight=0
isMember: False
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPlace: column=6, hight=65
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getPhone: 151
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
getPhone: 132
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 36
addCostumer: SUCCESS
getPlace: column=6, hight=38
addPrize: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: column=6, hight=0
isMember: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPhone: 180
putOnTop: DOESNT_EXISTS
getPhone: 80
getPlace: column=6, hight=65
isMember: INVALID_INPUT
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
buyRecord: INVALID_INPUT
isMember: False
putOnTop: FAILURE
makeMember: SUCCESS
getPhone: 73
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 104
getPlace: INVALID_INPUT
addPrize: SUCCESS
isMember: True
putOnTop: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: False
addPrize: SUCCESS
isMember: False
getExpenses: -286
addCostumer: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: column=6, hight=25
getPlace: column=6, hight=82
buyRecord: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: INVALID_INPUT
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
putOnTop: FAILURE
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
addCostumer: INVALID_INPUT
getPhone: INVALID_INPUT
addCostumer: ALREADY_EXISTS
isMember: False
getExpenses: -640
makeMember: INVALID_INPUT
isMember: False
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
getExpenses: -71
getExpenses: DOESNT_EXISTS
isMember: True
getPhone: 229
getExpenses: DOESNT_EXISTS
isMember: INVALID_INPUT
getPhone: 221
getPlace: column=6, hight=17
getPhone: 121
addCostumer: ALREADY_EXISTS
getExpenses: INVALID_INPUT
getPhone: 73
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getPhone: 128
getPlace: column=6, hight=25
makeMember: DOESNT_EXISTS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 68
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
isMember: False
getPhone: DOESNT_EXISTS
getPlace: column=6, hight=25
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
isMember: False
getPlace: column=6, hight=82
getPlace: DOESNT_EXISTS
getPlace: INVALID_INPUT
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
isMember: True
addPrize: INVALID_INPUT
getPlace: column=6, hight=53
isMember: False
getPhone: 31
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: -827
putOnTop: FAILURE
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
getPlace: INVALID_INPUT
addPrize: SUCCESS
isMember: True
addCostumer: SUCCESS
putOnTop: FAILURE
getPlace: column=6, hight=38
addCostumer: ALREADY_EXISTS
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: -606
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: INVALID_INPUT
isMember: DOESNT_EXISTS
getPlace: column=6, hight=40
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
makeMember: SUCCESS
getPlace: column=6, hight=38
makeMember: SUCCESS
getPhone: 78
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 55
getPlace: column=6, hight=17
putOnTop: FAILURE
getPhone: 102
addCostumer: SUCCESS
getPhone: 102
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: INVALID_INPUT
getExpenses: -195
putOnTop: INVALID_INPUT
getPlace: column=6, hight=53
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: column=6, hight=17
getPlace: DOESNT_EXISTS
getPlace: INVALID_INPUT
isMember: True
makeMember: SUCCESS
isMember: INVALID_INPUT
getPlace: column=6, hight=38
getPlace: column=6, hight=47
getExpenses: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
getPhone: 226
isMember: True
isMember: True
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: -1068
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
getPhone: 145
getPlace: column=6, hight=65
getPhone: 68
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
isMember: True
getExpenses: 0
addPrize: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: 224
makeMember: SUCCESS
buyRecord: DOESNT_EXISTS
getPlace: INVALID_INPUT
getPhone: 63
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
getPhone: 90
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: False
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
getPhone: 128
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=6, hight=53
isMember: True
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: True
isMember: True
makeMember: SUCCESS
buyRecord: SUCCESS
getPhone: 11
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: -397
addPrize: SUCCESS
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: column=6, hight=47
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPhone: 76
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 19
isMember: True
isMember: False
getPlace: column=6, hight=17
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: FAILURE
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
buyRecord: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPlace: column=6, hight=38
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=6, hight=25
getPlace: column=6, hight=40
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 1
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
getPlace: column=6, hight=53
getExpenses: -191
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: -230
isMember: True
addPrize: INVALID_INPUT
getPhone: 38
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: False
addPrize: SUCCESS
getExpenses: -914
isMember: True
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
addCostumer: INVALID_INPUT
putOnTop: DOESNT_EXISTS
buyRecord: INVALID_INPUT
makeMember: DOESNT_EXISTS
getPhone: 102
putOnTop: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPhone: 181
makeMember: SUCCESS
getPlace: column=6, hight=82
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
isMember: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: column=6, hight=25
isMember: True
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: -592
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: False
addCostumer: ALREADY_EXISTS
getPhone: 198
addPrize: SUCCESS
getExpenses: -546
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPhone: 152
putOnTop: FAILURE
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 90
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
getPhone: 110
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: column=6, hight=25
isMember: True
getExpenses: DOESNT_EXISTS
isMember: False
isMember: False
getPlace: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: -780
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: 89
getPhone: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: True
getPhone: 76
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: -785
isMember: False
isMember: False
isMember: False
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
isMember: False
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: FAILURE
isMember: True
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
isMember: True
isMember: False
addPrize: SUCCESS
makeMember: INVALID_INPUT
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
buyRecord: DOESNT_EXISTS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: False
isMember: True
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPhone: 98
addPrize: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
isMember: True
putOnTop: FAILURE
addPrize: SUCCESS
getExpenses: INVALID_INPUT
getPhone: 76
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 95
getPhone: 82
getPlace: INVALID_INPUT
getPhone: 138
getPhone: 82
getExpenses: -474
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: INVALID_INPUT
getExpenses: -1263
getPhone: 232
addCostumer: SUCCESS
getPhone: 226
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 173
putOnTop: FAILURE
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
isMember: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 177
makeMember: INVALID_INPUT
getExpenses: -1845
addPrize: SUCCESS
makeMember: SUCCESS
getPlace: column=6, hight=53
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=6, hight=38
getExpenses: -898
makeMember: INVALID_INPUT
isMember: True
addPrize: INVALID_INPUT
