newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
getPhone: DOESNT_EXISTS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 57
isMember: False
makeMember: INVALID_INPUT
makeMember: SUCCESS
getPhone: INVALID_INPUT
isMember: True
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 176
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: False
buyRecord: SUCCESS
isMember: False
addCostumer: SUCCESS
getPhone: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPlace: column=6, hight=0
getExpenses: DOESNT_EXISTS
getPhone: 16
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 16
addCostumer: ALREADY_EXISTS
isMember: False
getPlace: column=9, hight=0
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 20
addCostumer: SUCCESS
getPhone: INVALID_INPUT
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getPhone: 35
addPrize: INVALID_INPUT
makeMember: INVALID_INPUT
makeMember: SUCCESS
getPhone: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: 0
getPlace: column=15, hight=0
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 164
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=15, hight=0
getPhone: 35
addCostumer: SUCCESS
isMember: True
buyRecord: SUCCESS
isMember: False
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 95
putOnTop: INVALID_INPUT
putOnTop: SUCCESS
addPrize: SUCCESS
getExpenses: -102
addPrize: INVALID_INPUT
getPhone: 176
makeMember: DOESNT_EXISTS
getPlace: column=4, hight=9
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: INVALID_INPUT
getPlace: column=3, hight=0
getPhone: 20
putOnTop: SUCCESS
putOnTop: SUCCESS
getPhone: 95
getPhone: 57
addPrize: SUCCESS
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
getPlace: column=13, hight=7
isMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPhone: 138
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=0, hight=12
makeMember: ALREADY_EXISTS
isMember: False
addPrize: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
putOnTop: SUCCESS
getPlace: column=13, hight=24
getPlace: column=8, hight=0
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: 88
makeMember: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=15, hight=0
getPlace: column=0, hight=11
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: column=0, hight=84
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
getPlace: column=6, hight=0
addPrize: SUCCESS
getPlace: column=0, hight=40
addCostumer: SUCCESS
getPlace: column=0, hight=84
addCostumer: SUCCESS
getExpenses: 0
isMember: False
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
isMember: False
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: False
addCostumer: SUCCESS
getPhone: INVALID_INPUT
isMember: DOESNT_EXISTS
getPlace: column=6, hight=0
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
isMember: False
getPhone: 138
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 67
getPhone: 36
putOnTop: SUCCESS
addCostumer: SUCCESS
getPhone: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getPhone: 5
addPrize: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
isMember: False
makeMember: DOESNT_EXISTS
isMember: False
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
makeMember: INVALID_INPUT
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
isMember: False
buyRecord: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
getPhone: 57
isMember: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
addCostumer: INVALID_INPUT
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 66
getPlace: column=12, hight=99
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 35
getPlace: column=12, hight=17
makeMember: INVALID_INPUT
getPhone: 47
isMember: DOESNT_EXISTS
isMember: False
isMember: True
getExpenses: -207
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
getPlace: column=12, hight=0
isMember: False
addPrize: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 175
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: -98
makeMember: INVALID_INPUT
getPlace: column=12, hight=59
getPlace: INVALID_INPUT
putOnTop: FAILURE
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: 35
addCostumer: SUCCESS
getPhone: 169
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPhone: 7
getExpenses: -32
getPhone: 87
getExpenses: DOESNT_EXISTS
getPhone: 87
buyRecord: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=12, hight=6
getPlace: INVALID_INPUT
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
getPlace: column=7, hight=83
getPhone: 147
buyRecord: SUCCESS
isMember: False
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: 210
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
getPhone: 127
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 32
getPlace: column=7, hight=83
getPhone: 57
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 75
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
getExpenses: -155
getPlace: column=7, hight=98
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 42
getPhone: INVALID_INPUT
isMember: False
getExpenses: INVALID_INPUT
getPhone: 206
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -253
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getPhone: 176
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: 0
isMember: False
getExpenses: DOESNT_EXISTS
isMember: False
makeMember: ALREADY_EXISTS
getPhone: 175
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
getPhone: 85
makeMember: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: column=8, hight=120
addPrize: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
isMember: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: column=8, hight=94
makeMember: ALREADY_EXISTS
isMember: True
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPlace: column=8, hight=18
isMember: False
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getExpenses: -99
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: SUCCESS
isMember: True
getPlace: column=8, hight=38
buyRecord: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: False
addPrize: INVALID_INPUT
putOnTop: FAILURE
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
getPlace: column=8, hight=58
getPlace: column=1, hight=0
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=8, hight=18
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
makeMember: SUCCESS
getPhone: 19
getPlace: column=8, hight=111
addPrize: SUCCESS
addPrize: INVALID_INPUT
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=8, hight=38
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
getPhone: 207
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: FAILURE
getPlace: column=8, hight=29
buyRecord: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
getPlace: column=8, hight=87
addCostumer: ALREADY_EXISTS
getExpenses: -505
addCostumer: SUCCESS
getPhone: 75
getPhone: 19
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 9
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: SUCCESS
buyRecord: INVALID_INPUT
makeMember: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
getPhone: 75
makeMember: INVALID_INPUT
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
isMember: False
makeMember: SUCCESS
buyRecord: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: 17
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
putOnTop: FAILURE
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: -318
getPhone: 67
isMember: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPlace: column=1, hight=0
buyRecord: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
makeMember: SUCCESS
makeMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: True
getPlace: column=1, hight=114
addCostumer: ALREADY_EXISTS
getPhone: 228
getPlace: column=1, hight=30
putOnTop: FAILURE
isMember: True
isMember: INVALID_INPUT
isMember: True
getExpenses: -139
getPhone: DOESNT_EXISTS
getPlace: column=1, hight=99
getPhone: 244
makeMember: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getExpenses: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: False
getPhone: 66
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
addCostumer: ALREADY_EXISTS
getPlace: column=1, hight=123
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=1, hight=83
isMember: False
getPlace: DOESNT_EXISTS
getExpenses: -442
getExpenses: 0
addCostumer: SUCCESS
getPhone: 5
putOnTop: FAILURE
isMember: INVALID_INPUT
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
getExpenses: -120
getPlace: column=1, hight=114
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: 0
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=1, hight=106
makeMember: SUCCESS
getPhone: 42
addCostumer: SUCCESS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
isMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 47
getPhone: DOESNT_EXISTS
isMember: False
getPhone: 91
buyRecord: SUCCESS
getPlace: column=1, hight=12
addPrize: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
isMember: False
isMember: True
getExpenses: -481
getExpenses: -2
isMember: False
getPhone: 238
getPlace: column=1, hight=139
getPhone: 213
isMember: False
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: FAILURE
buyRecord: DOESNT_EXISTS
makeMember: INVALID_INPUT
isMember: True
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: INVALID_INPUT
getExpenses: -621
addCostumer: SUCCESS
getPlace: column=1, hight=83
getPlace: DOESNT_EXISTS
getPlace: column=1, hight=139
addPrize: SUCCESS
getPlace: column=1, hight=16
makeMember: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
getExpenses: -348
getExpenses: -294
getPhone: 127
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
putOnTop: FAILURE
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 105
isMember: True
putOnTop: FAILURE
addPrize: INVALID_INPUT
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 138
isMember: True
getPhone: 247
addPrize: SUCCESS
putOnTop: FAILURE
isMember: DOESNT_EXISTS
buyRecord: INVALID_INPUT
getPlace: column=1, hight=106
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: -769
getExpenses: -234
getPhone: DOESNT_EXISTS
getPhone: 186
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
getExpenses: INVALID_INPUT
getPlace: column=1, hight=50
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getExpenses: -572
putOnTop: FAILURE
buyRecord: SUCCESS
isMember: False
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: False
addPrize: INVALID_INPUT
isMember: False
putOnTop: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
addPrize: INVALID_INPUT
getExpenses: 0
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 20
isMember: True
putOnTop: FAILURE
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: INVALID_INPUT
isMember: INVALID_INPUT
getPhone: 98
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 9
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: column=1, hight=12
isMember: False
buyRecord: DOESNT_EXISTS
buyRecord: INVALID_INPUT
isMember: True
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: True
isMember: True
getPlace: column=1, hight=99
putOnTop: FAILURE
buyRecord: SUCCESS
isMember: False
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: -116
getPlace: column=1, hight=50
isMember: True
makeMember: ALREADY_EXISTS
addCostumer: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
getExpenses: -914
getPlace: column=1, hight=42
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: False
getExpenses: -650
makeMember: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
putOnTop: INVALID_INPUT
getPhone: 14
addPrize: INVALID_INPUT
putOnTop: FAILURE
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
getPlace: column=1, hight=41
getPhone: DOESNT_EXISTS
getPlace: column=1, hight=70
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: True
isMember: INVALID_INPUT
getPlace: column=1, hight=130
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 87
getPlace: column=1, hight=106
addPrize: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
isMember: False
getPhone: INVALID_INPUT
getPhone: 14
addPrize: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: INVALID_INPUT
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 20
putOnTop: FAILURE
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: INVALID_INPUT
getPhone: 66
addPrize: SUCCESS
getExpenses: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 127
getPhone: 213
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: False
getPlace: column=1, hight=114
addPrize: SUCCESS
getPhone: 47
putOnTop: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 212
makeMember: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 179
makeMember: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getPhone: 179
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
isMember: INVALID_INPUT
getPhone: 213
putOnTop: FAILURE
getExpenses: -74
isMember: True
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPhone: 186
getPlace: column=1, hight=0
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 105
makeMember: ALREADY_EXISTS
getPhone: 163
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
getPhone: 102
getPhone: 85
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
isMember: False
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: column=1, hight=83
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
isMember: False
getExpenses: -1329
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getPlace: column=1, hight=83
putOnTop: FAILURE
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPhone: 36
putOnTop: FAILURE
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=1, hight=12
addPrize: INVALID_INPUT
getPhone: 17
addCostumer: ALREADY_EXISTS
getPlace: column=1, hight=123
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
isMember: False
makeMember: SUCCESS
makeMember: INVALID_INPUT
getPlace: column=1, hight=123
isMember: True
getPlace: DOESNT_EXISTS
isMember: True
getExpenses: -105
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: INVALID_INPUT
addPrize: SUCCESS
isMember: True
putOnTop: INVALID_INPUT
makeMember: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: -102
makeMember: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: -90
addPrize: INVALID_INPUT
addCostumer: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
isMember: INVALID_INPUT
isMember: True
isMember: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=1, hight=50
makeMember: ALREADY_EXISTS
