newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 141
getPhone: 141
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
getPhone: 140
isMember: False
getPlace: column=8, hight=0
getPlace: column=4, hight=0
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
getPhone: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
getPlace: column=2, hight=0
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
isMember: False
getPlace: column=10, hight=0
getPhone: 232
isMember: False
buyRecord: DOESNT_EXISTS
isMember: False
isMember: False
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPlace: column=10, hight=0
getPhone: 232
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: True
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: True
buyRecord: SUCCESS
getPhone: 232
buyRecord: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=10, hight=0
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 232
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: False
buyRecord: SUCCESS
getExpenses: 202
addPrize: INVALID_INPUT
makeMember: SUCCESS
isMember: False
getPhone: 94
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: -75
isMember: True
addPrize: INVALID_INPUT
getPhone: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
getExpenses: 226
addPrize: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: 226
buyRecord: DOESNT_EXISTS
getExpenses: 202
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=21, hight=0
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getPhone: 21
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 94
makeMember: ALREADY_EXISTS
getPlace: column=15, hight=0
isMember: False
getPlace: column=17, hight=0
getPhone: 13
putOnTop: SUCCESS
makeMember: DOESNT_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 13
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=1, hight=16
makeMember: ALREADY_EXISTS
isMember: False
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
isMember: True
isMember: True
buyRecord: SUCCESS
getPlace: column=25, hight=26
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=12
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
addPrize: SUCCESS
makeMember: INVALID_INPUT
isMember: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: column=19, hight=0
addPrize: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 140
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 230
addCostumer: SUCCESS
isMember: False
isMember: False
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addPrize: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
isMember: False
getExpenses: DOESNT_EXISTS
getPlace: column=16, hight=58
getPhone: 46
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=0, hight=0
putOnTop: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: True
addPrize: SUCCESS
isMember: False
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
isMember: True
buyRecord: SUCCESS
getPlace: column=16, hight=35
getPhone: 232
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 140
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 94
buyRecord: SUCCESS
putOnTop: SUCCESS
isMember: False
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=26, hight=0
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPlace: column=24, hight=0
getExpenses: INVALID_INPUT
getExpenses: -129
buyRecord: SUCCESS
isMember: True
isMember: True
getPhone: 220
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: 0
isMember: True
isMember: True
isMember: False
isMember: True
getPlace: column=15, hight=83
addPrize: INVALID_INPUT
getPhone: 21
getExpenses: DOESNT_EXISTS
getPhone: 40
isMember: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: True
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 140
addCostumer: SUCCESS
putOnTop: SUCCESS
getExpenses: -87
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: True
addPrize: SUCCESS
getPlace: column=15, hight=58
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: SUCCESS
getPlace: column=4, hight=57
getPhone: DOESNT_EXISTS
getPhone: 199
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 63
getPhone: 220
addCostumer: SUCCESS
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 35
newMonth: SUCCESS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPlace: column=1, hight=0
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: INVALID_INPUT
makeMember: SUCCESS
getPlace: column=4, hight=0
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 199
isMember: True
getPlace: column=15, hight=0
isMember: True
addCostumer: SUCCESS
putOnTop: SUCCESS
getPhone: 199
isMember: False
getExpenses: INVALID_INPUT
getPhone: 63
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPhone: INVALID_INPUT
getPhone: 140
addCostumer: ALREADY_EXISTS
getExpenses: -54
getPhone: 28
isMember: False
makeMember: SUCCESS
getExpenses: 0
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
putOnTop: SUCCESS
isMember: False
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 140
getPlace: column=8, hight=0
addPrize: INVALID_INPUT
addPrize: SUCCESS
putOnTop: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
makeMember: SUCCESS
putOnTop: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: 0
putOnTop: SUCCESS
isMember: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=8, hight=0
getPhone: 153
isMember: False
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=19, hight=0
getExpenses: 0
addCostumer: SUCCESS
putOnTop: SUCCESS
makeMember: SUCCESS
getExpenses: 0
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 14
putOnTop: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: column=3, hight=0
getExpenses: -60
addCostumer: SUCCESS
makeMember: INVALID_INPUT
getPhone: 94
getPlace: DOESNT_EXISTS
getPhone: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 140
getPlace: column=10, hight=17
isMember: True
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: 0
getExpenses: DOESNT_EXISTS
getPhone: 145
isMember: True
putOnTop: SUCCESS
getPhone: 47
addCostumer: SUCCESS
getPlace: column=19, hight=0
isMember: INVALID_INPUT
putOnTop: SUCCESS
makeMember: SUCCESS
makeMember: INVALID_INPUT
isMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: False
isMember: INVALID_INPUT
getPhone: 160
getPlace: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
isMember: INVALID_INPUT
makeMember: INVALID_INPUT
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: False
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: 140
makeMember: ALREADY_EXISTS
isMember: True
buyRecord: SUCCESS
isMember: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=7, hight=0
addPrize: SUCCESS
isMember: False
addPrize: INVALID_INPUT
isMember: False
isMember: True
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
getPhone: 94
putOnTop: SUCCESS
makeMember: SUCCESS
isMember: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: column=6, hight=0
addPrize: INVALID_INPUT
putOnTop: SUCCESS
putOnTop: SUCCESS
isMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPlace: column=15, hight=73
getPhone: 230
addPrize: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPhone: 35
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getPhone: 14
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 22
isMember: False
isMember: True
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: INVALID_INPUT
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=15, hight=100
addPrize: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: False
makeMember: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 230
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: INVALID_INPUT
getPhone: 40
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: column=15, hight=39
getPhone: 60
getPhone: 222
isMember: False
makeMember: SUCCESS
getPlace: column=15, hight=39
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=15, hight=100
putOnTop: SUCCESS
putOnTop: FAILURE
isMember: False
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
getPlace: column=1, hight=0
putOnTop: SUCCESS
buyRecord: SUCCESS
getPlace: column=15, hight=85
addCostumer: SUCCESS
getPhone: INVALID_INPUT
getPhone: INVALID_INPUT
addPrize: SUCCESS
getExpenses: -391
isMember: True
getPlace: column=15, hight=126
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=15, hight=145
getPlace: column=15, hight=38
makeMember: INVALID_INPUT
putOnTop: FAILURE
isMember: DOESNT_EXISTS
getPlace: column=15, hight=145
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: column=15, hight=73
isMember: True
buyRecord: SUCCESS
addPrize: SUCCESS
getPlace: INVALID_INPUT
isMember: True
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
putOnTop: SUCCESS
getPlace: column=15, hight=113
buyRecord: INVALID_INPUT
getPhone: 8
addPrize: INVALID_INPUT
isMember: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
isMember: DOESNT_EXISTS
getPhone: 154
addCostumer: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=3, hight=47
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: column=3, hight=166
getPhone: 21
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPhone: 144
isMember: False
putOnTop: SUCCESS
getExpenses: -183
addCostumer: ALREADY_EXISTS
getExpenses: -687
getPhone: 121
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: -536
isMember: True
addPrize: INVALID_INPUT
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=2, hight=0
makeMember: DOESNT_EXISTS
isMember: False
getPhone: 242
putOnTop: FAILURE
putOnTop: FAILURE
addCostumer: SUCCESS
getPlace: column=2, hight=25
makeMember: SUCCESS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: column=2, hight=171
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 233
putOnTop: FAILURE
putOnTop: FAILURE
isMember: True
getPhone: 94
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
getPhone: 21
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=2, hight=10
getPlace: column=7, hight=0
isMember: True
getPhone: 81
getPhone: 144
isMember: False
isMember: False
isMember: True
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: DOESNT_EXISTS
isMember: True
getPhone: 154
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
getPlace: INVALID_INPUT
getPlace: column=2, hight=48
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=2, hight=123
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPhone: 233
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
getPhone: INVALID_INPUT
newMonth: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: INVALID_INPUT
isMember: False
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: False
getExpenses: 0
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=4, hight=0
buyRecord: SUCCESS
getPhone: 81
makeMember: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
getExpenses: 0
putOnTop: SUCCESS
addCostumer: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 232
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: True
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: False
getExpenses: INVALID_INPUT
getExpenses: 0
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
isMember: True
getExpenses: -92
getPlace: column=6, hight=0
addCostumer: SUCCESS
getExpenses: 0
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 135
getPlace: column=0, hight=7
addCostumer: ALREADY_EXISTS
putOnTop: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
getPlace: column=8, hight=0
isMember: False
getPhone: 241
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: -92
getPlace: column=3, hight=0
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: column=4, hight=0
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=0, hight=7
buyRecord: INVALID_INPUT
putOnTop: SUCCESS
addPrize: INVALID_INPUT
isMember: True
getExpenses: 0
getPhone: 241
putOnTop: FAILURE
addPrize: INVALID_INPUT
isMember: True
getPhone: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getPhone: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 193
getExpenses: 10
getExpenses: DOESNT_EXISTS
getPhone: 19
putOnTop: FAILURE
getPlace: column=2, hight=0
buyRecord: INVALID_INPUT
makeMember: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: False
addCostumer: SUCCESS
makeMember: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=2, hight=18
makeMember: SUCCESS
getPhone: 144
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: -175
getPhone: 167
getPlace: column=2, hight=34
getPhone: 21
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
getExpenses: -83
isMember: False
getExpenses: -83
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -83
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 227
putOnTop: FAILURE
isMember: False
makeMember: SUCCESS
getPhone: 153
isMember: True
getPhone: 140
getExpenses: -175
buyRecord: INVALID_INPUT
isMember: INVALID_INPUT
getPlace: column=4, hight=0
isMember: False
isMember: True
isMember: True
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: INVALID_INPUT
addCostumer: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: column=2, hight=23
isMember: False
putOnTop: INVALID_INPUT
getPhone: 24
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 183
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 147
isMember: DOESNT_EXISTS
isMember: False
addPrize: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: 195
isMember: False
addCostumer: SUCCESS
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: True
getPhone: 70
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: 102
putOnTop: SUCCESS
getExpenses: -83
getExpenses: DOESNT_EXISTS
getPlace: column=0, hight=0
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
addCostumer: INVALID_INPUT
getPlace: column=0, hight=7
makeMember: INVALID_INPUT
getPlace: column=3, hight=0
addPrize: INVALID_INPUT
makeMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 21
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
isMember: False
isMember: DOESNT_EXISTS
getPhone: 71
getPlace: DOESNT_EXISTS
isMember: True
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=0, hight=56
isMember: True
addCostumer: SUCCESS
putOnTop: FAILURE
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: INVALID_INPUT
makeMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
isMember: True
putOnTop: DOESNT_EXISTS
getExpenses: -83
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
getPlace: column=0, hight=32
getExpenses: DOESNT_EXISTS
getPlace: column=0, hight=10
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: 29
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
isMember: False
getPhone: 67
getPhone: 142
putOnTop: FAILURE
isMember: True
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 24
addPrize: INVALID_INPUT
getPhone: 15
putOnTop: INVALID_INPUT
addPrize: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: True
getExpenses: INVALID_INPUT
getPlace: column=0, hight=40
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
makeMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -268
buyRecord: SUCCESS
getPhone: 195
addPrize: SUCCESS
getPhone: 141
isMember: True
isMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
isMember: False
getPhone: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getPlace: column=0, hight=22
getPlace: INVALID_INPUT
makeMember: DOESNT_EXISTS
getPlace: column=0, hight=22
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: 82
getPhone: 21
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: 87
isMember: True
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=0, hight=32
putOnTop: FAILURE
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: column=0, hight=7
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
isMember: False
buyRecord: SUCCESS
isMember: True
putOnTop: INVALID_INPUT
getPhone: 183
putOnTop: FAILURE
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: INVALID_INPUT
