newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
isMember: True
getPlace: column=7, hight=0
getPlace: column=6, hight=0
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
getExpenses: INVALID_INPUT
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPhone: 75
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
getPhone: DOESNT_EXISTS
getPlace: column=4, hight=12
putOnTop: DOESNT_EXISTS
getPhone: 36
isMember: False
isMember: INVALID_INPUT
makeMember: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: 0
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=8, hight=0
putOnTop: DOESNT_EXISTS
getPhone: 167
addCostumer: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: column=6, hight=0
getExpenses: 44
getExpenses: 26
getPhone: 36
putOnTop: INVALID_INPUT
getExpenses: 0
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: True
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
isMember: INVALID_INPUT
makeMember: SUCCESS
getExpenses: -36
addPrize: SUCCESS
isMember: True
isMember: False
isMember: False
buyRecord: SUCCESS
isMember: False
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=0
getPhone: 105
putOnTop: SUCCESS
addCostumer: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 64
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=4, hight=12
isMember: True
makeMember: ALREADY_EXISTS
isMember: True
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 162
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: INVALID_INPUT
getPlace: column=6, hight=0
putOnTop: FAILURE
getPhone: 162
getPhone: 218
getPhone: INVALID_INPUT
getPhone: 39
isMember: True
getPlace: column=8, hight=0
getPlace: column=6, hight=0
putOnTop: SUCCESS
getPhone: 16
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: FAILURE
getExpenses: 201
makeMember: SUCCESS
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=8, hight=38
isMember: True
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
isMember: False
buyRecord: SUCCESS
getPhone: 162
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
isMember: False
getPhone: 25
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: column=8, hight=0
makeMember: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 162
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 218
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: SUCCESS
getPhone: 118
buyRecord: SUCCESS
getPlace: column=8, hight=38
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 14
putOnTop: SUCCESS
isMember: True
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 167
addPrize: SUCCESS
getExpenses: -126
isMember: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getExpenses: 0
getPlace: column=8, hight=18
isMember: True
getPhone: 162
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 36
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=8, hight=29
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: INVALID_INPUT
putOnTop: FAILURE
getPlace: column=8, hight=18
getPlace: column=8, hight=38
addPrize: SUCCESS
getExpenses: -112
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=8, hight=38
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=8, hight=38
buyRecord: INVALID_INPUT
isMember: True
getPlace: DOESNT_EXISTS
getPlace: column=8, hight=7
isMember: False
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -106
isMember: True
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: True
buyRecord: SUCCESS
getPhone: 40
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 76
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: INVALID_INPUT
isMember: True
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: -459
addPrize: INVALID_INPUT
buyRecord: INVALID_INPUT
isMember: INVALID_INPUT
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
isMember: False
putOnTop: INVALID_INPUT
getExpenses: -245
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: SUCCESS
getExpenses: -173
getPhone: 25
addPrize: INVALID_INPUT
addPrize: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
getExpenses: -204
addCostumer: SUCCESS
isMember: True
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
getExpenses: -312
makeMember: INVALID_INPUT
putOnTop: FAILURE
addPrize: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: SUCCESS
putOnTop: FAILURE
isMember: True
getExpenses: -91
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
isMember: INVALID_INPUT
makeMember: INVALID_INPUT
getPlace: column=3, hight=38
getPhone: 16
buyRecord: SUCCESS
isMember: True
getPlace: column=3, hight=26
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: FAILURE
getExpenses: -223
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: 118
isMember: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
getPhone: 186
getPlace: column=3, hight=26
getPhone: 118
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: INVALID_INPUT
putOnTop: FAILURE
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=3, hight=58
getPhone: 76
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: True
getExpenses: -225
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getPhone: 156
addCostumer: SUCCESS
getPlace: column=3, hight=38
isMember: False
putOnTop: FAILURE
getExpenses: -130
addPrize: INVALID_INPUT
addPrize: SUCCESS
isMember: True
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: 65
getPhone: 159
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
isMember: True
addCostumer: ALREADY_EXISTS
getPlace: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
getPhone: 64
getPlace: INVALID_INPUT
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPhone: 2
putOnTop: FAILURE
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=3, hight=58
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=3, hight=20
makeMember: SUCCESS
addCostumer: SUCCESS
getPhone: 64
isMember: True
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
putOnTop: INVALID_INPUT
putOnTop: INVALID_INPUT
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
putOnTop: FAILURE
getExpenses: -741
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
getExpenses: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=3, hight=26
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=3, hight=0
getPlace: column=3, hight=49
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
isMember: True
addCostumer: SUCCESS
getPhone: 14
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
putOnTop: INVALID_INPUT
getPlace: column=3, hight=58
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getPlace: column=3, hight=49
buyRecord: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 43
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 167
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
isMember: False
addPrize: INVALID_INPUT
makeMember: SUCCESS
getExpenses: 48
getPlace: column=3, hight=69
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 54
getPhone: 54
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: 105
getPhone: 102
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=3, hight=0
getPlace: column=3, hight=69
makeMember: DOESNT_EXISTS
getPhone: 195
makeMember: ALREADY_EXISTS
isMember: False
isMember: INVALID_INPUT
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=3, hight=26
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
getPhone: 65
getPlace: column=3, hight=58
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 36
getPhone: 118
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
isMember: True
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getPhone: 195
getPlace: column=3, hight=69
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: 0
makeMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 185
addCostumer: SUCCESS
getExpenses: -274
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=3, hight=38
isMember: True
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
isMember: True
getPlace: column=3, hight=58
getPlace: column=3, hight=0
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
getPlace: column=3, hight=20
makeMember: SUCCESS
getPhone: 162
getPhone: 105
getExpenses: -83
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: DOESNT_EXISTS
getExpenses: -908
isMember: True
getExpenses: -898
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
isMember: DOESNT_EXISTS
getPhone: 72
makeMember: DOESNT_EXISTS
getPhone: 14
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 54
getPlace: INVALID_INPUT
newMonth: SUCCESS
isMember: True
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
getPlace: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
addCostumer: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: INVALID_INPUT
getPlace: column=7, hight=0
addPrize: SUCCESS
getExpenses: -58
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: -9
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
getPhone: 229
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 250
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=3, hight=0
isMember: False
getPlace: DOESNT_EXISTS
getPhone: 83
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 186
putOnTop: DOESNT_EXISTS
getPhone: 244
buyRecord: INVALID_INPUT
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=8, hight=0
addCostumer: SUCCESS
getPhone: 75
getExpenses: DOESNT_EXISTS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: -98
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
isMember: False
getPhone: 130
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getPhone: 229
getExpenses: -38
getPhone: 76
isMember: INVALID_INPUT
isMember: False
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: INVALID_INPUT
getPhone: 162
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -156
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
putOnTop: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
isMember: False
getPlace: column=0, hight=0
getExpenses: 0
buyRecord: SUCCESS
getPhone: INVALID_INPUT
getPhone: 201
isMember: False
makeMember: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
isMember: True
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 199
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
addCostumer: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: INVALID_INPUT
isMember: True
makeMember: SUCCESS
getPlace: column=5, hight=9
buyRecord: INVALID_INPUT
addCostumer: INVALID_INPUT
getPhone: 167
addPrize: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: DOESNT_EXISTS
putOnTop: SUCCESS
putOnTop: FAILURE
isMember: True
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
getPlace: column=7, hight=0
putOnTop: SUCCESS
getPlace: column=2, hight=0
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: True
getPhone: 167
addPrize: SUCCESS
putOnTop: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
getPhone: 209
getPhone: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPhone: INVALID_INPUT
isMember: True
getPhone: 181
makeMember: SUCCESS
getPhone: 193
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
getPlace: INVALID_INPUT
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 96
putOnTop: FAILURE
getPhone: 54
getExpenses: -445
isMember: INVALID_INPUT
getExpenses: -198
getPhone: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=0, hight=48
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: 16
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -202
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 118
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
getPlace: column=0, hight=0
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: -331
getPhone: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -300
isMember: False
addPrize: SUCCESS
getPhone: 16
addCostumer: SUCCESS
getPhone: 23
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 82
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
getPhone: 43
isMember: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
isMember: False
getPlace: column=0, hight=34
isMember: INVALID_INPUT
getPhone: 76
getPhone: 156
isMember: True
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addPrize: INVALID_INPUT
putOnTop: FAILURE
isMember: False
addCostumer: ALREADY_EXISTS
getPlace: column=0, hight=0
getPhone: 114
getExpenses: DOESNT_EXISTS
getPhone: 61
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
isMember: False
isMember: True
getPhone: 32
buyRecord: SUCCESS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: -434
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
getPlace: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 159
getPhone: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: -506
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: INVALID_INPUT
getPlace: column=0, hight=16
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
putOnTop: FAILURE
putOnTop: INVALID_INPUT
getPhone: 159
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: FAILURE
getExpenses: -676
addPrize: SUCCESS
getPhone: 72
getExpenses: -583
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=0, hight=25
getPlace: column=0, hight=25
buyRecord: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 105
makeMember: ALREADY_EXISTS
getPlace: INVALID_INPUT
isMember: True
putOnTop: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getPlace: column=6, hight=76
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: column=6, hight=0
makeMember: SUCCESS
isMember: False
getPhone: 105
getPlace: column=6, hight=1
isMember: True
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
isMember: True
makeMember: SUCCESS
isMember: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 181
addCostumer: SUCCESS
getExpenses: -486
makeMember: ALREADY_EXISTS
getExpenses: -311
putOnTop: FAILURE
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 94
getPlace: DOESNT_EXISTS
getPhone: 120
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=6, hight=1
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
getExpenses: -271
getPlace: column=6, hight=71
addCostumer: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -571
getExpenses: DOESNT_EXISTS
isMember: False
makeMember: INVALID_INPUT
getPhone: 42
getPlace: column=6, hight=17
makeMember: INVALID_INPUT
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
isMember: False
getPhone: 61
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: -481
addCostumer: SUCCESS
putOnTop: FAILURE
isMember: False
getExpenses: DOESNT_EXISTS
getExpenses: -377
getPlace: column=6, hight=0
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getExpenses: -119
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
