newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=30, hight=0
buyRecord: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
getPlace: column=33, hight=0
getPlace: column=5, hight=0
getExpenses: INVALID_INPUT
isMember: False
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: 21
getPlace: column=17, hight=0
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
isMember: False
isMember: False
putOnTop: SUCCESS
getPhone: 196
isMember: INVALID_INPUT
buyRecord: INVALID_INPUT
makeMember: DOESNT_EXISTS
isMember: True
getPlace: column=9, hight=0
getPlace: column=2, hight=0
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: True
isMember: False
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=12, hight=19
getExpenses: -98
buyRecord: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
getPhone: 21
getPlace: column=25, hight=0
putOnTop: SUCCESS
addCostumer: SUCCESS
getPhone: 21
getExpenses: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
getPlace: column=25, hight=0
addPrize: SUCCESS
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: INVALID_INPUT
addPrize: SUCCESS
getExpenses: INVALID_INPUT
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 196
getPhone: INVALID_INPUT
isMember: False
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=20, hight=0
getPlace: column=30, hight=7
isMember: False
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
buyRecord: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 9
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 114
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
isMember: True
getExpenses: -103
getPhone: DOESNT_EXISTS
makeMember: INVALID_INPUT
getPlace: column=3, hight=0
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
getPlace: column=2, hight=0
getPlace: column=1, hight=7
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPhone: INVALID_INPUT
getPlace: column=31, hight=0
isMember: True
makeMember: SUCCESS
isMember: False
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
getPlace: column=22, hight=0
isMember: True
getPlace: column=19, hight=0
getPlace: column=12, hight=19
getPlace: column=7, hight=0
isMember: True
getExpenses: INVALID_INPUT
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
getExpenses: -141
getPhone: 114
addCostumer: SUCCESS
getExpenses: -38
isMember: False
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: 229
putOnTop: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
getPlace: column=1, hight=68
getPhone: 114
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: INVALID_INPUT
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
isMember: True
addPrize: INVALID_INPUT
putOnTop: SUCCESS
getPlace: column=30, hight=7
getPlace: column=6, hight=0
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
getPlace: column=1, hight=18
putOnTop: SUCCESS
makeMember: SUCCESS
putOnTop: FAILURE
getExpenses: 163
buyRecord: SUCCESS
getPhone: 92
getExpenses: 0
isMember: True
getPhone: 108
getExpenses: 76
getExpenses: 62
getExpenses: DOESNT_EXISTS
isMember: True
putOnTop: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getExpenses: 0
isMember: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: SUCCESS
buyRecord: INVALID_INPUT
isMember: True
isMember: False
getPhone: 114
isMember: True
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=30, hight=7
getExpenses: INVALID_INPUT
makeMember: INVALID_INPUT
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getPhone: 114
makeMember: ALREADY_EXISTS
isMember: False
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
makeMember: SUCCESS
isMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
getPhone: INVALID_INPUT
getPhone: 9
isMember: True
addCostumer: SUCCESS
getPhone: 229
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: False
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: INVALID_INPUT
getExpenses: -50
getPhone: 45
isMember: True
getPhone: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: SUCCESS
getPhone: 159
getPhone: 84
addCostumer: SUCCESS
putOnTop: SUCCESS
putOnTop: INVALID_INPUT
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
makeMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 144
getPlace: column=7, hight=55
getExpenses: -16
isMember: True
makeMember: SUCCESS
makeMember: SUCCESS
isMember: True
putOnTop: FAILURE
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
getExpenses: -88
getPhone: DOESNT_EXISTS
getPlace: column=10, hight=4
getPlace: column=24, hight=0
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: column=7, hight=92
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 207
getExpenses: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: 224
isMember: True
putOnTop: FAILURE
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
getExpenses: -153
getPlace: column=8, hight=107
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 244
isMember: True
getPlace: column=8, hight=172
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=24, hight=0
putOnTop: SUCCESS
getPhone: 114
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
isMember: False
getPhone: 204
getPhone: 114
putOnTop: DOESNT_EXISTS
makeMember: INVALID_INPUT
getExpenses: -153
isMember: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: -229
makeMember: SUCCESS
getPhone: INVALID_INPUT
newMonth: SUCCESS
getPhone: 84
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
getPlace: column=18, hight=0
addCostumer: INVALID_INPUT
getPlace: column=12, hight=0
getExpenses: -94
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: -89
getPhone: 84
putOnTop: SUCCESS
newMonth: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
isMember: INVALID_INPUT
isMember: INVALID_INPUT
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: column=9, hight=8
isMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: True
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: INVALID_INPUT
addPrize: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: SUCCESS
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 159
getPhone: 36
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: 0
getPlace: column=5, hight=0
buyRecord: SUCCESS
addCostumer: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=3, hight=0
isMember: True
buyRecord: INVALID_INPUT
isMember: True
putOnTop: SUCCESS
makeMember: SUCCESS
getExpenses: 0
isMember: True
isMember: DOESNT_EXISTS
getPlace: column=18, hight=0
putOnTop: SUCCESS
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
getPhone: INVALID_INPUT
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: column=17, hight=0
isMember: True
addCostumer: SUCCESS
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
isMember: False
getPhone: 244
isMember: True
isMember: True
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 105
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
isMember: False
putOnTop: SUCCESS
buyRecord: SUCCESS
getPhone: 200
getPlace: column=4, hight=0
isMember: True
addPrize: SUCCESS
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: 0
putOnTop: SUCCESS
buyRecord: SUCCESS
isMember: False
putOnTop: SUCCESS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
putOnTop: SUCCESS
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
getPlace: column=9, hight=56
isMember: False
getPlace: column=11, hight=0
getExpenses: INVALID_INPUT
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=9, hight=22
getExpenses: -37
getPhone: 21
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 108
putOnTop: DOESNT_EXISTS
isMember: True
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: True
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPhone: 171
buyRecord: SUCCESS
addPrize: INVALID_INPUT
makeMember: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
isMember: True
getExpenses: 64
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 208
makeMember: SUCCESS
addPrize: SUCCESS
getPhone: 127
putOnTop: SUCCESS
makeMember: SUCCESS
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -82
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 76
addCostumer: SUCCESS
isMember: False
getPhone: 200
getExpenses: 63
addCostumer: SUCCESS
getPlace: column=9, hight=8
getPhone: 92
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 36
getExpenses: -135
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
isMember: True
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: column=8, hight=12
getPlace: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=7, hight=0
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
isMember: False
getPlace: column=17, hight=0
getPlace: column=0, hight=0
makeMember: SUCCESS
isMember: True
putOnTop: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPhone: 158
addPrize: SUCCESS
getPhone: 244
addPrize: SUCCESS
getPhone: 114
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: 245
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 245
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: False
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: INVALID_INPUT
getExpenses: -363
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
getPhone: 128
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 114
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
getPhone: 36
getPlace: column=7, hight=144
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: SUCCESS
isMember: False
isMember: False
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
isMember: False
getPhone: 158
isMember: DOESNT_EXISTS
makeMember: INVALID_INPUT
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
getPlace: column=7, hight=144
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=7, hight=144
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: True
getExpenses: -313
putOnTop: FAILURE
addCostumer: SUCCESS
getPhone: 133
putOnTop: FAILURE
putOnTop: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: True
isMember: True
addCostumer: SUCCESS
isMember: True
getPlace: DOESNT_EXISTS
getPlace: column=7, hight=105
addPrize: SUCCESS
putOnTop: INVALID_INPUT
isMember: True
addCostumer: ALREADY_EXISTS
getPlace: column=7, hight=93
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
getPlace: column=7, hight=168
getPlace: column=7, hight=113
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: INVALID_INPUT
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: True
putOnTop: DOESNT_EXISTS
getExpenses: -560
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getExpenses: -386
makeMember: INVALID_INPUT
isMember: False
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=7, hight=127
putOnTop: FAILURE
addCostumer: SUCCESS
getPhone: 92
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 190
addPrize: INVALID_INPUT
getPhone: 114
buyRecord: SUCCESS
getExpenses: -438
addPrize: INVALID_INPUT
getPlace: column=7, hight=25
putOnTop: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
getPhone: 172
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getPhone: 172
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=7, hight=38
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
getPhone: 92
getPhone: 242
buyRecord: SUCCESS
getPlace: column=7, hight=168
putOnTop: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -206
makeMember: ALREADY_EXISTS
getPlace: column=7, hight=144
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: SUCCESS
getPlace: column=7, hight=210
getPlace: column=7, hight=53
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: -553
getPlace: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: -35
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=7, hight=127
getPhone: INVALID_INPUT
getPhone: 131
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
getPlace: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getPlace: column=7, hight=113
getPlace: column=7, hight=105
isMember: True
buyRecord: SUCCESS
getPlace: INVALID_INPUT
getExpenses: -484
isMember: True
putOnTop: FAILURE
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=113
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -240
getPhone: 114
putOnTop: FAILURE
getPhone: 158
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=7, hight=113
getPhone: 210
getPhone: 114
makeMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=7, hight=93
putOnTop: FAILURE
getPlace: column=7, hight=168
addPrize: SUCCESS
putOnTop: FAILURE
makeMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: -35
getPhone: 140
getPlace: column=7, hight=127
getPhone: 204
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: -114
addCostumer: SUCCESS
getPlace: column=7, hight=64
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=7, hight=144
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 73
getPlace: column=7, hight=38
getPlace: DOESNT_EXISTS
isMember: True
putOnTop: FAILURE
isMember: True
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 44
makeMember: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
isMember: False
buyRecord: SUCCESS
getPhone: 245
isMember: False
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
getPhone: 231
putOnTop: FAILURE
isMember: False
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
getExpenses: -714
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
makeMember: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
getPlace: column=7, hight=64
buyRecord: SUCCESS
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
isMember: True
getPlace: column=7, hight=81
makeMember: ALREADY_EXISTS
isMember: True
getPlace: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: column=7, hight=64
buyRecord: SUCCESS
getExpenses: -630
addPrize: SUCCESS
isMember: False
buyRecord: SUCCESS
getPhone: 114
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=7, hight=137
buyRecord: SUCCESS
getPhone: 114
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: FAILURE
getPlace: column=7, hight=0
putOnTop: INVALID_INPUT
getPlace: column=7, hight=190
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: -852
getExpenses: -687
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=7, hight=113
buyRecord: SUCCESS
getPlace: column=7, hight=161
getPlace: INVALID_INPUT
isMember: False
putOnTop: FAILURE
isMember: False
addCostumer: SUCCESS
getPlace: column=7, hight=53
getPhone: 116
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: FAILURE
getPhone: 76
getPlace: column=7, hight=144
buyRecord: SUCCESS
getExpenses: -869
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: True
makeMember: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: -617
isMember: True
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 73
getPlace: column=7, hight=137
buyRecord: SUCCESS
getExpenses: -83
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 229
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: 6
getPhone: 212
getPlace: column=7, hight=64
addPrize: SUCCESS
getPhone: 196
buyRecord: INVALID_INPUT
makeMember: SUCCESS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 189
buyRecord: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
isMember: False
getExpenses: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
isMember: True
putOnTop: DOESNT_EXISTS
isMember: True
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=7, hight=34
addPrize: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
getPhone: 229
makeMember: INVALID_INPUT
getPlace: column=7, hight=190
addCostumer: SUCCESS
getPhone: 16
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 170
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
getPlace: column=7, hight=168
isMember: False
addPrize: SUCCESS
getPlace: column=7, hight=25
getPlace: column=7, hight=14
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=25
getPlace: DOESNT_EXISTS
getExpenses: -786
