newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: False
getPhone: 44
getPlace: column=4, hight=0
getPlace: column=8, hight=0
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: column=5, hight=0
buyRecord: SUCCESS
putOnTop: SUCCESS
getExpenses: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: INVALID_INPUT
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPlace: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: INVALID_INPUT
getPhone: 44
addPrize: INVALID_INPUT
getExpenses: -33
getPlace: column=8, hight=0
getPlace: column=8, hight=0
isMember: True
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
getPhone: 44
isMember: INVALID_INPUT
getPhone: INVALID_INPUT
getExpenses: 107
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=6, hight=0
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=8, hight=6
buyRecord: SUCCESS
getExpenses: 68
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
putOnTop: SUCCESS
makeMember: SUCCESS
getPhone: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: 107
addCostumer: SUCCESS
isMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
getPlace: column=8, hight=0
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
isMember: INVALID_INPUT
