newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: INVALID_INPUT
getPhone: DOESNT_EXISTS
getPhone: 240
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
isMember: True
addCostumer: SUCCESS
getPhone: 147
getPlace: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
getPlace: column=8, hight=0
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 9
addPrize: SUCCESS
addPrize: INVALID_INPUT
isMember: True
putOnTop: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 155
makeMember: SUCCESS
addPrize: SUCCESS
getPhone: 9
putOnTop: SUCCESS
getPhone: DOESNT_EXISTS
putOnTop: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
isMember: INVALID_INPUT
putOnTop: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
getPlace: column=16, hight=0
getExpenses: 122
addCostumer: SUCCESS
putOnTop: SUCCESS
isMember: False
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
getPlace: column=17, hight=0
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
isMember: INVALID_INPUT
isMember: False
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=8, hight=0
addCostumer: SUCCESS
getPhone: 223
isMember: False
getPlace: column=1, hight=0
addCostumer: SUCCESS
isMember: False
getPlace: column=3, hight=0
getPhone: 138
addPrize: INVALID_INPUT
isMember: False
putOnTop: FAILURE
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
getPhone: 161
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: 223
addCostumer: SUCCESS
getPhone: 161
makeMember: INVALID_INPUT
putOnTop: FAILURE
isMember: False
getPhone: 240
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: column=17, hight=0
getExpenses: 5
putOnTop: SUCCESS
buyRecord: INVALID_INPUT
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 219
makeMember: SUCCESS
getPhone: 63
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
isMember: False
isMember: False
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
getPhone: 223
makeMember: SUCCESS
getPhone: 20
getPhone: 64
addCostumer: SUCCESS
getPhone: 208
getPlace: column=16, hight=0
buyRecord: SUCCESS
getExpenses: 0
putOnTop: FAILURE
addPrize: SUCCESS
getPlace: column=18, hight=0
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=17, hight=0
getExpenses: -417
isMember: DOESNT_EXISTS
getPhone: 161
buyRecord: INVALID_INPUT
getPlace: column=13, hight=35
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
getPhone: 147
makeMember: SUCCESS
getExpenses: -417
getPhone: 44
buyRecord: INVALID_INPUT
getPhone: 240
getPhone: 137
isMember: True
getExpenses: -95
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: DOESNT_EXISTS
getPhone: 208
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: column=15, hight=63
putOnTop: FAILURE
makeMember: SUCCESS
getPhone: 20
getPlace: column=15, hight=161
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getPlace: column=15, hight=52
addPrize: INVALID_INPUT
getPhone: 138
makeMember: INVALID_INPUT
isMember: False
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: True
isMember: True
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: -226
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: INVALID_INPUT
addPrize: SUCCESS
isMember: True
getPlace: column=16, hight=0
putOnTop: SUCCESS
getPhone: 132
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=16, hight=151
addCostumer: SUCCESS
putOnTop: SUCCESS
buyRecord: DOESNT_EXISTS
getPhone: 223
isMember: False
makeMember: INVALID_INPUT
isMember: False
makeMember: ALREADY_EXISTS
isMember: True
buyRecord: SUCCESS
getExpenses: -24
makeMember: SUCCESS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: INVALID_INPUT
makeMember: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
isMember: True
getExpenses: -266
addCostumer: SUCCESS
getPhone: 227
putOnTop: FAILURE
isMember: False
getPhone: 163
getPhone: 132
getPlace: column=8, hight=0
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
isMember: False
putOnTop: FAILURE
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: column=8, hight=15
buyRecord: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPhone: 136
isMember: True
putOnTop: FAILURE
isMember: INVALID_INPUT
isMember: True
putOnTop: FAILURE
getPhone: 165
putOnTop: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 240
addPrize: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
isMember: False
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -266
addPrize: SUCCESS
getPlace: column=8, hight=143
addPrize: SUCCESS
isMember: True
makeMember: SUCCESS
getPhone: 28
getPhone: DOESNT_EXISTS
getPhone: 137
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: INVALID_INPUT
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
addPrize: SUCCESS
getExpenses: -276
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 225
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
getPlace: column=8, hight=134
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: 69
getExpenses: -211
addPrize: SUCCESS
makeMember: INVALID_INPUT
getPhone: 57
buyRecord: SUCCESS
getPlace: column=8, hight=0
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=8, hight=232
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: -90
isMember: False
getPhone: 165
putOnTop: SUCCESS
isMember: False
getPlace: column=5, hight=239
addCostumer: SUCCESS
getPlace: column=5, hight=151
getPhone: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
getPhone: 65
getPhone: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: column=5, hight=35
makeMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: -53
addPrize: SUCCESS
buyRecord: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: -156
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
putOnTop: FAILURE
isMember: False
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=5, hight=54
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=5, hight=94
getExpenses: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -62
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=5, hight=0
addCostumer: SUCCESS
isMember: INVALID_INPUT
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: column=5, hight=255
getPhone: 41
getPhone: INVALID_INPUT
getExpenses: -135
buyRecord: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
getPlace: INVALID_INPUT
isMember: DOESNT_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: True
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
isMember: True
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
isMember: True
makeMember: ALREADY_EXISTS
getPhone: 225
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
getPhone: DOESNT_EXISTS
isMember: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getPlace: column=5, hight=88
isMember: True
putOnTop: SUCCESS
getPhone: INVALID_INPUT
getPlace: column=4, hight=143
buyRecord: SUCCESS
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: column=4, hight=106
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
isMember: True
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: False
getExpenses: -455
addPrize: SUCCESS
getPlace: column=4, hight=109
makeMember: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
isMember: INVALID_INPUT
getPhone: 63
addPrize: SUCCESS
addPrize: SUCCESS
isMember: True
makeMember: DOESNT_EXISTS
isMember: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPhone: 9
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
getPhone: 155
buyRecord: INVALID_INPUT
isMember: False
putOnTop: FAILURE
getPlace: column=4, hight=103
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: INVALID_INPUT
getExpenses: INVALID_INPUT
getPlace: column=4, hight=83
buyRecord: SUCCESS
getPlace: column=4, hight=69
isMember: False
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: -263
buyRecord: SUCCESS
putOnTop: FAILURE
getPhone: 155
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
buyRecord: INVALID_INPUT
isMember: True
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getPhone: 74
getPhone: DOESNT_EXISTS
newMonth: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 123
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPhone: 28
putOnTop: DOESNT_EXISTS
newMonth: SUCCESS
getPhone: 20
makeMember: DOESNT_EXISTS
putOnTop: SUCCESS
getPhone: 123
putOnTop: SUCCESS
getPhone: 96
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 219
buyRecord: SUCCESS
getPlace: column=2, hight=0
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 165
addPrize: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
getPlace: column=15, hight=0
getPlace: column=16, hight=0
makeMember: ALREADY_EXISTS
getPlace: column=13, hight=15
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 96
buyRecord: SUCCESS
isMember: True
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=11, hight=0
getPhone: 136
getExpenses: DOESNT_EXISTS
getPlace: column=19, hight=0
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getPhone: 132
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 124
addCostumer: SUCCESS
getPhone: 113
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: 0
getExpenses: 0
isMember: False
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
getPlace: column=6, hight=0
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
buyRecord: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getPhone: 163
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=7, hight=17
getPlace: column=18, hight=0
getPlace: column=1, hight=0
getPhone: 79
putOnTop: SUCCESS
putOnTop: SUCCESS
getPlace: column=20, hight=29
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=4, hight=20
makeMember: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPhone: 81
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=6, hight=0
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: 100
getPhone: 75
addPrize: SUCCESS
addCostumer: SUCCESS
getPhone: 208
addCostumer: SUCCESS
isMember: True
buyRecord: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: INVALID_INPUT
makeMember: SUCCESS
getExpenses: INVALID_INPUT
getPhone: 247
isMember: DOESNT_EXISTS
putOnTop: INVALID_INPUT
addCostumer: INVALID_INPUT
addPrize: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 166
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
addPrize: SUCCESS
addCostumer: INVALID_INPUT
isMember: False
isMember: True
putOnTop: SUCCESS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
isMember: False
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: False
getPlace: column=7, hight=17
putOnTop: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: -173
getPhone: 44
addPrize: INVALID_INPUT
isMember: False
makeMember: ALREADY_EXISTS
getExpenses: 0
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -330
addCostumer: SUCCESS
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: INVALID_INPUT
isMember: True
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 175
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
getPhone: 227
isMember: True
getPlace: column=20, hight=51
getPlace: column=20, hight=29
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=20, hight=51
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 65
getPhone: 135
buyRecord: INVALID_INPUT
putOnTop: SUCCESS
getPhone: 217
getPhone: 91
addPrize: SUCCESS
getPhone: 227
isMember: True
addPrize: SUCCESS
getExpenses: INVALID_INPUT
getPlace: column=18, hight=129
getPlace: column=6, hight=0
isMember: True
getPhone: 99
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=6, hight=1
getExpenses: DOESNT_EXISTS
getPhone: 141
getPhone: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
getPhone: 64
buyRecord: DOESNT_EXISTS
getPhone: 79
getExpenses: INVALID_INPUT
getExpenses: -267
makeMember: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
isMember: False
addPrize: INVALID_INPUT
putOnTop: FAILURE
getPhone: 247
getExpenses: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPlace: column=18, hight=108
getPlace: column=6, hight=1
getExpenses: -88
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
isMember: False
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=18, hight=67
addCostumer: ALREADY_EXISTS
putOnTop: SUCCESS
getPhone: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: True
addPrize: INVALID_INPUT
addCostumer: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getPlace: column=18, hight=67
isMember: INVALID_INPUT
getPlace: column=18, hight=129
isMember: DOESNT_EXISTS
getPlace: column=5, hight=0
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
getPlace: INVALID_INPUT
getExpenses: -367
addCostumer: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
isMember: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 163
getPlace: column=18, hight=95
getPlace: column=18, hight=95
isMember: False
isMember: False
getPlace: column=18, hight=15
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
makeMember: SUCCESS
getPlace: column=18, hight=67
buyRecord: SUCCESS
getPhone: 247
addPrize: SUCCESS
getPlace: INVALID_INPUT
putOnTop: FAILURE
getPlace: column=5, hight=0
addPrize: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getExpenses: -71
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPhone: 91
makeMember: INVALID_INPUT
getPlace: DOESNT_EXISTS
isMember: False
getPhone: 56
isMember: DOESNT_EXISTS
isMember: True
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: INVALID_INPUT
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=11, hight=14
putOnTop: FAILURE
getPlace: INVALID_INPUT
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=11, hight=42
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
isMember: True
putOnTop: FAILURE
getPlace: column=11, hight=0
getExpenses: DOESNT_EXISTS
getPhone: 18
addPrize: SUCCESS
getPlace: column=11, hight=107
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=11, hight=14
getPhone: 233
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 81
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=11, hight=164
putOnTop: FAILURE
makeMember: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
getPhone: 219
buyRecord: SUCCESS
getPhone: 135
putOnTop: FAILURE
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
putOnTop: FAILURE
addPrize: SUCCESS
getPhone: 237
buyRecord: INVALID_INPUT
makeMember: SUCCESS
putOnTop: FAILURE
putOnTop: INVALID_INPUT
getExpenses: -37
addCostumer: SUCCESS
getPhone: 164
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
getExpenses: -37
buyRecord: SUCCESS
getExpenses: -501
makeMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: 0
getPhone: 237
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
putOnTop: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getPlace: column=12, hight=0
getPlace: column=12, hight=67
putOnTop: FAILURE
getPhone: 9
getPlace: column=12, hight=137
buyRecord: DOESNT_EXISTS
isMember: True
getPlace: column=12, hight=114
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=12, hight=29
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: column=12, hight=114
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: column=12, hight=146
isMember: DOESNT_EXISTS
getPhone: 122
buyRecord: INVALID_INPUT
getPhone: 128
addCostumer: ALREADY_EXISTS
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
getExpenses: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPhone: 96
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=12, hight=7
addPrize: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
buyRecord: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
isMember: False
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 212
getPhone: 74
