newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=12, hight=0
isMember: False
getPlace: INVALID_INPUT
isMember: False
putOnTop: SUCCESS
putOnTop: SUCCESS
makeMember: SUCCESS
getExpenses: 0
getPlace: DOESNT_EXISTS
getExpenses: 0
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
isMember: False
getPhone: 155
addPrize: SUCCESS
getPhone: INVALID_INPUT
getPhone: 2
putOnTop: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
getExpenses: 100
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
isMember: True
putOnTop: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: True
putOnTop: SUCCESS
isMember: INVALID_INPUT
addPrize: SUCCESS
makeMember: INVALID_INPUT
isMember: False
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=8, hight=12
getPlace: INVALID_INPUT
putOnTop: INVALID_INPUT
addPrize: SUCCESS
getExpenses: -45
putOnTop: SUCCESS
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: -45
putOnTop: SUCCESS
makeMember: SUCCESS
getExpenses: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: -45
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=8, hight=40
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: INVALID_INPUT
isMember: True
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: DOESNT_EXISTS
getPhone: 2
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
getExpenses: 100
addCostumer: SUCCESS
getExpenses: 0
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
getPhone: 175
getExpenses: 200
getExpenses: DOESNT_EXISTS
getPhone: 142
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: 101
makeMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
