newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=12, hight=0
isMember: False
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: SUCCESS
getPlace: column=11, hight=13
getExpenses: 0
isMember: DOESNT_EXISTS
isMember: False
getPhone: 246
getPhone: 214
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=15, hight=0
addPrize: INVALID_INPUT
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 42
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=13, hight=0
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 42
putOnTop: INVALID_INPUT
getPlace: column=12, hight=0
buyRecord: SUCCESS
getPlace: column=7, hight=0
getExpenses: 194
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: column=7, hight=0
getPlace: column=11, hight=0
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
makeMember: SUCCESS
addPrize: SUCCESS
getPlace: INVALID_INPUT
getPlace: INVALID_INPUT
getExpenses: -87
addPrize: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
getPhone: 214
getPhone: 246
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
isMember: True
addCostumer: SUCCESS
putOnTop: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
isMember: True
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 45
getPhone: 45
makeMember: ALREADY_EXISTS
isMember: True
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 227
addPrize: SUCCESS
isMember: False
getPhone: 42
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
getPhone: 206
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
