newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
makeMember: SUCCESS
buyRecord: INVALID_INPUT
makeMember: SUCCESS
getExpenses: 0
buyRecord: DOESNT_EXISTS
isMember: False
putOnTop: SUCCESS
getPhone: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
addPrize: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: column=10, hight=0
buyRecord: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=1, hight=0
getPlace: column=0, hight=16
isMember: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: 102
isMember: False
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 119
isMember: False
getPlace: column=1, hight=0
getPhone: 93
getExpenses: -167
getExpenses: 200
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 119
getPlace: column=3, hight=0
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: False
isMember: False
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 24
putOnTop: FAILURE
makeMember: SUCCESS
getPhone: 176
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=5, hight=0
putOnTop: SUCCESS
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: INVALID_INPUT
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
getPlace: column=7, hight=0
addCostumer: SUCCESS
isMember: INVALID_INPUT
buyRecord: SUCCESS
getPlace: INVALID_INPUT
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=3, hight=0
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
isMember: False
getPlace: INVALID_INPUT
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 173
putOnTop: SUCCESS
addCostumer: SUCCESS
getPlace: column=2, hight=2
makeMember: SUCCESS
putOnTop: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 48
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: 179
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
getPhone: INVALID_INPUT
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: 34
addCostumer: SUCCESS
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: 76
getExpenses: DOESNT_EXISTS
getExpenses: -105
getPhone: 173
isMember: True
isMember: False
makeMember: ALREADY_EXISTS
getPhone: 17
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -251
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: INVALID_INPUT
getPlace: column=0, hight=0
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: 0
makeMember: ALREADY_EXISTS
isMember: False
putOnTop: SUCCESS
makeMember: INVALID_INPUT
getPhone: 17
getPlace: column=0, hight=0
addCostumer: ALREADY_EXISTS
getPhone: 96
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 249
getExpenses: INVALID_INPUT
isMember: False
buyRecord: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPlace: column=0, hight=16
getPhone: 34
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: 0
addCostumer: SUCCESS
getPhone: 175
addCostumer: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=9, hight=0
buyRecord: SUCCESS
getPhone: 76
addPrize: SUCCESS
getPhone: 86
addPrize: INVALID_INPUT
isMember: True
makeMember: SUCCESS
getPlace: column=9, hight=0
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: 0
getPhone: 8
buyRecord: SUCCESS
isMember: False
getPhone: 121
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=0, hight=33
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=0, hight=33
makeMember: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 84
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: column=2, hight=0
isMember: False
addCostumer: SUCCESS
getPhone: 249
putOnTop: FAILURE
addCostumer: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
getPhone: 109
getPhone: 170
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
getPlace: column=2, hight=0
isMember: False
addPrize: SUCCESS
putOnTop: SUCCESS
getPhone: 176
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
isMember: True
isMember: False
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: 177
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: FAILURE
isMember: False
getPlace: column=1, hight=35
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 109
buyRecord: SUCCESS
getPhone: 109
getPhone: 48
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: INVALID_INPUT
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: -30
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPlace: column=1, hight=82
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
getPlace: column=1, hight=52
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 121
getPhone: INVALID_INPUT
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getExpenses: -288
addPrize: SUCCESS
getPhone: 77
getPhone: 249
getPlace: column=1, hight=35
isMember: INVALID_INPUT
getPhone: 48
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: True
getExpenses: -314
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: False
addCostumer: SUCCESS
isMember: False
addPrize: INVALID_INPUT
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
getExpenses: -64
putOnTop: DOESNT_EXISTS
getPlace: INVALID_INPUT
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPhone: 247
buyRecord: SUCCESS
isMember: False
addPrize: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -126
getPlace: DOESNT_EXISTS
addCostumer: INVALID_INPUT
isMember: False
buyRecord: INVALID_INPUT
getExpenses: -319
makeMember: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 231
makeMember: ALREADY_EXISTS
getPhone: 17
makeMember: SUCCESS
addPrize: SUCCESS
getPhone: 101
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: column=1, hight=0
getPhone: 34
makeMember: ALREADY_EXISTS
getPhone: INVALID_INPUT
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=1, hight=15
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -315
isMember: True
makeMember: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
putOnTop: INVALID_INPUT
getPlace: column=1, hight=35
getExpenses: INVALID_INPUT
makeMember: SUCCESS
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 138
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
isMember: True
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 94
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: 109
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 62
buyRecord: SUCCESS
addPrize: INVALID_INPUT
putOnTop: FAILURE
isMember: True
getPlace: column=1, hight=19
getPlace: column=1, hight=0
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=1, hight=13
addCostumer: INVALID_INPUT
makeMember: SUCCESS
getPlace: column=1, hight=42
getExpenses: -859
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
getExpenses: -236
isMember: True
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
isMember: DOESNT_EXISTS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: DOESNT_EXISTS
getPhone: 177
isMember: False
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
isMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPlace: column=1, hight=52
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: INVALID_INPUT
getPlace: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=1, hight=11
getPlace: DOESNT_EXISTS
getPlace: INVALID_INPUT
putOnTop: FAILURE
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPhone: 138
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 94
makeMember: SUCCESS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 121
getPhone: 177
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 177
addPrize: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
isMember: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
getExpenses: -446
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 176
putOnTop: DOESNT_EXISTS
putOnTop: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -402
getPhone: DOESNT_EXISTS
isMember: False
getPhone: 34
getPhone: 173
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 177
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: -566
addCostumer: SUCCESS
getPhone: 138
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=1, hight=13
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
isMember: False
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: INVALID_INPUT
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 39
isMember: True
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
getPhone: 191
buyRecord: INVALID_INPUT
isMember: False
getPlace: column=1, hight=19
getPlace: column=1, hight=42
makeMember: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: False
isMember: True
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
getPhone: 23
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
isMember: True
getExpenses: -592
isMember: True
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: 247
getPlace: column=1, hight=13
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 8
getPhone: 137
isMember: True
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
getPlace: DOESNT_EXISTS
getPhone: 23
addCostumer: SUCCESS
getPlace: column=1, hight=52
getPlace: column=1, hight=13
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
getPlace: column=1, hight=13
putOnTop: FAILURE
isMember: True
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 117
getPlace: column=1, hight=0
getPlace: INVALID_INPUT
putOnTop: FAILURE
getPlace: column=1, hight=0
getExpenses: -667
makeMember: SUCCESS
getPlace: column=1, hight=42
isMember: False
getExpenses: -522
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: INVALID_INPUT
getPhone: 8
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
isMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getPlace: column=1, hight=11
addPrize: INVALID_INPUT
getPhone: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 7
addPrize: INVALID_INPUT
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: -1099
isMember: False
getPlace: column=1, hight=15
buyRecord: INVALID_INPUT
isMember: False
getPlace: DOESNT_EXISTS
getPlace: column=1, hight=11
putOnTop: FAILURE
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 170
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=1, hight=0
addCostumer: SUCCESS
putOnTop: FAILURE
getExpenses: -975
getExpenses: DOESNT_EXISTS
getPhone: 101
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=1, hight=15
getPlace: column=1, hight=52
isMember: True
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 39
buyRecord: SUCCESS
getPlace: column=1, hight=82
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: INVALID_INPUT
getPlace: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
isMember: INVALID_INPUT
getPhone: 8
isMember: INVALID_INPUT
getExpenses: -590
putOnTop: FAILURE
putOnTop: INVALID_INPUT
getPlace: column=1, hight=82
buyRecord: SUCCESS
getPhone: INVALID_INPUT
isMember: True
addCostumer: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPhone: 83
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
addPrize: SUCCESS
isMember: True
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
isMember: False
isMember: True
getPhone: 205
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
putOnTop: FAILURE
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=1, hight=68
getPlace: column=1, hight=97
addPrize: SUCCESS
newMonth: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
getPhone: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
getPhone: 176
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: 0
putOnTop: DOESNT_EXISTS
isMember: True
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: True
getPlace: DOESNT_EXISTS
isMember: INVALID_INPUT
makeMember: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
isMember: False
makeMember: INVALID_INPUT
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: -75
getPlace: INVALID_INPUT
getPhone: 234
getPhone: 119
isMember: True
makeMember: SUCCESS
getPhone: 137
getPhone: 93
putOnTop: SUCCESS
getExpenses: -16
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getPlace: column=4, hight=0
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
getPhone: 204
getPlace: DOESNT_EXISTS
getPhone: 0
getPhone: 177
addPrize: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
getPlace: column=1, hight=0
makeMember: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
getPhone: 113
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
putOnTop: INVALID_INPUT
getPlace: column=1, hight=0
getPlace: column=4, hight=0
makeMember: DOESNT_EXISTS
getPhone: 173
addCostumer: SUCCESS
makeMember: INVALID_INPUT
getPlace: column=0, hight=0
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPlace: column=3, hight=0
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 49
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
getPhone: 48
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
isMember: True
getPlace: column=4, hight=0
isMember: False
putOnTop: INVALID_INPUT
addPrize: SUCCESS
getPhone: INVALID_INPUT
getPlace: DOESNT_EXISTS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
getExpenses: -56
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: INVALID_INPUT
isMember: False
isMember: True
getPhone: 84
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: INVALID_INPUT
addCostumer: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
getExpenses: INVALID_INPUT
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
makeMember: SUCCESS
isMember: True
addCostumer: ALREADY_EXISTS
getPlace: column=0, hight=54
addCostumer: SUCCESS
getPlace: column=4, hight=0
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
getPhone: 117
isMember: INVALID_INPUT
isMember: True
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 144
addCostumer: INVALID_INPUT
isMember: True
addCostumer: SUCCESS
getPhone: 204
getPhone: 84
getPhone: 214
makeMember: INVALID_INPUT
getExpenses: -180
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 231
getExpenses: DOESNT_EXISTS
getExpenses: -180
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPlace: column=0, hight=0
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
isMember: INVALID_INPUT
getPhone: 4
putOnTop: INVALID_INPUT
getPhone: 177
getExpenses: -189
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 34
