newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: INVALID_INPUT
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPhone: 180
isMember: False
putOnTop: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
isMember: INVALID_INPUT
getExpenses: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: 0
getPhone: 133
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
getPhone: INVALID_INPUT
isMember: INVALID_INPUT
isMember: INVALID_INPUT
isMember: False
isMember: False
getPlace: column=5, hight=17
addCostumer: INVALID_INPUT
getPlace: column=4, hight=0
getPhone: 42
getPlace: column=10, hight=17
getPhone: 180
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=0, hight=0
buyRecord: SUCCESS
isMember: False
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 42
addPrize: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 18
getPlace: DOESNT_EXISTS
isMember: False
isMember: True
newMonth: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: 0
getPlace: column=12, hight=0
getPhone: 133
makeMember: SUCCESS
isMember: DOESNT_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: 0
addCostumer: SUCCESS
getPlace: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: True
buyRecord: SUCCESS
isMember: False
getPlace: column=3, hight=0
buyRecord: SUCCESS
isMember: False
isMember: DOESNT_EXISTS
getExpenses: 0
isMember: True
putOnTop: INVALID_INPUT
getPhone: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
isMember: False
putOnTop: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
getPhone: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
getPlace: column=2, hight=0
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: column=4, hight=0
addPrize: SUCCESS
getPlace: column=0, hight=6
getPhone: 95
getPlace: DOESNT_EXISTS
isMember: False
makeMember: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: True
getPlace: column=2, hight=0
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
getPlace: column=8, hight=0
buyRecord: SUCCESS
makeMember: INVALID_INPUT
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPhone: 42
putOnTop: FAILURE
getPlace: column=5, hight=6
getPhone: 2
getPhone: 42
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 145
addCostumer: SUCCESS
isMember: True
addPrize: SUCCESS
isMember: True
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 146
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
addCostumer: INVALID_INPUT
getPhone: 159
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: INVALID_INPUT
getPlace: column=10, hight=0
getExpenses: DOESNT_EXISTS
getPlace: column=10, hight=21
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -83
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
isMember: True
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: INVALID_INPUT
getPhone: 133
getPhone: 17
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
getPlace: INVALID_INPUT
makeMember: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
isMember: False
isMember: False
getPlace: INVALID_INPUT
getPhone: 102
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getPhone: 178
putOnTop: SUCCESS
isMember: False
putOnTop: SUCCESS
isMember: False
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
isMember: True
getPhone: INVALID_INPUT
getPhone: 102
isMember: False
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
addPrize: SUCCESS
getPhone: 145
buyRecord: SUCCESS
getPlace: column=11, hight=64
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=9, hight=0
putOnTop: FAILURE
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: -302
isMember: False
putOnTop: SUCCESS
getExpenses: 9
buyRecord: SUCCESS
isMember: True
putOnTop: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: 18
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getExpenses: -17
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
isMember: True
getPlace: column=12, hight=0
buyRecord: SUCCESS
isMember: False
makeMember: INVALID_INPUT
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getExpenses: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
getPhone: 108
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
getPhone: 159
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=14, hight=112
getPhone: 2
getPhone: 158
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getPhone: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPhone: 5
getPhone: 102
getPhone: 5
putOnTop: FAILURE
isMember: False
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
putOnTop: FAILURE
isMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
isMember: DOESNT_EXISTS
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=14, hight=89
addCostumer: SUCCESS
getPhone: 2
getExpenses: -16
addPrize: SUCCESS
buyRecord: INVALID_INPUT
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: True
isMember: True
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: 162
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getExpenses: 0
putOnTop: FAILURE
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 18
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
isMember: False
isMember: False
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=3, hight=91
getExpenses: DOESNT_EXISTS
getPhone: 244
isMember: False
buyRecord: SUCCESS
isMember: False
getPhone: INVALID_INPUT
isMember: DOESNT_EXISTS
getPhone: 17
getPhone: 0
buyRecord: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
getExpenses: -29
isMember: INVALID_INPUT
isMember: True
getPhone: 120
makeMember: DOESNT_EXISTS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 180
getPhone: 193
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 120
getPhone: 193
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
getPlace: column=3, hight=52
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
getPhone: 57
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 250
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 120
isMember: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
getPlace: DOESNT_EXISTS
isMember: True
getPhone: 193
getPhone: 250
getPlace: column=3, hight=102
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 162
putOnTop: FAILURE
makeMember: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
getPhone: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
isMember: False
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
getPhone: 145
buyRecord: SUCCESS
getPhone: INVALID_INPUT
getExpenses: 54
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: True
getPhone: 158
isMember: True
putOnTop: FAILURE
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
addCostumer: ALREADY_EXISTS
isMember: DOESNT_EXISTS
getPlace: INVALID_INPUT
getPhone: 244
getPlace: column=3, hight=116
getPhone: 135
addPrize: INVALID_INPUT
buyRecord: INVALID_INPUT
addPrize: SUCCESS
putOnTop: FAILURE
isMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: INVALID_INPUT
makeMember: SUCCESS
addPrize: SUCCESS
getPhone: 102
getPhone: 145
isMember: True
buyRecord: SUCCESS
getPhone: 18
isMember: False
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
getExpenses: -245
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
getPhone: 25
addCostumer: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
getPlace: column=3, hight=128
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: 51
getPlace: column=3, hight=52
putOnTop: FAILURE
getPlace: column=3, hight=108
buyRecord: SUCCESS
isMember: True
addCostumer: SUCCESS
getExpenses: 102
addCostumer: SUCCESS
isMember: False
addPrize: SUCCESS
isMember: False
getExpenses: 6
getPhone: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 175
makeMember: SUCCESS
putOnTop: INVALID_INPUT
isMember: False
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: INVALID_INPUT
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: INVALID_INPUT
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
isMember: False
makeMember: ALREADY_EXISTS
getPhone: 46
getPlace: column=3, hight=96
addPrize: INVALID_INPUT
getPlace: column=3, hight=108
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
isMember: False
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
getPhone: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=3, hight=37
makeMember: SUCCESS
putOnTop: FAILURE
isMember: False
getPhone: 2
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
isMember: True
buyRecord: SUCCESS
getPlace: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 192
getPlace: column=3, hight=128
putOnTop: FAILURE
makeMember: SUCCESS
getPhone: 183
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 209
getPlace: column=3, hight=91
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=3, hight=70
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: 102
getPhone: 184
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=3, hight=23
getPhone: 118
isMember: True
getPlace: column=3, hight=85
getPhone: 162
addPrize: INVALID_INPUT
getPhone: 133
isMember: True
buyRecord: SUCCESS
getPhone: 218
addCostumer: ALREADY_EXISTS
getPhone: INVALID_INPUT
getPlace: column=3, hight=131
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=3, hight=128
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: INVALID_INPUT
isMember: True
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: 47
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: INVALID_INPUT
getPlace: column=3, hight=102
getPlace: column=3, hight=91
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getPlace: column=3, hight=0
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 175
isMember: True
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
makeMember: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
addCostumer: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
isMember: INVALID_INPUT
makeMember: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPhone: 175
getExpenses: 94
getPlace: column=3, hight=19
getPlace: column=3, hight=23
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 180
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: 184
isMember: True
putOnTop: FAILURE
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: INVALID_INPUT
makeMember: INVALID_INPUT
makeMember: SUCCESS
buyRecord: SUCCESS
getExpenses: -474
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: True
makeMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
isMember: True
getExpenses: -458
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=3, hight=128
putOnTop: FAILURE
addCostumer: SUCCESS
makeMember: SUCCESS
getPlace: column=3, hight=70
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=3, hight=108
makeMember: SUCCESS
getExpenses: -65
getPlace: column=3, hight=52
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: True
putOnTop: INVALID_INPUT
buyRecord: INVALID_INPUT
getPhone: 218
addCostumer: ALREADY_EXISTS
getPhone: 193
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
isMember: True
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
getExpenses: -94
addCostumer: ALREADY_EXISTS
getPhone: 56
getPhone: 5
addCostumer: ALREADY_EXISTS
getExpenses: INVALID_INPUT
putOnTop: FAILURE
putOnTop: INVALID_INPUT
putOnTop: FAILURE
putOnTop: FAILURE
addCostumer: SUCCESS
getPlace: column=3, hight=0
addCostumer: SUCCESS
isMember: False
makeMember: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 56
getPlace: column=3, hight=0
addPrize: SUCCESS
addPrize: INVALID_INPUT
putOnTop: FAILURE
makeMember: INVALID_INPUT
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: True
getExpenses: -217
getExpenses: 57
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=3, hight=0
isMember: True
getPlace: column=3, hight=116
isMember: False
getPlace: column=3, hight=70
getPhone: 102
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: 0
addPrize: INVALID_INPUT
getExpenses: -189
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPlace: column=3, hight=70
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
getPlace: column=3, hight=19
isMember: True
getPhone: 228
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
makeMember: INVALID_INPUT
makeMember: SUCCESS
getExpenses: -372
makeMember: SUCCESS
makeMember: SUCCESS
getPhone: 146
buyRecord: INVALID_INPUT
getPhone: 97
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: 57
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
getPlace: column=3, hight=128
getPhone: 149
getPlace: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: -1080
getPlace: column=3, hight=23
getPlace: column=3, hight=0
putOnTop: DOESNT_EXISTS
buyRecord: INVALID_INPUT
isMember: True
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
isMember: True
getPhone: 4
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
getPlace: column=3, hight=85
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 146
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: column=3, hight=52
getPlace: column=3, hight=0
putOnTop: DOESNT_EXISTS
getPhone: 180
addPrize: SUCCESS
addPrize: SUCCESS
isMember: DOESNT_EXISTS
getPhone: 62
buyRecord: SUCCESS
isMember: True
isMember: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 193
getPhone: 18
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
getExpenses: -491
getPhone: 0
getExpenses: DOESNT_EXISTS
isMember: False
getPhone: 51
isMember: True
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=3, hight=128
putOnTop: FAILURE
addCostumer: SUCCESS
getExpenses: -159
isMember: False
putOnTop: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
getPhone: 247
getPhone: 136
getExpenses: DOESNT_EXISTS
getExpenses: -50
makeMember: INVALID_INPUT
putOnTop: FAILURE
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: True
putOnTop: FAILURE
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 113
isMember: True
isMember: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: INVALID_INPUT
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=3, hight=70
addPrize: INVALID_INPUT
getPhone: 16
getExpenses: DOESNT_EXISTS
getExpenses: 0
addPrize: SUCCESS
isMember: False
makeMember: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
makeMember: INVALID_INPUT
getPhone: 242
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=3, hight=96
getPhone: 162
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
getExpenses: -720
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 118
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 25
putOnTop: FAILURE
addPrize: INVALID_INPUT
putOnTop: FAILURE
getPhone: 49
addPrize: INVALID_INPUT
getPhone: DOESNT_EXISTS
getPlace: column=3, hight=110
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
getPlace: column=3, hight=128
getExpenses: DOESNT_EXISTS
