newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: column=18, hight=0
getPlace: column=6, hight=0
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
getPhone: 64
addPrize: INVALID_INPUT
getPlace: column=17, hight=0
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: 237
getPhone: 91
getPlace: column=4, hight=0
isMember: DOESNT_EXISTS
getPhone: 201
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=7
addCostumer: SUCCESS
addCostumer: SUCCESS
newMonth: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 64
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=8, hight=0
getExpenses: INVALID_INPUT
getPlace: column=2, hight=0
getExpenses: DOESNT_EXISTS
getPhone: 199
addPrize: SUCCESS
putOnTop: SUCCESS
getPhone: 199
getExpenses: 0
getPlace: column=0, hight=0
buyRecord: DOESNT_EXISTS
getPhone: 100
getPhone: 237
makeMember: SUCCESS
putOnTop: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=12, hight=0
putOnTop: SUCCESS
getPlace: column=12, hight=0
isMember: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 129
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
getExpenses: INVALID_INPUT
putOnTop: SUCCESS
makeMember: SUCCESS
isMember: True
makeMember: SUCCESS
buyRecord: SUCCESS
getPhone: 129
addPrize: INVALID_INPUT
getPlace: column=2, hight=9
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: INVALID_INPUT
isMember: False
getPhone: 129
putOnTop: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: column=6, hight=0
getExpenses: 0
getExpenses: -13
getExpenses: -21
putOnTop: SUCCESS
isMember: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 82
getPhone: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 201
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
getPhone: 199
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: -16
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=8, hight=0
makeMember: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=18, hight=17
isMember: False
buyRecord: SUCCESS
getPhone: 129
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: 33
addPrize: INVALID_INPUT
getPlace: column=1, hight=0
getPhone: 18
getPlace: column=2, hight=9
buyRecord: SUCCESS
getPhone: 64
addCostumer: SUCCESS
getPhone: 246
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
isMember: True
putOnTop: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: INVALID_INPUT
getPhone: 100
getPhone: INVALID_INPUT
putOnTop: FAILURE
makeMember: SUCCESS
getPlace: column=7, hight=0
buyRecord: SUCCESS
getPhone: 64
getPhone: 82
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
isMember: False
addCostumer: SUCCESS
getExpenses: 157
getExpenses: -15
addCostumer: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
getPlace: column=12, hight=65
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getExpenses: 0
getExpenses: 161
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: False
getExpenses: INVALID_INPUT
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: True
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
buyRecord: SUCCESS
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
buyRecord: INVALID_INPUT
makeMember: SUCCESS
makeMember: SUCCESS
makeMember: DOESNT_EXISTS
isMember: True
makeMember: DOESNT_EXISTS
makeMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
isMember: True
addPrize: SUCCESS
getExpenses: -87
makeMember: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
getExpenses: -18
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getExpenses: 0
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=7, hight=2
getPhone: 249
addCostumer: SUCCESS
isMember: True
addPrize: SUCCESS
getPhone: 129
makeMember: SUCCESS
isMember: False
addCostumer: SUCCESS
getPhone: 100
putOnTop: FAILURE
addPrize: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
getPhone: 129
addCostumer: INVALID_INPUT
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 201
buyRecord: SUCCESS
getPlace: column=18, hight=45
makeMember: ALREADY_EXISTS
getPlace: column=18, hight=18
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 144
makeMember: SUCCESS
addCostumer: SUCCESS
getPhone: 82
addPrize: INVALID_INPUT
getPlace: column=1, hight=7
addPrize: SUCCESS
putOnTop: SUCCESS
isMember: False
makeMember: DOESNT_EXISTS
getPlace: column=18, hight=59
getPlace: column=18, hight=83
putOnTop: FAILURE
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: -87
isMember: False
buyRecord: DOESNT_EXISTS
getPhone: 39
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=18, hight=101
getExpenses: 61
putOnTop: FAILURE
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: 199
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: column=7, hight=151
addCostumer: SUCCESS
getExpenses: -52
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 86
addCostumer: SUCCESS
getExpenses: 106
getPlace: column=7, hight=97
isMember: False
isMember: False
addCostumer: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 91
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: True
isMember: False
putOnTop: FAILURE
buyRecord: SUCCESS
getExpenses: 133
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=7, hight=97
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
isMember: True
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: True
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=7, hight=133
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: 102
getExpenses: DOESNT_EXISTS
isMember: True
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
isMember: False
getExpenses: -64
getPhone: 82
addPrize: SUCCESS
getPhone: 2
getPhone: DOESNT_EXISTS
getExpenses: -173
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getPhone: 249
isMember: False
getPlace: column=7, hight=57
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=7, hight=80
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
getExpenses: -334
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 213
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPhone: INVALID_INPUT
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=7, hight=80
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
isMember: DOESNT_EXISTS
getPlace: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: column=7, hight=167
putOnTop: DOESNT_EXISTS
isMember: False
buyRecord: DOESNT_EXISTS
makeMember: INVALID_INPUT
getPhone: 103
addPrize: SUCCESS
makeMember: INVALID_INPUT
getPhone: 214
getExpenses: -280
isMember: False
putOnTop: FAILURE
makeMember: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
getPlace: column=7, hight=177
getExpenses: INVALID_INPUT
isMember: DOESNT_EXISTS
putOnTop: FAILURE
isMember: True
putOnTop: FAILURE
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=7, hight=6
addPrize: INVALID_INPUT
isMember: True
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 145
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=167
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPhone: 244
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
isMember: INVALID_INPUT
getExpenses: -432
addCostumer: SUCCESS
getPhone: 238
makeMember: SUCCESS
getPhone: INVALID_INPUT
getPlace: DOESNT_EXISTS
makeMember: INVALID_INPUT
getPlace: column=7, hight=0
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: INVALID_INPUT
getExpenses: -76
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=38
addCostumer: ALREADY_EXISTS
getPhone: 100
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: INVALID_INPUT
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
isMember: INVALID_INPUT
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: True
getPlace: column=7, hight=0
isMember: False
buyRecord: SUCCESS
addCostumer: SUCCESS
isMember: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 13
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
makeMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: True
putOnTop: FAILURE
makeMember: SUCCESS
addCostumer: SUCCESS
getPhone: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
getPlace: column=7, hight=6
isMember: False
getPhone: INVALID_INPUT
getPlace: column=7, hight=80
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: 33
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPhone: 194
makeMember: SUCCESS
getPhone: 210
getPhone: 129
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: -413
getPlace: column=7, hight=122
putOnTop: FAILURE
makeMember: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: column=7, hight=57
getPhone: 82
putOnTop: FAILURE
getPlace: column=7, hight=133
addPrize: INVALID_INPUT
buyRecord: INVALID_INPUT
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: FAILURE
putOnTop: FAILURE
isMember: True
getPhone: 28
getExpenses: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 237
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
isMember: False
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPhone: 82
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: False
putOnTop: FAILURE
getPlace: column=7, hight=2
addCostumer: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 244
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
isMember: INVALID_INPUT
getExpenses: -719
getExpenses: -356
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: False
getPlace: column=7, hight=80
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=7, hight=6
putOnTop: FAILURE
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
isMember: True
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: -488
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: INVALID_INPUT
getPlace: DOESNT_EXISTS
buyRecord: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: 156
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
getExpenses: -592
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -648
getPhone: 129
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
isMember: False
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
getPlace: column=7, hight=137
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
makeMember: INVALID_INPUT
getPlace: column=7, hight=21
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 38
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
getExpenses: -116
getExpenses: -583
addPrize: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
isMember: True
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: column=7, hight=21
isMember: False
putOnTop: INVALID_INPUT
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: False
addPrize: INVALID_INPUT
makeMember: SUCCESS
addPrize: SUCCESS
isMember: False
getPlace: INVALID_INPUT
getPlace: INVALID_INPUT
getPhone: 116
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPhone: 160
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: True
makeMember: SUCCESS
putOnTop: FAILURE
isMember: True
putOnTop: FAILURE
getPlace: column=7, hight=2
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 176
makeMember: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
getExpenses: -676
isMember: True
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: column=7, hight=151
getPlace: column=7, hight=167
makeMember: SUCCESS
isMember: INVALID_INPUT
isMember: False
getPhone: 239
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 91
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
isMember: DOESNT_EXISTS
getExpenses: -730
buyRecord: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPhone: 82
isMember: True
getPlace: column=7, hight=6
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: FAILURE
getPlace: column=7, hight=151
makeMember: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getPlace: column=7, hight=66
isMember: True
addPrize: SUCCESS
getPhone: 46
makeMember: ALREADY_EXISTS
getExpenses: -527
getPhone: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: INVALID_INPUT
putOnTop: INVALID_INPUT
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
getPlace: column=7, hight=151
putOnTop: FAILURE
getExpenses: -668
addCostumer: ALREADY_EXISTS
getExpenses: -442
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
getPlace: column=7, hight=0
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
buyRecord: SUCCESS
putOnTop: FAILURE
getExpenses: -176
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=6
getExpenses: -144
isMember: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=7, hight=21
isMember: DOESNT_EXISTS
getPhone: 145
getExpenses: DOESNT_EXISTS
getExpenses: -148
getPlace: column=7, hight=167
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
addCostumer: INVALID_INPUT
getPhone: 82
getPlace: column=7, hight=97
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=7, hight=174
putOnTop: DOESNT_EXISTS
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: True
getPlace: column=7, hight=57
addPrize: SUCCESS
isMember: False
getPhone: 64
makeMember: INVALID_INPUT
getPhone: 29
getPlace: column=7, hight=177
makeMember: SUCCESS
getPhone: 117
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: 187
getPhone: 42
makeMember: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=7, hight=57
putOnTop: FAILURE
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 187
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 144
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=38
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=7, hight=66
getPlace: DOESNT_EXISTS
getPhone: 162
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: INVALID_INPUT
getPhone: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getPlace: column=7, hight=38
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=7, hight=0
isMember: False
addCostumer: INVALID_INPUT
getPlace: column=7, hight=21
addCostumer: SUCCESS
getPhone: 239
getExpenses: -154
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getExpenses: -1070
makeMember: ALREADY_EXISTS
isMember: False
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: True
addCostumer: INVALID_INPUT
getPhone: 106
putOnTop: FAILURE
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPhone: 83
isMember: INVALID_INPUT
getExpenses: -857
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: 21
isMember: False
isMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
isMember: False
