newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=8, hight=0
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: INVALID_INPUT
getPhone: 88
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
makeMember: INVALID_INPUT
getPlace: INVALID_INPUT
getPhone: 116
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: False
buyRecord: SUCCESS
isMember: False
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 42
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=4, hight=0
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=13, hight=0
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: True
getPlace: column=16, hight=0
getExpenses: DOESNT_EXISTS
getPhone: 205
getPlace: column=17, hight=0
getPhone: 42
isMember: False
addCostumer: SUCCESS
getExpenses: 0
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=17, hight=0
getPhone: INVALID_INPUT
getPhone: 88
getPlace: column=13, hight=0
putOnTop: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
isMember: True
getPlace: column=2, hight=0
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: INVALID_INPUT
addPrize: SUCCESS
putOnTop: SUCCESS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: SUCCESS
getPhone: 199
getPlace: column=8, hight=20
addPrize: INVALID_INPUT
getPlace: column=16, hight=0
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
getExpenses: 0
isMember: True
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 137
getExpenses: DOESNT_EXISTS
getPlace: column=15, hight=0
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 147
getPhone: 147
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
putOnTop: SUCCESS
isMember: INVALID_INPUT
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 205
getPlace: DOESNT_EXISTS
getPhone: 101
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 199
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
getPhone: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 158
isMember: False
addPrize: INVALID_INPUT
getPhone: 147
getPhone: 229
getExpenses: INVALID_INPUT
addCostumer: INVALID_INPUT
getPlace: column=5, hight=0
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: 199
makeMember: ALREADY_EXISTS
getPhone: 147
putOnTop: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
isMember: False
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=7, hight=0
getPlace: column=2, hight=7
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: -176
getPhone: 42
isMember: DOESNT_EXISTS
isMember: False
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -95
putOnTop: SUCCESS
buyRecord: SUCCESS
getPlace: column=13, hight=0
isMember: False
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
isMember: INVALID_INPUT
getPhone: 227
makeMember: ALREADY_EXISTS
getExpenses: -189
isMember: False
getPhone: 152
getPlace: column=1, hight=0
getPhone: 225
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
isMember: False
getPhone: 3
isMember: False
getPhone: 101
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
buyRecord: INVALID_INPUT
getPlace: column=2, hight=34
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: INVALID_INPUT
addPrize: SUCCESS
putOnTop: SUCCESS
isMember: INVALID_INPUT
getPlace: column=1, hight=0
getPhone: 147
addPrize: INVALID_INPUT
getPlace: column=1, hight=2
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: -167
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
getPlace: column=16, hight=35
getPhone: 137
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 11
getExpenses: -274
addPrize: INVALID_INPUT
makeMember: DOESNT_EXISTS
getPhone: 143
isMember: True
addCostumer: SUCCESS
getPhone: 101
getPlace: column=2, hight=15
addCostumer: SUCCESS
isMember: False
makeMember: DOESNT_EXISTS
isMember: True
getPhone: INVALID_INPUT
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 229
getPhone: 182
addPrize: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
getPhone: 23
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
putOnTop: SUCCESS
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 192
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: column=1, hight=76
isMember: True
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 11
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=19, hight=0
getPlace: INVALID_INPUT
putOnTop: FAILURE
putOnTop: INVALID_INPUT
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: True
addPrize: INVALID_INPUT
isMember: False
putOnTop: SUCCESS
isMember: False
getPhone: 143
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: -193
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: False
putOnTop: SUCCESS
makeMember: SUCCESS
getPhone: 227
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: True
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getExpenses: -324
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
makeMember: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: INVALID_INPUT
addCostumer: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
isMember: False
getPhone: INVALID_INPUT
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -324
isMember: True
putOnTop: SUCCESS
getPhone: 191
getPlace: column=5, hight=121
putOnTop: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=19, hight=0
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
getExpenses: -203
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 42
getPhone: 104
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 88
buyRecord: SUCCESS
isMember: True
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: column=15, hight=131
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
putOnTop: FAILURE
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: False
addCostumer: SUCCESS
getPlace: column=15, hight=80
isMember: False
buyRecord: SUCCESS
getPlace: column=15, hight=102
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: -14
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
isMember: True
getPlace: INVALID_INPUT
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPhone: 116
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
isMember: True
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
isMember: True
getPhone: 24
getPhone: 24
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 3
isMember: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 147
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
getExpenses: -100
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: False
makeMember: SUCCESS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
getPlace: column=19, hight=183
putOnTop: INVALID_INPUT
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
getPhone: 43
buyRecord: SUCCESS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: column=19, hight=128
getPhone: 11
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: -414
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
isMember: True
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=19, hight=88
makeMember: SUCCESS
isMember: True
getPlace: column=19, hight=42
getPhone: INVALID_INPUT
getPlace: column=19, hight=4
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 24
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 147
addCostumer: INVALID_INPUT
getPhone: 183
getPhone: INVALID_INPUT
getExpenses: INVALID_INPUT
getPhone: 24
getPhone: 82
addPrize: INVALID_INPUT
isMember: True
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=19, hight=32
getExpenses: DOESNT_EXISTS
getPlace: column=19, hight=135
getPhone: 185
isMember: False
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=19, hight=162
isMember: False
isMember: False
putOnTop: FAILURE
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: FAILURE
isMember: False
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: 96
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: 158
isMember: False
addPrize: INVALID_INPUT
getPhone: 208
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 183
getPlace: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
getPhone: 46
getExpenses: DOESNT_EXISTS
isMember: INVALID_INPUT
getPlace: column=19, hight=42
getPlace: column=19, hight=6
buyRecord: SUCCESS
getPhone: 65
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getPlace: column=19, hight=6
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
getPhone: 43
makeMember: SUCCESS
getPlace: column=19, hight=135
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getPhone: 75
getPhone: 57
buyRecord: SUCCESS
addPrize: SUCCESS
getPlace: column=7, hight=0
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 21
isMember: True
putOnTop: FAILURE
isMember: False
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=19, hight=162
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
addCostumer: ALREADY_EXISTS
getPlace: column=7, hight=0
getPhone: DOESNT_EXISTS
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 96
getPhone: 227
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: INVALID_INPUT
putOnTop: FAILURE
addPrize: SUCCESS
getPlace: column=19, hight=84
getPlace: column=19, hight=22
buyRecord: INVALID_INPUT
makeMember: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
getPlace: column=7, hight=152
buyRecord: SUCCESS
getPlace: column=7, hight=150
addCostumer: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
putOnTop: FAILURE
putOnTop: FAILURE
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
getPlace: column=7, hight=13
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 155
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=15
makeMember: DOESNT_EXISTS
isMember: True
putOnTop: FAILURE
getPlace: column=7, hight=79
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getPlace: column=7, hight=144
addPrize: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: FAILURE
getPlace: column=7, hight=79
getPlace: column=7, hight=97
addCostumer: SUCCESS
getPlace: column=7, hight=41
putOnTop: FAILURE
getExpenses: INVALID_INPUT
getExpenses: -453
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getExpenses: -573
getPlace: column=7, hight=192
getPhone: INVALID_INPUT
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
putOnTop: INVALID_INPUT
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: column=7, hight=0
getPlace: column=7, hight=31
makeMember: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
getPhone: 183
putOnTop: FAILURE
putOnTop: FAILURE
buyRecord: INVALID_INPUT
getExpenses: -543
putOnTop: FAILURE
makeMember: SUCCESS
getPhone: 183
addCostumer: SUCCESS
isMember: True
isMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
isMember: True
getExpenses: -632
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: False
getPhone: 46
buyRecord: SUCCESS
getPhone: 206
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -44
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
addPrize: SUCCESS
isMember: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: -356
putOnTop: INVALID_INPUT
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
makeMember: DOESNT_EXISTS
isMember: False
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 63
isMember: False
isMember: False
makeMember: SUCCESS
makeMember: INVALID_INPUT
getPhone: 143
addCostumer: SUCCESS
getPhone: 104
getPlace: column=7, hight=172
getPlace: column=7, hight=0
addPrize: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
getExpenses: INVALID_INPUT
getPlace: column=7, hight=144
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
isMember: False
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
isMember: False
getExpenses: 0
isMember: False
getPhone: INVALID_INPUT
makeMember: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
getPlace: column=7, hight=150
getExpenses: DOESNT_EXISTS
getPhone: 63
getPlace: column=7, hight=93
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=7, hight=9
isMember: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 152
getExpenses: -128
buyRecord: SUCCESS
getPhone: 164
getExpenses: DOESNT_EXISTS
isMember: False
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
makeMember: INVALID_INPUT
getPhone: 208
isMember: True
isMember: True
getPlace: DOESNT_EXISTS
getPhone: 185
isMember: True
getPhone: 177
getPlace: column=7, hight=192
getPhone: 82
addPrize: SUCCESS
getPhone: 121
putOnTop: DOESNT_EXISTS
getPhone: 114
getPhone: 158
makeMember: INVALID_INPUT
putOnTop: FAILURE
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: 205
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getPlace: column=7, hight=172
addCostumer: SUCCESS
getExpenses: -178
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
buyRecord: INVALID_INPUT
getPlace: column=7, hight=79
addPrize: SUCCESS
isMember: False
getPhone: 88
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -253
isMember: False
getPlace: column=7, hight=192
isMember: True
getPlace: column=7, hight=58
addCostumer: SUCCESS
isMember: False
buyRecord: SUCCESS
getPhone: 72
isMember: False
isMember: False
buyRecord: SUCCESS
getPhone: INVALID_INPUT
getExpenses: -789
addPrize: INVALID_INPUT
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: DOESNT_EXISTS
getPlace: column=7, hight=51
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: INVALID_INPUT
isMember: True
addPrize: INVALID_INPUT
getExpenses: -91
addPrize: INVALID_INPUT
getPhone: 185
putOnTop: FAILURE
addPrize: SUCCESS
isMember: True
getPlace: column=7, hight=152
getExpenses: -313
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 229
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=15
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=7, hight=144
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
getPlace: INVALID_INPUT
getPhone: 72
isMember: False
isMember: False
isMember: False
makeMember: ALREADY_EXISTS
getExpenses: -1130
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
getExpenses: -91
getExpenses: DOESNT_EXISTS
makeMember: INVALID_INPUT
putOnTop: FAILURE
getExpenses: -648
addCostumer: SUCCESS
isMember: False
getPlace: column=7, hight=172
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: column=7, hight=115
addCostumer: INVALID_INPUT
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
getPhone: 114
makeMember: ALREADY_EXISTS
getPhone: 51
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=115
getPhone: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
makeMember: SUCCESS
getPhone: 247
addCostumer: SUCCESS
getExpenses: -91
buyRecord: SUCCESS
putOnTop: FAILURE
isMember: False
putOnTop: FAILURE
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
isMember: True
isMember: False
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=7, hight=152
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=7, hight=150
getExpenses: -91
getPlace: column=7, hight=171
isMember: True
makeMember: ALREADY_EXISTS
isMember: False
putOnTop: FAILURE
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPhone: 138
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPhone: 227
getPhone: 82
getPlace: column=7, hight=144
isMember: True
addPrize: SUCCESS
getPlace: column=7, hight=9
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: -1137
addPrize: INVALID_INPUT
getExpenses: -1379
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: False
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
isMember: False
putOnTop: FAILURE
getPlace: column=7, hight=171
isMember: False
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
getPlace: column=7, hight=58
getPlace: column=7, hight=78
addPrize: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
makeMember: DOESNT_EXISTS
isMember: False
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
isMember: False
getPhone: 88
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPlace: column=7, hight=171
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: INVALID_INPUT
addPrize: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: column=7, hight=31
getPlace: column=7, hight=172
addCostumer: ALREADY_EXISTS
getPhone: 21
getPhone: 227
getPhone: 59
buyRecord: SUCCESS
isMember: False
getPhone: 42
addPrize: SUCCESS
isMember: True
getPhone: 177
addPrize: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=7, hight=15
