newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 152
addCostumer: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
getPhone: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
getPlace: column=1, hight=0
makeMember: SUCCESS
makeMember: SUCCESS
getPlace: column=3, hight=0
makeMember: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
makeMember: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=7, hight=0
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
getPhone: 43
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: INVALID_INPUT
putOnTop: SUCCESS
getExpenses: 0
isMember: False
makeMember: SUCCESS
isMember: INVALID_INPUT
addPrize: SUCCESS
getPhone: 102
getPhone: 53
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: False
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
isMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=0, hight=0
isMember: True
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: True
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
makeMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: column=6, hight=24
addPrize: SUCCESS
getPlace: INVALID_INPUT
makeMember: INVALID_INPUT
makeMember: DOESNT_EXISTS
getPhone: 109
addCostumer: SUCCESS
getPlace: column=6, hight=24
addPrize: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
putOnTop: SUCCESS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: SUCCESS
putOnTop: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: -4
addPrize: SUCCESS
getExpenses: 101
getPhone: 48
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 102
getExpenses: 0
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=0, hight=60
isMember: True
getPlace: DOESNT_EXISTS
getPhone: 109
getPlace: column=0, hight=36
getExpenses: 7
getPhone: INVALID_INPUT
makeMember: DOESNT_EXISTS
getPhone: 229
getPhone: 167
getPhone: 129
addPrize: SUCCESS
getExpenses: 7
isMember: True
getPlace: INVALID_INPUT
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
getPlace: column=0, hight=60
getPhone: 43
makeMember: DOESNT_EXISTS
getExpenses: INVALID_INPUT
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPhone: 229
getExpenses: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
makeMember: INVALID_INPUT
isMember: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 64
addCostumer: SUCCESS
getPlace: column=0, hight=74
getPhone: DOESNT_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 152
isMember: False
buyRecord: SUCCESS
getExpenses: -95
isMember: True
getPhone: DOESNT_EXISTS
getPhone: 229
isMember: False
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPhone: 129
getPlace: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
getExpenses: -95
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPhone: 213
isMember: INVALID_INPUT
getPhone: 73
makeMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: INVALID_INPUT
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
getPlace: column=0, hight=36
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -99
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: INVALID_INPUT
isMember: True
isMember: DOESNT_EXISTS
isMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addPrize: INVALID_INPUT
makeMember: INVALID_INPUT
getExpenses: -207
getPhone: 43
addCostumer: SUCCESS
getPhone: 68
isMember: False
addCostumer: SUCCESS
isMember: False
getPhone: 162
getPlace: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
getExpenses: -352
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: -399
getPlace: column=4, hight=69
getPhone: 68
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: False
addPrize: SUCCESS
getPlace: column=4, hight=0
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 229
putOnTop: FAILURE
getPhone: 87
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 56
getExpenses: INVALID_INPUT
getPhone: INVALID_INPUT
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPhone: 167
getPhone: 129
getPhone: 167
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=4, hight=69
getPlace: column=4, hight=26
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 199
getPhone: 166
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: INVALID_INPUT
makeMember: SUCCESS
addCostumer: INVALID_INPUT
putOnTop: FAILURE
makeMember: SUCCESS
getPhone: 166
getExpenses: INVALID_INPUT
addPrize: SUCCESS
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
getPlace: column=4, hight=70
getPlace: column=4, hight=0
buyRecord: SUCCESS
isMember: True
buyRecord: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 213
makeMember: SUCCESS
getPhone: 85
addCostumer: SUCCESS
getPhone: 43
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
getPhone: 3
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
addPrize: SUCCESS
isMember: False
makeMember: ALREADY_EXISTS
getPhone: 73
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: False
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
isMember: False
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: INVALID_INPUT
getExpenses: 0
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 56
isMember: False
getPlace: column=4, hight=26
getPhone: 96
putOnTop: FAILURE
isMember: True
getExpenses: DOESNT_EXISTS
getExpenses: -90
getExpenses: -12
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: column=4, hight=0
getExpenses: -90
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: FAILURE
getExpenses: INVALID_INPUT
getExpenses: -329
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=4, hight=70
buyRecord: SUCCESS
getPlace: column=4, hight=10
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: False
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getPlace: column=4, hight=60
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=4, hight=26
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: column=4, hight=10
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
putOnTop: FAILURE
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: column=4, hight=60
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: INVALID_INPUT
makeMember: SUCCESS
putOnTop: FAILURE
isMember: False
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
newMonth: SUCCESS
getPhone: 53
addPrize: SUCCESS
putOnTop: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
getPlace: column=6, hight=0
getPhone: 100
makeMember: ALREADY_EXISTS
isMember: False
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 185
addPrize: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=17, hight=0
getExpenses: DOESNT_EXISTS
getPlace: column=5, hight=0
getPlace: column=25, hight=0
addCostumer: SUCCESS
getPlace: column=2, hight=0
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 87
getExpenses: DOESNT_EXISTS
getPlace: column=27, hight=0
getPhone: DOESNT_EXISTS
getPhone: 73
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
getPlace: column=12, hight=0
putOnTop: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=3, hight=0
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
putOnTop: SUCCESS
getExpenses: 0
getPhone: 32
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: -124
isMember: False
addCostumer: SUCCESS
getPhone: 199
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: -124
isMember: False
makeMember: INVALID_INPUT
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=17, hight=0
getPhone: 162
isMember: False
addPrize: INVALID_INPUT
putOnTop: SUCCESS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
makeMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 25
getExpenses: INVALID_INPUT
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=11, hight=0
getPhone: INVALID_INPUT
putOnTop: SUCCESS
getPhone: 53
addCostumer: SUCCESS
getExpenses: -127
getExpenses: DOESNT_EXISTS
getPlace: column=5, hight=13
putOnTop: SUCCESS
isMember: True
addCostumer: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 187
getExpenses: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
isMember: True
isMember: False
makeMember: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: True
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: False
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=20, hight=9
buyRecord: INVALID_INPUT
makeMember: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
getPlace: column=20, hight=0
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: 126
makeMember: SUCCESS
addCostumer: SUCCESS
isMember: True
isMember: False
getPhone: INVALID_INPUT
getPlace: column=16, hight=0
getPlace: column=6, hight=0
addPrize: SUCCESS
putOnTop: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
getPlace: column=21, hight=34
getPhone: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getPlace: column=20, hight=0
putOnTop: FAILURE
getExpenses: 0
addCostumer: SUCCESS
getExpenses: -322
isMember: True
addPrize: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=3, hight=9
buyRecord: SUCCESS
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
isMember: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: INVALID_INPUT
getPlace: column=6, hight=0
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -47
getPlace: DOESNT_EXISTS
getExpenses: -245
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=11, hight=0
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
makeMember: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: -436
addPrize: INVALID_INPUT
isMember: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 182
isMember: True
isMember: True
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: SUCCESS
getPhone: 77
getPhone: 73
getExpenses: DOESNT_EXISTS
getPlace: column=25, hight=0
buyRecord: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
getPhone: 3
isMember: False
addCostumer: INVALID_INPUT
addPrize: SUCCESS
getPhone: 217
isMember: False
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: -521
getPhone: 232
buyRecord: INVALID_INPUT
getPlace: column=4, hight=0
getPhone: 162
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPlace: column=6, hight=0
makeMember: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: column=21, hight=25
makeMember: SUCCESS
addCostumer: SUCCESS
isMember: False
addPrize: SUCCESS
getPhone: 43
getPlace: INVALID_INPUT
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 56
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: SUCCESS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 111
getPlace: column=19, hight=48
getExpenses: INVALID_INPUT
isMember: False
isMember: False
isMember: True
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=19, hight=3
isMember: False
isMember: False
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 43
buyRecord: INVALID_INPUT
putOnTop: SUCCESS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
isMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: INVALID_INPUT
makeMember: SUCCESS
getPlace: column=8, hight=21
addCostumer: SUCCESS
isMember: False
getExpenses: 0
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: 47
getExpenses: -96
getPlace: column=2, hight=0
isMember: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 77
putOnTop: FAILURE
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: False
putOnTop: INVALID_INPUT
buyRecord: INVALID_INPUT
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: 47
isMember: True
addCostumer: ALREADY_EXISTS
getPlace: column=26, hight=146
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
getExpenses: 0
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: False
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
isMember: False
makeMember: ALREADY_EXISTS
isMember: False
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
makeMember: INVALID_INPUT
makeMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: INVALID_INPUT
isMember: True
isMember: False
putOnTop: DOESNT_EXISTS
getPlace: column=26, hight=146
addPrize: INVALID_INPUT
isMember: True
getPhone: 130
makeMember: SUCCESS
addPrize: SUCCESS
getPlace: column=26, hight=54
getPhone: 64
makeMember: DOESNT_EXISTS
getExpenses: -704
getPlace: column=26, hight=24
addCostumer: ALREADY_EXISTS
getPhone: 53
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: INVALID_INPUT
putOnTop: FAILURE
getExpenses: -8
makeMember: SUCCESS
getPlace: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 130
isMember: DOESNT_EXISTS
getPlace: column=26, hight=155
getPhone: 85
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
isMember: True
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: 127
putOnTop: SUCCESS
buyRecord: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
buyRecord: SUCCESS
putOnTop: FAILURE
getExpenses: -920
getPlace: column=2, hight=0
buyRecord: SUCCESS
isMember: True
getPhone: INVALID_INPUT
getPhone: 99
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: -467
getPhone: 129
isMember: True
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=2, hight=136
getPlace: column=2, hight=53
getExpenses: -446
buyRecord: INVALID_INPUT
makeMember: INVALID_INPUT
getPhone: 100
getPhone: 232
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=2, hight=225
addCostumer: ALREADY_EXISTS
isMember: DOESNT_EXISTS
getPlace: column=2, hight=40
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=2, hight=136
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
putOnTop: FAILURE
isMember: True
getPlace: column=2, hight=90
putOnTop: FAILURE
buyRecord: SUCCESS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 133
buyRecord: INVALID_INPUT
getPhone: 53
getPlace: column=2, hight=101
isMember: True
getExpenses: -106
putOnTop: FAILURE
getPhone: INVALID_INPUT
getPhone: 161
getPhone: 73
getPlace: column=2, hight=123
isMember: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
getPhone: 56
isMember: False
putOnTop: FAILURE
getPlace: column=2, hight=102
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
getPhone: 41
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
getPhone: 100
getPhone: 136
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
getPhone: 74
getPhone: 3
getPlace: column=2, hight=123
getPlace: column=2, hight=123
putOnTop: INVALID_INPUT
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: 59
makeMember: SUCCESS
addPrize: SUCCESS
isMember: False
makeMember: SUCCESS
getPhone: 249
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
addPrize: SUCCESS
makeMember: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=2, hight=12
isMember: INVALID_INPUT
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPlace: column=2, hight=42
getPhone: 1
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=2, hight=123
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
