newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
addPrize: SUCCESS
makeMember: SUCCESS
getExpenses: 0
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 146
makeMember: SUCCESS
getPhone: 118
getPhone: 50
getPhone: 50
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=23, hight=0
getExpenses: 0
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
getPhone: 118
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
isMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
isMember: INVALID_INPUT
getExpenses: 0
getExpenses: 0
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getPhone: 118
makeMember: DOESNT_EXISTS
getExpenses: 185
isMember: INVALID_INPUT
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
getPhone: 146
makeMember: DOESNT_EXISTS
getPhone: 118
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
putOnTop: SUCCESS
getPhone: 50
getExpenses: -109
getExpenses: DOESNT_EXISTS
isMember: False
makeMember: SUCCESS
getPlace: column=5, hight=0
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: INVALID_INPUT
getPlace: column=29, hight=0
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: column=2, hight=9
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: 0
getPhone: 118
addCostumer: SUCCESS
isMember: True
putOnTop: DOESNT_EXISTS
isMember: False
getExpenses: 0
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
getPhone: 118
addPrize: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
buyRecord: SUCCESS
isMember: INVALID_INPUT
addCostumer: SUCCESS
