newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: INVALID_INPUT
isMember: False
isMember: False
putOnTop: SUCCESS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=12, hight=0
getPhone: 104
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
isMember: False
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 8
putOnTop: DOESNT_EXISTS
getPhone: 212
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
getPlace: column=5, hight=0
makeMember: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
getPlace: column=4, hight=0
getPlace: column=5, hight=0
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 166
putOnTop: SUCCESS
putOnTop: FAILURE
getPhone: 237
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
addPrize: SUCCESS
getPlace: INVALID_INPUT
addPrize: SUCCESS
putOnTop: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
getPlace: column=7, hight=23
getPhone: 214
putOnTop: SUCCESS
isMember: True
addPrize: SUCCESS
getPhone: 21
putOnTop: INVALID_INPUT
getPlace: column=5, hight=6
getPlace: column=11, hight=8
getExpenses: 0
isMember: False
addPrize: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: 101
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=5, hight=0
makeMember: SUCCESS
addPrize: SUCCESS
makeMember: INVALID_INPUT
getPlace: column=5, hight=0
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
getPhone: 237
isMember: True
isMember: True
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: 21
addCostumer: SUCCESS
getExpenses: 201
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: column=5, hight=6
buyRecord: SUCCESS
getExpenses: 201
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getPhone: 166
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: 0
putOnTop: INVALID_INPUT
getExpenses: 0
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPlace: column=11, hight=31
isMember: False
getExpenses: 0
isMember: False
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: 201
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=5, hight=0
getExpenses: 0
putOnTop: SUCCESS
putOnTop: SUCCESS
isMember: False
makeMember: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 44
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
getPlace: column=11, hight=8
getPhone: 173
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
putOnTop: INVALID_INPUT
getPlace: column=6, hight=0
putOnTop: FAILURE
getPlace: INVALID_INPUT
getPhone: 212
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 82
getPlace: column=0, hight=29
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: SUCCESS
getPhone: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=0, hight=12
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: 102
makeMember: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: column=0, hight=35
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
addPrize: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: 0
getPlace: INVALID_INPUT
addPrize: SUCCESS
getPhone: 44
addCostumer: SUCCESS
getPhone: 212
addPrize: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
getExpenses: 165
getExpenses: INVALID_INPUT
getPhone: INVALID_INPUT
getPhone: INVALID_INPUT
getPlace: column=0, hight=111
addPrize: SUCCESS
isMember: True
addCostumer: ALREADY_EXISTS
getExpenses: -148
putOnTop: FAILURE
makeMember: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
getPhone: 237
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=6, hight=4
addPrize: SUCCESS
getPhone: 212
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
getPhone: 81
addPrize: INVALID_INPUT
getPhone: 45
getPhone: 44
makeMember: DOESNT_EXISTS
getExpenses: INVALID_INPUT
addCostumer: INVALID_INPUT
getPhone: 212
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: False
isMember: False
isMember: True
makeMember: DOESNT_EXISTS
isMember: False
getPlace: column=6, hight=0
buyRecord: SUCCESS
getPhone: 25
makeMember: INVALID_INPUT
getPlace: column=6, hight=43
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
getPhone: 166
putOnTop: FAILURE
isMember: True
putOnTop: FAILURE
addCostumer: INVALID_INPUT
isMember: DOESNT_EXISTS
getPhone: 166
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
putOnTop: DOESNT_EXISTS
isMember: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
getPhone: 46
getPlace: column=6, hight=115
getPlace: column=6, hight=72
getExpenses: 0
addCostumer: SUCCESS
getPhone: 146
getPhone: 135
getPhone: INVALID_INPUT
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
isMember: False
putOnTop: DOESNT_EXISTS
getExpenses: 0
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPhone: 21
addPrize: SUCCESS
getPhone: 146
getPlace: column=6, hight=47
getPhone: 173
addPrize: SUCCESS
getExpenses: INVALID_INPUT
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: FAILURE
buyRecord: SUCCESS
isMember: True
putOnTop: FAILURE
isMember: False
addPrize: SUCCESS
getPlace: column=6, hight=115
isMember: False
putOnTop: FAILURE
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: False
getPhone: 45
addPrize: INVALID_INPUT
makeMember: SUCCESS
isMember: True
isMember: False
getPlace: column=6, hight=115
putOnTop: FAILURE
getPhone: 229
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=6, hight=33
putOnTop: FAILURE
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
getPlace: column=6, hight=33
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
getPhone: 25
getPhone: 104
makeMember: INVALID_INPUT
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
isMember: False
getPhone: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: INVALID_INPUT
getPlace: column=6, hight=126
buyRecord: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
getExpenses: -141
isMember: DOESNT_EXISTS
getPlace: column=6, hight=126
getExpenses: DOESNT_EXISTS
getExpenses: -141
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
getPhone: 104
getExpenses: -493
getPlace: column=6, hight=4
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
getPhone: 171
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: INVALID_INPUT
getPlace: column=6, hight=47
getPhone: 236
getExpenses: DOESNT_EXISTS
isMember: INVALID_INPUT
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 156
getExpenses: -317
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
getPhone: 135
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -309
putOnTop: DOESNT_EXISTS
getExpenses: -78
isMember: True
isMember: False
addPrize: SUCCESS
getPhone: 82
getPlace: column=6, hight=0
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: INVALID_INPUT
getPlace: column=6, hight=4
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: True
makeMember: SUCCESS
putOnTop: FAILURE
isMember: False
makeMember: ALREADY_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
buyRecord: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=6, hight=4
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: column=6, hight=78
getPlace: column=6, hight=115
getPlace: DOESNT_EXISTS
getExpenses: -433
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: True
getPhone: INVALID_INPUT
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
isMember: INVALID_INPUT
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: False
getPhone: 135
getExpenses: -42
getPlace: column=6, hight=0
isMember: INVALID_INPUT
getExpenses: -440
getExpenses: -600
getExpenses: 0
getPlace: column=6, hight=47
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
putOnTop: INVALID_INPUT
isMember: True
addCostumer: INVALID_INPUT
putOnTop: INVALID_INPUT
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 82
isMember: True
isMember: True
getExpenses: DOESNT_EXISTS
getPhone: 214
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPlace: column=6, hight=126
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: 16
getPhone: 136
isMember: False
getPhone: 44
isMember: False
addCostumer: ALREADY_EXISTS
buyRecord: INVALID_INPUT
getPlace: column=6, hight=47
isMember: True
getPlace: column=6, hight=115
buyRecord: SUCCESS
isMember: False
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: -131
getPlace: column=6, hight=78
getPlace: column=6, hight=55
putOnTop: FAILURE
makeMember: INVALID_INPUT
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
getExpenses: -392
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=6, hight=0
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 81
getPlace: column=6, hight=33
addPrize: INVALID_INPUT
getExpenses: -46
putOnTop: FAILURE
getPhone: 146
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 81
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=6, hight=55
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
isMember: True
getPhone: DOESNT_EXISTS
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: True
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 21
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=6, hight=78
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
getPhone: INVALID_INPUT
addPrize: SUCCESS
getExpenses: -359
buyRecord: SUCCESS
getExpenses: -57
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
getPhone: 107
makeMember: ALREADY_EXISTS
getPhone: 147
putOnTop: DOESNT_EXISTS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPlace: column=6, hight=43
getPhone: 154
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: INVALID_INPUT
addPrize: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 96
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: False
makeMember: ALREADY_EXISTS
getExpenses: -81
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: INVALID_INPUT
isMember: False
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=6, hight=126
getPlace: column=6, hight=16
isMember: True
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 248
getPlace: column=6, hight=115
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPhone: INVALID_INPUT
addCostumer: ALREADY_EXISTS
isMember: True
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
putOnTop: FAILURE
isMember: True
makeMember: DOESNT_EXISTS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=6, hight=4
getPhone: 75
getPlace: column=6, hight=16
getPlace: column=6, hight=33
makeMember: SUCCESS
addCostumer: SUCCESS
getPhone: 116
isMember: False
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: True
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: -29
getPlace: column=6, hight=4
getPhone: 102
getPlace: DOESNT_EXISTS
getPhone: 166
getPhone: 25
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 9
makeMember: ALREADY_EXISTS
isMember: False
isMember: True
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: False
getPlace: column=6, hight=16
isMember: False
getPhone: INVALID_INPUT
getPlace: column=6, hight=115
addPrize: INVALID_INPUT
getPhone: 58
buyRecord: INVALID_INPUT
getPhone: 212
addCostumer: ALREADY_EXISTS
getExpenses: -576
addPrize: SUCCESS
getPhone: 9
addPrize: SUCCESS
getExpenses: -246
getExpenses: -127
addCostumer: ALREADY_EXISTS
isMember: False
getPhone: 146
addCostumer: INVALID_INPUT
isMember: True
addPrize: SUCCESS
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=6, hight=115
buyRecord: INVALID_INPUT
getPhone: 210
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: INVALID_INPUT
addCostumer: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: column=6, hight=126
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: True
getExpenses: INVALID_INPUT
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
isMember: DOESNT_EXISTS
getExpenses: -425
addCostumer: SUCCESS
getPhone: 232
getPlace: column=6, hight=55
buyRecord: SUCCESS
getPhone: 147
getPhone: 198
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: -415
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: -259
isMember: False
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
getPhone: 107
addPrize: SUCCESS
getPhone: 84
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=6, hight=126
makeMember: SUCCESS
getPlace: column=6, hight=50
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=6, hight=16
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
getPhone: INVALID_INPUT
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
getPlace: column=6, hight=126
putOnTop: INVALID_INPUT
addPrize: SUCCESS
getPhone: 141
isMember: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: -367
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
getExpenses: INVALID_INPUT
makeMember: SUCCESS
makeMember: SUCCESS
getExpenses: -96
addCostumer: ALREADY_EXISTS
getPlace: column=6, hight=33
makeMember: ALREADY_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -73
getPhone: 175
addPrize: SUCCESS
getPlace: column=6, hight=0
addCostumer: SUCCESS
getPhone: 66
makeMember: SUCCESS
getPlace: column=6, hight=115
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
isMember: False
isMember: True
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: True
getPhone: INVALID_INPUT
getPhone: 171
getExpenses: -308
makeMember: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=6, hight=50
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
isMember: False
isMember: True
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
isMember: True
addCostumer: INVALID_INPUT
getPhone: 126
newMonth: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
isMember: True
addPrize: SUCCESS
getExpenses: 0
getPlace: column=4, hight=0
makeMember: ALREADY_EXISTS
getPlace: column=14, hight=0
buyRecord: INVALID_INPUT
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 235
isMember: True
buyRecord: SUCCESS
getExpenses: 0
getPhone: 75
addCostumer: ALREADY_EXISTS
putOnTop: SUCCESS
putOnTop: SUCCESS
getPlace: column=8, hight=0
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
makeMember: DOESNT_EXISTS
getPhone: 8
getExpenses: -39
addCostumer: SUCCESS
isMember: INVALID_INPUT
addCostumer: ALREADY_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
getPlace: column=7, hight=0
buyRecord: SUCCESS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
isMember: False
putOnTop: INVALID_INPUT
makeMember: SUCCESS
isMember: False
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
putOnTop: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
isMember: False
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=3, hight=15
makeMember: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPlace: column=3, hight=32
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: 171
isMember: False
addCostumer: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
isMember: False
isMember: False
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=3, hight=15
getPlace: column=0, hight=0
addCostumer: SUCCESS
getPhone: 77
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 62
getPhone: 54
addCostumer: SUCCESS
getPlace: column=5, hight=8
getPlace: INVALID_INPUT
addPrize: INVALID_INPUT
makeMember: SUCCESS
putOnTop: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: INVALID_INPUT
getPlace: column=7, hight=15
putOnTop: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 62
putOnTop: SUCCESS
isMember: True
buyRecord: DOESNT_EXISTS
getPhone: 151
buyRecord: SUCCESS
isMember: False
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
