newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=0, hight=0
isMember: False
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
putOnTop: SUCCESS
getPhone: 75
getPlace: column=2, hight=0
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: INVALID_INPUT
getPlace: column=3, hight=0
addPrize: SUCCESS
makeMember: INVALID_INPUT
isMember: False
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=5, hight=12
isMember: False
addCostumer: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 75
isMember: False
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=3, hight=19
buyRecord: SUCCESS
isMember: False
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPhone: 75
addPrize: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
getPlace: column=3, hight=0
isMember: False
isMember: False
getPhone: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 16
getPhone: 9
getPhone: 238
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
isMember: False
getPlace: column=3, hight=7
addPrize: SUCCESS
isMember: False
getExpenses: -59
isMember: False
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
getPlace: column=6, hight=0
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=3, hight=0
isMember: False
buyRecord: SUCCESS
getPhone: 123
getExpenses: DOESNT_EXISTS
getPhone: 75
getPlace: column=3, hight=0
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: False
getExpenses: 141
buyRecord: SUCCESS
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPhone: 117
makeMember: DOESNT_EXISTS
getPhone: 123
getPhone: 176
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
isMember: False
addPrize: SUCCESS
isMember: True
addPrize: SUCCESS
getPhone: 176
putOnTop: SUCCESS
getPhone: 123
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 122
getExpenses: INVALID_INPUT
getExpenses: 8
putOnTop: FAILURE
getPlace: column=3, hight=7
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 248
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
isMember: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 77
addPrize: INVALID_INPUT
getPlace: column=2, hight=0
putOnTop: FAILURE
isMember: False
getPlace: column=3, hight=28
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: False
isMember: True
getPhone: 122
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: INVALID_INPUT
getPhone: 77
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
makeMember: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
isMember: True
buyRecord: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: 141
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 61
isMember: True
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
makeMember: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
isMember: False
isMember: False
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
getPhone: 21
getPlace: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: INVALID_INPUT
addPrize: SUCCESS
isMember: True
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
isMember: False
isMember: False
getPhone: 193
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=3, hight=78
getPhone: 113
addPrize: INVALID_INPUT
addPrize: SUCCESS
isMember: True
makeMember: SUCCESS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
getPlace: column=3, hight=78
addCostumer: SUCCESS
getPhone: 16
addPrize: INVALID_INPUT
getPhone: 117
buyRecord: SUCCESS
getPhone: 248
addPrize: INVALID_INPUT
isMember: False
getPlace: INVALID_INPUT
getExpenses: 48
isMember: False
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPhone: 16
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: INVALID_INPUT
getPlace: column=3, hight=28
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 18
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=3, hight=66
makeMember: SUCCESS
getPhone: 176
addCostumer: SUCCESS
isMember: True
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
getExpenses: 107
getPhone: 165
getPlace: column=3, hight=7
getPhone: 123
addCostumer: SUCCESS
getPhone: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: INVALID_INPUT
getExpenses: INVALID_INPUT
putOnTop: INVALID_INPUT
isMember: False
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=3, hight=7
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
getExpenses: -117
buyRecord: SUCCESS
getPhone: 182
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=3, hight=28
addPrize: INVALID_INPUT
makeMember: INVALID_INPUT
getPhone: 18
makeMember: SUCCESS
getPhone: 26
buyRecord: SUCCESS
addCostumer: SUCCESS
isMember: False
getPhone: 165
makeMember: INVALID_INPUT
addCostumer: ALREADY_EXISTS
isMember: False
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: 6
putOnTop: FAILURE
getPlace: column=3, hight=66
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
getExpenses: -117
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
getPlace: column=3, hight=19
isMember: False
getPhone: 9
addPrize: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 117
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=3, hight=0
getPhone: 83
getPhone: DOESNT_EXISTS
getExpenses: 94
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 176
buyRecord: SUCCESS
isMember: False
putOnTop: FAILURE
addPrize: INVALID_INPUT
putOnTop: FAILURE
getExpenses: -137
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: INVALID_INPUT
addPrize: SUCCESS
putOnTop: FAILURE
getExpenses: INVALID_INPUT
isMember: True
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 75
addPrize: SUCCESS
isMember: True
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: INVALID_INPUT
getPlace: column=3, hight=47
makeMember: SUCCESS
makeMember: SUCCESS
makeMember: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 119
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
putOnTop: DOESNT_EXISTS
isMember: True
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
makeMember: SUCCESS
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
isMember: True
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
getPhone: 177
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
getPlace: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 9
getPhone: 84
getPhone: 176
isMember: False
addCostumer: SUCCESS
isMember: False
getPhone: 171
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getPlace: INVALID_INPUT
isMember: True
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
getPhone: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
getPlace: column=3, hight=19
getExpenses: DOESNT_EXISTS
isMember: False
makeMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPhone: 104
putOnTop: FAILURE
getPlace: column=3, hight=0
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: INVALID_INPUT
addPrize: SUCCESS
getPhone: 106
putOnTop: DOESNT_EXISTS
getPhone: 9
getPhone: 116
isMember: INVALID_INPUT
getPhone: 167
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
getPlace: column=3, hight=0
buyRecord: SUCCESS
isMember: INVALID_INPUT
isMember: True
makeMember: ALREADY_EXISTS
isMember: True
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
getPhone: 75
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: False
addCostumer: SUCCESS
getPhone: 75
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=3, hight=0
getExpenses: DOESNT_EXISTS
getPlace: column=3, hight=19
addCostumer: ALREADY_EXISTS
getPlace: column=3, hight=28
isMember: False
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
putOnTop: INVALID_INPUT
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 26
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 122
isMember: False
addPrize: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
isMember: True
makeMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=3, hight=78
makeMember: SUCCESS
makeMember: SUCCESS
getPhone: 9
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
buyRecord: SUCCESS
isMember: False
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
isMember: True
addPrize: SUCCESS
newMonth: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: 0
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: False
getPhone: 167
isMember: False
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: True
makeMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 38
buyRecord: SUCCESS
putOnTop: SUCCESS
isMember: INVALID_INPUT
isMember: True
makeMember: SUCCESS
putOnTop: INVALID_INPUT
getPhone: 155
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPhone: 104
getPhone: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
getPhone: INVALID_INPUT
isMember: INVALID_INPUT
addPrize: SUCCESS
putOnTop: FAILURE
getExpenses: 0
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 165
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=4, hight=0
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=3, hight=0
getPhone: 26
makeMember: ALREADY_EXISTS
getPlace: column=14, hight=0
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
getPhone: 248
getPhone: 104
getExpenses: -162
makeMember: SUCCESS
putOnTop: SUCCESS
getPhone: 97
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addPrize: INVALID_INPUT
makeMember: DOESNT_EXISTS
buyRecord: INVALID_INPUT
makeMember: SUCCESS
isMember: True
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPhone: INVALID_INPUT
getPhone: 42
getPlace: column=10, hight=24
getPhone: 9
getExpenses: -162
isMember: False
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
isMember: False
getPhone: 123
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
getExpenses: 0
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
getPhone: 248
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=4, hight=0
addCostumer: SUCCESS
isMember: False
isMember: False
addCostumer: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
getPlace: INVALID_INPUT
getPhone: 26
addPrize: INVALID_INPUT
getPhone: 64
getPhone: 38
getExpenses: DOESNT_EXISTS
getPlace: column=13, hight=16
putOnTop: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getPhone: 176
getPlace: DOESNT_EXISTS
getPlace: INVALID_INPUT
getPhone: INVALID_INPUT
getExpenses: INVALID_INPUT
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 148
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=1, hight=0
getPlace: column=3, hight=0
putOnTop: SUCCESS
putOnTop: SUCCESS
isMember: False
buyRecord: INVALID_INPUT
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: 217
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
newMonth: SUCCESS
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: column=1, hight=0
getPhone: 75
getPhone: 217
getPhone: 191
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
getPlace: INVALID_INPUT
isMember: True
getPlace: INVALID_INPUT
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
isMember: True
getPlace: column=0, hight=0
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPhone: 25
addCostumer: SUCCESS
isMember: True
getPlace: column=2, hight=0
addCostumer: SUCCESS
getPlace: INVALID_INPUT
addPrize: SUCCESS
isMember: False
getPlace: column=5, hight=0
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=5, hight=0
getExpenses: INVALID_INPUT
isMember: INVALID_INPUT
isMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
getExpenses: 0
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
isMember: False
isMember: True
getPlace: column=1, hight=0
getPlace: column=2, hight=0
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
isMember: True
addPrize: SUCCESS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 9
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 176
makeMember: SUCCESS
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
getPhone: 169
putOnTop: SUCCESS
addCostumer: SUCCESS
getExpenses: 0
isMember: True
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: INVALID_INPUT
getPhone: 238
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
getPhone: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: INVALID_INPUT
getPhone: 77
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: INVALID_INPUT
isMember: False
getPhone: 178
putOnTop: FAILURE
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: 0
putOnTop: FAILURE
isMember: DOESNT_EXISTS
getExpenses: -4
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=2, hight=34
addPrize: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPhone: 0
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 104
makeMember: SUCCESS
getPlace: INVALID_INPUT
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: True
isMember: False
getPlace: DOESNT_EXISTS
getPlace: column=3, hight=0
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: True
getExpenses: -4
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 199
makeMember: SUCCESS
getPlace: column=2, hight=27
getPhone: 217
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
getPlace: column=2, hight=27
addPrize: INVALID_INPUT
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=4, hight=0
getPhone: 248
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 156
makeMember: ALREADY_EXISTS
getExpenses: -220
isMember: False
isMember: False
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: INVALID_INPUT
isMember: True
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 148
isMember: True
getPhone: 13
getExpenses: -86
getPlace: INVALID_INPUT
getPlace: column=3, hight=0
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 155
getPhone: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getPhone: 72
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=2, hight=34
makeMember: DOESNT_EXISTS
getPlace: column=2, hight=0
getPhone: 61
isMember: True
getPhone: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
getPhone: 103
getPhone: 191
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 12
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -161
putOnTop: FAILURE
getPlace: column=2, hight=34
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
