newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: True
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=0, hight=0
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: False
makeMember: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: 0
isMember: True
isMember: True
buyRecord: SUCCESS
getExpenses: 300
addCostumer: SUCCESS
getPlace: column=12, hight=0
putOnTop: SUCCESS
addPrize: SUCCESS
getPhone: 112
getPhone: 112
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
putOnTop: SUCCESS
getExpenses: 0
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=22, hight=0
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: column=7, hight=0
getPhone: 36
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 108
getPlace: column=19, hight=0
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
isMember: False
makeMember: DOESNT_EXISTS
putOnTop: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: -135
isMember: False
addPrize: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 219
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: True
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: 20
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 157
buyRecord: SUCCESS
getExpenses: 10
getPhone: 108
buyRecord: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
getPhone: 59
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=0, hight=0
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
makeMember: SUCCESS
getPlace: column=26, hight=0
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
isMember: True
addCostumer: INVALID_INPUT
getPlace: column=15, hight=12
addPrize: SUCCESS
isMember: DOESNT_EXISTS
isMember: True
getPhone: 36
getPlace: column=12, hight=6
putOnTop: FAILURE
getPlace: column=4, hight=0
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
addPrize: INVALID_INPUT
makeMember: SUCCESS
addPrize: INVALID_INPUT
isMember: False
addCostumer: SUCCESS
getPlace: INVALID_INPUT
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
isMember: False
addCostumer: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
getPhone: 43
putOnTop: SUCCESS
buyRecord: INVALID_INPUT
getPlace: column=15, hight=13
getExpenses: INVALID_INPUT
getPhone: 18
getExpenses: 499
buyRecord: INVALID_INPUT
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
getPhone: 157
getExpenses: DOESNT_EXISTS
getPlace: column=21, hight=14
putOnTop: DOESNT_EXISTS
getExpenses: -29
getPhone: 112
getPlace: column=15, hight=28
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
isMember: True
addPrize: SUCCESS
getExpenses: -29
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
isMember: True
getPlace: column=15, hight=13
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPhone: 43
putOnTop: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=12, hight=61
getPhone: 90
makeMember: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 158
getExpenses: DOESNT_EXISTS
getPlace: column=15, hight=12
getPlace: column=11, hight=0
addCostumer: SUCCESS
isMember: INVALID_INPUT
isMember: True
addPrize: INVALID_INPUT
getPhone: 43
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
getPlace: column=15, hight=69
getPlace: column=12, hight=6
getExpenses: 0
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: FAILURE
isMember: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: column=15, hight=0
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
getPhone: 59
makeMember: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=15, hight=151
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 240
makeMember: ALREADY_EXISTS
getPlace: column=15, hight=106
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
getPlace: column=21, hight=14
buyRecord: SUCCESS
getExpenses: 78
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getPhone: 157
getPlace: column=9, hight=105
getPlace: column=21, hight=0
putOnTop: FAILURE
getPlace: column=9, hight=21
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: 600
makeMember: SUCCESS
getPhone: 112
getPlace: column=21, hight=0
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 190
putOnTop: SUCCESS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: 0
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
isMember: True
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: -79
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
getPlace: column=21, hight=27
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: False
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: column=21, hight=27
makeMember: SUCCESS
addPrize: SUCCESS
getPlace: column=20, hight=13
addCostumer: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: 0
addPrize: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
getPlace: column=21, hight=14
getPlace: column=21, hight=113
addPrize: INVALID_INPUT
getPhone: 63
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: True
getExpenses: -90
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getExpenses: 0
makeMember: DOESNT_EXISTS
isMember: True
isMember: DOESNT_EXISTS
getPhone: 112
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=21, hight=27
buyRecord: SUCCESS
getExpenses: -256
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: column=21, hight=159
getPhone: INVALID_INPUT
isMember: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
getPlace: column=21, hight=41
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 190
isMember: INVALID_INPUT
getPhone: 0
getPhone: 63
makeMember: ALREADY_EXISTS
getPlace: column=4, hight=0
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: INVALID_INPUT
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=21, hight=14
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: False
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 166
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: 63
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
isMember: INVALID_INPUT
isMember: False
getPlace: column=21, hight=14
buyRecord: SUCCESS
getPhone: 166
addCostumer: SUCCESS
getPhone: 61
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
addPrize: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: -274
isMember: True
addPrize: SUCCESS
isMember: False
putOnTop: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 158
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPlace: column=21, hight=113
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 155
isMember: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: column=1, hight=0
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 190
addPrize: INVALID_INPUT
getPlace: column=6, hight=0
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=21, hight=131
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=21, hight=77
makeMember: INVALID_INPUT
addPrize: SUCCESS
isMember: False
getExpenses: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: True
addPrize: SUCCESS
getPhone: 55
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: True
getPhone: 28
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
putOnTop: INVALID_INPUT
getPlace: column=21, hight=27
getPhone: DOESNT_EXISTS
getPlace: column=21, hight=159
getExpenses: INVALID_INPUT
getPlace: column=21, hight=168
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getPhone: 98
isMember: False
getPhone: 196
putOnTop: DOESNT_EXISTS
isMember: True
isMember: False
isMember: True
makeMember: SUCCESS
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=4, hight=0
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=6, hight=206
getPhone: INVALID_INPUT
makeMember: INVALID_INPUT
isMember: INVALID_INPUT
getPhone: 43
getPhone: 173
getPlace: column=6, hight=0
makeMember: ALREADY_EXISTS
getPlace: column=6, hight=38
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=6, hight=188
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 112
isMember: True
getExpenses: -178
isMember: True
getExpenses: -576
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 36
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
isMember: True
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=6, hight=52
putOnTop: FAILURE
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: True
addPrize: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
isMember: False
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=6, hight=242
getPhone: 230
getPhone: 55
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -185
makeMember: INVALID_INPUT
getPlace: column=6, hight=0
buyRecord: SUCCESS
isMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
isMember: False
getPhone: 73
addPrize: SUCCESS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: -238
addCostumer: SUCCESS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: DOESNT_EXISTS
getPhone: 190
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
getPhone: 59
getPlace: column=6, hight=114
addCostumer: SUCCESS
getPhone: 136
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: INVALID_INPUT
getPhone: DOESNT_EXISTS
isMember: False
makeMember: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=6, hight=252
addCostumer: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getPhone: 55
buyRecord: SUCCESS
getPhone: 61
getPlace: column=6, hight=25
addPrize: INVALID_INPUT
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: True
makeMember: ALREADY_EXISTS
isMember: True
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=6, hight=101
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
addPrize: SUCCESS
addCostumer: INVALID_INPUT
getPhone: 171
getPlace: column=6, hight=88
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPhone: 135
putOnTop: INVALID_INPUT
getPhone: 18
putOnTop: FAILURE
getPhone: 82
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 166
getExpenses: DOESNT_EXISTS
getPhone: 17
isMember: True
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPhone: 166
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: column=6, hight=224
getExpenses: -143
addPrize: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: INVALID_INPUT
isMember: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
addPrize: SUCCESS
getPlace: column=6, hight=110
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
getPhone: DOESNT_EXISTS
getPlace: column=6, hight=38
getPhone: 43
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
putOnTop: FAILURE
putOnTop: FAILURE
addPrize: SUCCESS
getExpenses: -561
addPrize: INVALID_INPUT
getPlace: column=6, hight=158
addCostumer: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getPlace: column=6, hight=224
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: -1003
getPlace: column=6, hight=11
makeMember: DOESNT_EXISTS
getPhone: 171
buyRecord: SUCCESS
getExpenses: -139
putOnTop: FAILURE
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
newMonth: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 155
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 61
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: -50
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: column=9, hight=0
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: 61
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: INVALID_INPUT
makeMember: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getExpenses: -84
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getPhone: 36
isMember: True
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPlace: column=6, hight=0
addCostumer: SUCCESS
isMember: False
addPrize: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: True
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: -137
getPlace: DOESNT_EXISTS
getPlace: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: INVALID_INPUT
getPhone: 151
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: column=4, hight=0
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 180
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: 184
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
makeMember: DOESNT_EXISTS
getPhone: 123
makeMember: SUCCESS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=8, hight=21
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=8, hight=21
buyRecord: SUCCESS
isMember: True
addCostumer: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
getExpenses: -176
getPlace: column=3, hight=0
addPrize: SUCCESS
getPhone: 35
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: column=5, hight=0
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: True
getPhone: 28
getExpenses: -104
addCostumer: ALREADY_EXISTS
getExpenses: INVALID_INPUT
putOnTop: SUCCESS
getPlace: column=1, hight=0
getPlace: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getPlace: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=5, hight=11
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: True
addPrize: INVALID_INPUT
getPhone: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: True
addCostumer: ALREADY_EXISTS
getPlace: column=5, hight=40
getExpenses: DOESNT_EXISTS
getPlace: column=5, hight=48
buyRecord: SUCCESS
isMember: INVALID_INPUT
isMember: DOESNT_EXISTS
isMember: True
getExpenses: -268
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: SUCCESS
getExpenses: -261
getPlace: column=1, hight=57
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPhone: INVALID_INPUT
getPhone: 17
addPrize: SUCCESS
getPhone: 108
getPlace: column=1, hight=16
addCostumer: SUCCESS
addCostumer: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPlace: column=1, hight=16
buyRecord: SUCCESS
isMember: INVALID_INPUT
getPhone: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=1, hight=16
getExpenses: -287
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: column=1, hight=0
getPlace: column=1, hight=47
buyRecord: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 153
addCostumer: SUCCESS
getExpenses: -34
getExpenses: -292
getPlace: column=1, hight=0
putOnTop: INVALID_INPUT
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
buyRecord: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 151
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=1, hight=0
getPhone: DOESNT_EXISTS
isMember: False
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: 31
isMember: True
getPhone: 166
buyRecord: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
getPlace: column=1, hight=47
addCostumer: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: -259
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: -371
addPrize: SUCCESS
isMember: True
isMember: False
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: True
getExpenses: -342
getExpenses: -70
addCostumer: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 224
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
getPlace: column=1, hight=47
getPhone: 136
putOnTop: INVALID_INPUT
