newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: column=17, hight=0
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPlace: column=18, hight=0
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
getPhone: 10
getPlace: column=24, hight=0
getPhone: 66
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
getPhone: 249
putOnTop: SUCCESS
addCostumer: SUCCESS
isMember: False
isMember: INVALID_INPUT
makeMember: SUCCESS
putOnTop: SUCCESS
getPhone: 204
makeMember: SUCCESS
getPlace: column=24, hight=0
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=8, hight=28
getPlace: column=12, hight=0
addPrize: SUCCESS
isMember: False
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 114
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 102
putOnTop: INVALID_INPUT
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=2, hight=0
putOnTop: SUCCESS
getPhone: 249
buyRecord: SUCCESS
putOnTop: SUCCESS
getPlace: column=3, hight=0
makeMember: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: True
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=12, hight=0
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
isMember: True
getPhone: 46
isMember: False
getPlace: column=26, hight=0
getPhone: 10
getPhone: 114
addCostumer: SUCCESS
putOnTop: SUCCESS
isMember: False
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: True
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
getExpenses: 107
buyRecord: INVALID_INPUT
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=23, hight=0
getPlace: DOESNT_EXISTS
putOnTop: SUCCESS
putOnTop: FAILURE
isMember: True
addCostumer: SUCCESS
isMember: True
addCostumer: INVALID_INPUT
putOnTop: SUCCESS
isMember: DOESNT_EXISTS
getPlace: column=23, hight=16
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
isMember: True
getPlace: column=8, hight=110
isMember: True
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: 10
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: True
isMember: False
addCostumer: SUCCESS
getPhone: INVALID_INPUT
isMember: False
isMember: True
putOnTop: INVALID_INPUT
isMember: INVALID_INPUT
putOnTop: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addPrize: INVALID_INPUT
isMember: False
getPlace: column=6, hight=101
buyRecord: SUCCESS
getPlace: column=6, hight=130
getPlace: column=18, hight=0
getExpenses: DOESNT_EXISTS
getPhone: 75
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: True
putOnTop: SUCCESS
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: False
putOnTop: FAILURE
putOnTop: INVALID_INPUT
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getPhone: 237
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=12, hight=119
putOnTop: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
makeMember: SUCCESS
getPhone: 157
isMember: True
getPhone: 19
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 75
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
getPhone: 102
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
isMember: DOESNT_EXISTS
getPhone: 249
getPhone: 66
isMember: True
getPlace: column=12, hight=47
getPlace: column=4, hight=0
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: INVALID_INPUT
makeMember: SUCCESS
getPlace: column=23, hight=33
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
isMember: False
addCostumer: INVALID_INPUT
getPhone: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 237
isMember: True
isMember: DOESNT_EXISTS
putOnTop: FAILURE
isMember: False
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=23, hight=61
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
isMember: True
putOnTop: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 158
makeMember: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: True
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 204
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 114
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: SUCCESS
makeMember: SUCCESS
getPlace: column=13, hight=155
buyRecord: SUCCESS
getPhone: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=13, hight=216
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 244
putOnTop: SUCCESS
makeMember: SUCCESS
isMember: False
isMember: False
putOnTop: FAILURE
addPrize: SUCCESS
isMember: INVALID_INPUT
makeMember: INVALID_INPUT
isMember: True
addCostumer: SUCCESS
isMember: False
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
isMember: True
getPlace: column=13, hight=134
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
putOnTop: FAILURE
isMember: True
getPhone: 183
isMember: False
getExpenses: 201
isMember: True
putOnTop: FAILURE
getPlace: column=13, hight=110
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPhone: 204
getPhone: 245
getPhone: 115
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=13, hight=216
getExpenses: 21
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
isMember: True
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPhone: 35
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: INVALID_INPUT
getExpenses: 100
putOnTop: INVALID_INPUT
makeMember: SUCCESS
getPhone: 125
isMember: False
getPhone: 51
getPhone: 245
isMember: True
isMember: False
makeMember: ALREADY_EXISTS
getPlace: column=13, hight=69
getPhone: 51
makeMember: ALREADY_EXISTS
getPhone: 82
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: SUCCESS
getPlace: column=18, hight=227
isMember: True
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=18, hight=253
addCostumer: SUCCESS
getPlace: column=18, hight=179
makeMember: ALREADY_EXISTS
getPlace: column=18, hight=153
getPlace: column=18, hight=257
putOnTop: DOESNT_EXISTS
getPlace: column=18, hight=145
getPhone: 244
getPhone: 244
getPlace: column=18, hight=257
putOnTop: FAILURE
getPhone: INVALID_INPUT
getExpenses: -404
makeMember: SUCCESS
makeMember: SUCCESS
isMember: False
isMember: False
addCostumer: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=18, hight=166
getExpenses: -445
addCostumer: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 82
getPhone: 125
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 196
getPlace: column=18, hight=11
isMember: INVALID_INPUT
getPhone: 108
addPrize: SUCCESS
getPlace: column=18, hight=166
getPlace: column=18, hight=145
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=18, hight=117
getPlace: column=18, hight=261
addCostumer: SUCCESS
getPhone: 234
addCostumer: INVALID_INPUT
getPlace: column=18, hight=136
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: FAILURE
isMember: True
makeMember: SUCCESS
addPrize: INVALID_INPUT
isMember: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: INVALID_INPUT
putOnTop: FAILURE
addPrize: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
getPlace: column=1, hight=0
getExpenses: -249
isMember: True
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
getExpenses: 0
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=18, hight=253
putOnTop: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 61
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
isMember: True
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 108
getExpenses: -281
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: -242
addPrize: INVALID_INPUT
getPlace: column=18, hight=247
getPhone: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
isMember: True
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
getPhone: 233
getExpenses: -653
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getExpenses: 0
buyRecord: INVALID_INPUT
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
isMember: False
putOnTop: FAILURE
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
isMember: DOESNT_EXISTS
makeMember: SUCCESS
isMember: True
addPrize: INVALID_INPUT
addPrize: SUCCESS
getExpenses: -32
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: column=1, hight=104
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 187
getPlace: column=1, hight=112
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getPlace: column=1, hight=151
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: INVALID_INPUT
isMember: False
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
getPhone: 53
getPlace: column=1, hight=171
buyRecord: SUCCESS
getPlace: column=1, hight=67
addPrize: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
addCostumer: SUCCESS
getPlace: column=1, hight=242
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPhone: 0
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
getPlace: column=1, hight=181
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: -602
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=1, hight=268
addPrize: INVALID_INPUT
getPlace: column=1, hight=112
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: -245
getPhone: 196
isMember: False
isMember: True
makeMember: SUCCESS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=1, hight=223
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: False
getPlace: column=1, hight=112
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=1, hight=34
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: INVALID_INPUT
makeMember: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getPlace: column=1, hight=136
addPrize: SUCCESS
putOnTop: FAILURE
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 35
getExpenses: 164
addCostumer: SUCCESS
makeMember: INVALID_INPUT
getPhone: 237
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: INVALID_INPUT
getPhone: 92
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: True
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
isMember: True
getPlace: column=1, hight=181
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 233
getPhone: 196
isMember: True
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 183
isMember: False
putOnTop: INVALID_INPUT
getPlace: column=1, hight=0
getPhone: 204
addPrize: INVALID_INPUT
putOnTop: FAILURE
putOnTop: FAILURE
buyRecord: INVALID_INPUT
getPlace: column=1, hight=171
buyRecord: DOESNT_EXISTS
getPhone: 241
makeMember: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 9
getPhone: 244
addPrize: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: INVALID_INPUT
isMember: True
getPhone: 6
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
isMember: True
getPlace: column=1, hight=276
getExpenses: DOESNT_EXISTS
getExpenses: -234
getPhone: 162
addPrize: INVALID_INPUT
addCostumer: SUCCESS
isMember: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
isMember: INVALID_INPUT
makeMember: INVALID_INPUT
putOnTop: FAILURE
isMember: False
putOnTop: FAILURE
putOnTop: FAILURE
addPrize: SUCCESS
getPlace: column=1, hight=112
putOnTop: FAILURE
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: False
makeMember: INVALID_INPUT
buyRecord: INVALID_INPUT
addPrize: SUCCESS
makeMember: SUCCESS
getPlace: column=1, hight=272
getPhone: 37
getPlace: column=1, hight=15
addPrize: SUCCESS
getPlace: column=1, hight=171
getExpenses: DOESNT_EXISTS
getPlace: column=1, hight=0
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 206
isMember: True
addPrize: INVALID_INPUT
isMember: False
putOnTop: FAILURE
addCostumer: INVALID_INPUT
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 37
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
isMember: True
putOnTop: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 53
isMember: INVALID_INPUT
getPlace: column=1, hight=0
addCostumer: SUCCESS
getExpenses: 0
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: False
getPhone: 79
buyRecord: SUCCESS
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=1, hight=160
putOnTop: FAILURE
getPhone: 183
isMember: True
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=1, hight=262
addCostumer: SUCCESS
getPlace: column=1, hight=112
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: False
getExpenses: -458
putOnTop: FAILURE
getExpenses: -812
getPhone: 6
getPlace: column=1, hight=168
isMember: True
isMember: False
getPlace: column=1, hight=15
addCostumer: ALREADY_EXISTS
getPlace: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: False
makeMember: ALREADY_EXISTS
addCostumer: INVALID_INPUT
isMember: True
isMember: True
isMember: False
getPlace: column=1, hight=283
putOnTop: FAILURE
addPrize: INVALID_INPUT
putOnTop: FAILURE
getPlace: column=1, hight=136
getPhone: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=1, hight=26
getPlace: column=1, hight=151
buyRecord: INVALID_INPUT
getExpenses: -211
buyRecord: SUCCESS
getPhone: 203
buyRecord: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: False
buyRecord: INVALID_INPUT
getPhone: 214
getPlace: column=1, hight=262
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: column=1, hight=223
isMember: False
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: 4
buyRecord: SUCCESS
isMember: True
addCostumer: ALREADY_EXISTS
getPhone: 133
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=1, hight=242
buyRecord: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 245
makeMember: ALREADY_EXISTS
isMember: False
putOnTop: FAILURE
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPhone: 244
getPhone: 114
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
isMember: False
makeMember: SUCCESS
isMember: False
addPrize: SUCCESS
getPhone: 206
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
addPrize: INVALID_INPUT
isMember: False
addPrize: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 152
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=1, hight=223
getPhone: 124
makeMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
getPlace: column=1, hight=171
getPlace: column=1, hight=34
getExpenses: -726
makeMember: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=1, hight=112
addPrize: INVALID_INPUT
addPrize: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=1, hight=242
putOnTop: FAILURE
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 80
getExpenses: INVALID_INPUT
getPhone: 206
makeMember: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
getPlace: column=1, hight=213
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getPlace: column=1, hight=171
getPhone: 19
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
getPhone: 182
getPhone: 66
getExpenses: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
getPlace: column=1, hight=276
getPlace: column=1, hight=283
isMember: True
addCostumer: ALREADY_EXISTS
getPlace: column=1, hight=15
putOnTop: FAILURE
getExpenses: -389
addCostumer: SUCCESS
getPlace: column=1, hight=160
makeMember: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=1, hight=132
isMember: INVALID_INPUT
addCostumer: INVALID_INPUT
putOnTop: FAILURE
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 35
makeMember: DOESNT_EXISTS
isMember: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: FAILURE
isMember: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
getPhone: 46
buyRecord: DOESNT_EXISTS
getExpenses: -39
isMember: True
getExpenses: DOESNT_EXISTS
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
makeMember: INVALID_INPUT
getExpenses: -72
makeMember: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: -589
getExpenses: -1017
getExpenses: -857
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
getPlace: column=1, hight=15
isMember: True
isMember: True
putOnTop: FAILURE
getPhone: 239
isMember: True
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 80
isMember: INVALID_INPUT
makeMember: SUCCESS
isMember: False
isMember: True
addCostumer: SUCCESS
getPhone: 114
getPhone: 222
isMember: INVALID_INPUT
makeMember: SUCCESS
buyRecord: SUCCESS
