newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: INVALID_INPUT
putOnTop: FAILURE
isMember: DOESNT_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
putOnTop: INVALID_INPUT
makeMember: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: 231
makeMember: SUCCESS
isMember: False
getPhone: 117
getPhone: 7
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: INVALID_INPUT
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getPlace: column=3, hight=0
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: -39
isMember: False
isMember: True
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
makeMember: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=4, hight=0
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: True
isMember: True
addPrize: SUCCESS
getExpenses: -39
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: -39
getPhone: DOESNT_EXISTS
isMember: False
isMember: False
putOnTop: DOESNT_EXISTS
getExpenses: -39
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
getPhone: 7
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: True
isMember: False
getPlace: column=4, hight=0
isMember: False
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
buyRecord: INVALID_INPUT
getPhone: INVALID_INPUT
getExpenses: 0
makeMember: INVALID_INPUT
addPrize: SUCCESS
isMember: False
getPlace: column=0, hight=0
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: -109
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 99
getExpenses: 0
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: 0
putOnTop: SUCCESS
makeMember: SUCCESS
isMember: True
putOnTop: SUCCESS
getExpenses: 0
putOnTop: SUCCESS
isMember: False
isMember: False
getPhone: 93
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: FAILURE
isMember: INVALID_INPUT
makeMember: INVALID_INPUT
putOnTop: SUCCESS
getPhone: 97
isMember: False
getExpenses: 53
addCostumer: SUCCESS
isMember: True
getPlace: column=12, hight=0
getExpenses: 0
getPlace: column=10, hight=49
isMember: DOESNT_EXISTS
getPlace: column=10, hight=49
getPlace: INVALID_INPUT
isMember: False
putOnTop: SUCCESS
getPhone: 39
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: column=3, hight=63
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 98
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: INVALID_INPUT
isMember: INVALID_INPUT
addCostumer: SUCCESS
getPlace: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
getPhone: INVALID_INPUT
getExpenses: INVALID_INPUT
makeMember: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: True
getExpenses: 0
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: 0
getPlace: column=9, hight=0
isMember: True
addPrize: INVALID_INPUT
makeMember: SUCCESS
buyRecord: INVALID_INPUT
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: -39
getPlace: column=9, hight=0
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
getPhone: 234
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=2, hight=69
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 98
getPlace: column=6, hight=45
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 178
makeMember: ALREADY_EXISTS
getPlace: column=6, hight=43
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: 141
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
buyRecord: INVALID_INPUT
getPlace: column=6, hight=0
getPlace: column=6, hight=99
getPhone: 13
addCostumer: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
getPhone: 164
buyRecord: SUCCESS
getPlace: INVALID_INPUT
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: column=9, hight=0
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: column=6, hight=75
getExpenses: 203
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=6, hight=6
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
putOnTop: FAILURE
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: False
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 222
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: INVALID_INPUT
isMember: True
getPhone: 177
getPhone: 182
addPrize: SUCCESS
isMember: False
putOnTop: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: column=6, hight=43
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: False
makeMember: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: INVALID_INPUT
addPrize: SUCCESS
isMember: False
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
getExpenses: 0
getPlace: column=6, hight=130
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: -78
isMember: False
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
getPhone: 173
makeMember: SUCCESS
addPrize: SUCCESS
isMember: False
getPhone: 13
buyRecord: DOESNT_EXISTS
getPhone: 117
addPrize: SUCCESS
getPlace: column=6, hight=99
makeMember: SUCCESS
makeMember: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 39
getPhone: 102
isMember: False
getPhone: 13
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 99
putOnTop: DOESNT_EXISTS
isMember: True
isMember: True
makeMember: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
getExpenses: -456
addCostumer: SUCCESS
getExpenses: -314
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: INVALID_INPUT
addPrize: SUCCESS
isMember: True
isMember: True
isMember: True
putOnTop: FAILURE
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: 0
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: 0
getPhone: 235
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
putOnTop: FAILURE
makeMember: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: True
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
getExpenses: 0
getPlace: DOESNT_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: 0
getPlace: column=8, hight=22
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=8, hight=36
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: -445
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
getPlace: column=8, hight=16
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: -205
getPhone: INVALID_INPUT
getExpenses: -573
putOnTop: FAILURE
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
isMember: True
getPlace: column=8, hight=53
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: -284
getPlace: column=8, hight=132
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
getPlace: column=8, hight=127
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 182
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=8, hight=140
getPlace: column=8, hight=127
putOnTop: FAILURE
buyRecord: SUCCESS
getExpenses: -460
getPhone: 13
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: INVALID_INPUT
addPrize: SUCCESS
makeMember: INVALID_INPUT
addPrize: SUCCESS
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
isMember: True
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
getPhone: 57
addCostumer: ALREADY_EXISTS
getExpenses: -250
addCostumer: SUCCESS
getPhone: 231
putOnTop: FAILURE
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPlace: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: column=8, hight=109
getPhone: 117
addPrize: SUCCESS
putOnTop: FAILURE
getPhone: 234
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: -50
buyRecord: SUCCESS
isMember: True
putOnTop: FAILURE
putOnTop: FAILURE
putOnTop: FAILURE
getPlace: column=8, hight=85
getExpenses: -234
isMember: True
getExpenses: 154
getExpenses: -50
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 205
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
isMember: False
getExpenses: -494
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: INVALID_INPUT
getPhone: 97
addCostumer: SUCCESS
getPlace: column=8, hight=127
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: FAILURE
getPlace: column=8, hight=55
getPhone: 0
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
putOnTop: FAILURE
getPhone: 177
putOnTop: DOESNT_EXISTS
getPlace: column=8, hight=22
isMember: False
makeMember: SUCCESS
isMember: INVALID_INPUT
isMember: True
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: INVALID_INPUT
getPlace: INVALID_INPUT
putOnTop: FAILURE
buyRecord: DOESNT_EXISTS
buyRecord: INVALID_INPUT
getExpenses: -148
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
getExpenses: -780
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
getPhone: 13
getExpenses: DOESNT_EXISTS
getPlace: column=8, hight=85
getPlace: column=8, hight=140
getPhone: 30
addPrize: INVALID_INPUT
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 117
addPrize: SUCCESS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
isMember: False
buyRecord: SUCCESS
isMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPlace: column=8, hight=16
addCostumer: ALREADY_EXISTS
isMember: True
getExpenses: -570
makeMember: SUCCESS
addPrize: INVALID_INPUT
isMember: INVALID_INPUT
isMember: True
makeMember: SUCCESS
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
isMember: False
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=8, hight=132
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
getPlace: column=8, hight=91
isMember: False
makeMember: SUCCESS
isMember: True
addPrize: INVALID_INPUT
getExpenses: -714
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: 0
putOnTop: FAILURE
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 98
getPlace: DOESNT_EXISTS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 93
getExpenses: -391
isMember: False
getPlace: column=8, hight=10
isMember: False
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
makeMember: INVALID_INPUT
addCostumer: ALREADY_EXISTS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 0
buyRecord: SUCCESS
getPhone: 64
makeMember: INVALID_INPUT
buyRecord: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
getExpenses: -943
buyRecord: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 0
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: -637
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
getExpenses: 103
getExpenses: 0
buyRecord: SUCCESS
getPlace: column=8, hight=91
getPlace: column=8, hight=132
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: False
makeMember: SUCCESS
isMember: False
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPlace: column=8, hight=10
getExpenses: 0
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
isMember: True
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 178
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 188
isMember: True
getPhone: 177
buyRecord: SUCCESS
getPhone: 127
isMember: DOESNT_EXISTS
getPhone: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
getPlace: column=8, hight=16
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 102
getPlace: column=8, hight=73
getPhone: DOESNT_EXISTS
getPhone: 13
getPlace: column=8, hight=53
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: DOESNT_EXISTS
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: False
addCostumer: SUCCESS
getExpenses: -1226
getPhone: INVALID_INPUT
makeMember: INVALID_INPUT
buyRecord: INVALID_INPUT
getPhone: 152
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=8, hight=16
getPhone: 102
getExpenses: INVALID_INPUT
getPlace: DOESNT_EXISTS
buyRecord: INVALID_INPUT
getPhone: 99
getPlace: column=8, hight=127
putOnTop: INVALID_INPUT
getPlace: column=8, hight=140
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: -87
putOnTop: FAILURE
isMember: False
getPhone: DOESNT_EXISTS
getPlace: column=8, hight=127
getPhone: 2
putOnTop: FAILURE
isMember: True
addCostumer: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
isMember: False
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
putOnTop: FAILURE
getExpenses: -120
makeMember: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getExpenses: INVALID_INPUT
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: 67
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: column=8, hight=109
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: -1404
getPhone: 68
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=8, hight=73
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=8, hight=73
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
isMember: INVALID_INPUT
putOnTop: FAILURE
addPrize: SUCCESS
getExpenses: 32
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: INVALID_INPUT
getPlace: column=8, hight=91
addCostumer: SUCCESS
putOnTop: FAILURE
getExpenses: -65
addCostumer: SUCCESS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getPhone: 190
makeMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: INVALID_INPUT
putOnTop: FAILURE
getPhone: 231
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
isMember: INVALID_INPUT
isMember: True
isMember: True
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: -384
getPhone: 170
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPhone: 3
buyRecord: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getExpenses: 6
putOnTop: FAILURE
isMember: True
getPlace: INVALID_INPUT
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 96
getExpenses: DOESNT_EXISTS
getPlace: column=8, hight=127
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: column=8, hight=55
getPhone: 177
addCostumer: ALREADY_EXISTS
getExpenses: -906
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=8, hight=91
isMember: False
getPhone: 3
makeMember: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: -906
buyRecord: SUCCESS
isMember: True
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: -828
putOnTop: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
addPrize: INVALID_INPUT
putOnTop: FAILURE
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getPhone: INVALID_INPUT
makeMember: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: 6
addPrize: INVALID_INPUT
getExpenses: -369
putOnTop: FAILURE
addPrize: SUCCESS
getPlace: column=8, hight=55
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
getPlace: column=8, hight=73
buyRecord: SUCCESS
addCostumer: SUCCESS
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
isMember: False
getPhone: 231
putOnTop: FAILURE
getPhone: 98
getPhone: 195
getPhone: 236
makeMember: INVALID_INPUT
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 148
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 68
getPlace: column=8, hight=91
getPlace: column=8, hight=109
getExpenses: -1695
addPrize: INVALID_INPUT
addCostumer: SUCCESS
isMember: True
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
isMember: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
putOnTop: FAILURE
isMember: False
getPlace: DOESNT_EXISTS
getPhone: 111
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=8, hight=53
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: INVALID_INPUT
buyRecord: SUCCESS
isMember: False
getPhone: 50
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=8, hight=22
isMember: True
getExpenses: -177
putOnTop: FAILURE
buyRecord: SUCCESS
isMember: True
getPlace: column=8, hight=16
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 222
addPrize: SUCCESS
addPrize: INVALID_INPUT
isMember: False
isMember: False
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: INVALID_INPUT
getPlace: column=8, hight=10
makeMember: SUCCESS
putOnTop: FAILURE
getPhone: 64
getExpenses: -1179
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: 9
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: -1264
getPlace: DOESNT_EXISTS
getExpenses: 174
getPlace: column=8, hight=16
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
