newMonth: SUCCESS
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 221
buyRecord: SUCCESS
putOnTop: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: SUCCESS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 139
getPlace: column=8, hight=0
getExpenses: 0
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getPhone: 221
getPlace: column=17, hight=0
addCostumer: SUCCESS
getPlace: column=27, hight=0
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: True
isMember: True
putOnTop: SUCCESS
makeMember: SUCCESS
getExpenses: -7
isMember: True
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: 0
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 139
getExpenses: 100
getPhone: 92
makeMember: ALREADY_EXISTS
getExpenses: 93
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=8, hight=0
getPhone: 125
putOnTop: SUCCESS
getPhone: 92
getPlace: column=17, hight=0
makeMember: SUCCESS
getPlace: column=32, hight=0
putOnTop: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=13, hight=0
isMember: True
getExpenses: 201
putOnTop: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
isMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 53
getPlace: column=15, hight=0
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
getPhone: INVALID_INPUT
getPlace: column=1, hight=0
addCostumer: SUCCESS
getPlace: column=26, hight=27
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=2, hight=0
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getPhone: 110
addPrize: SUCCESS
makeMember: SUCCESS
isMember: False
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: False
getPhone: 53
getPhone: 132
buyRecord: SUCCESS
getPlace: column=15, hight=0
putOnTop: SUCCESS
isMember: True
addPrize: INVALID_INPUT
putOnTop: SUCCESS
putOnTop: FAILURE
getPlace: column=31, hight=21
getExpenses: DOESNT_EXISTS
getPlace: column=25, hight=0
addPrize: SUCCESS
getPhone: 53
makeMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
addPrize: SUCCESS
isMember: True
addPrize: INVALID_INPUT
getPlace: column=16, hight=0
getExpenses: -86
putOnTop: SUCCESS
isMember: DOESNT_EXISTS
newMonth: SUCCESS
isMember: True
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=1, hight=0
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 53
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: 125
addPrize: SUCCESS
isMember: True
addCostumer: SUCCESS
getPhone: 139
isMember: True
getExpenses: DOESNT_EXISTS
getExpenses: 0
getPlace: INVALID_INPUT
getPhone: 227
isMember: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 168
putOnTop: SUCCESS
getExpenses: -67
isMember: True
getPlace: INVALID_INPUT
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 132
isMember: True
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=16, hight=0
buyRecord: INVALID_INPUT
putOnTop: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getPhone: 125
addCostumer: SUCCESS
isMember: False
isMember: True
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: -64
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 9
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
isMember: True
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: False
buyRecord: SUCCESS
getPlace: column=1, hight=0
getExpenses: INVALID_INPUT
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: 0
addPrize: SUCCESS
getPlace: column=11, hight=0
isMember: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
getPlace: column=1, hight=34
addCostumer: SUCCESS
getPhone: 92
getPhone: 182
getExpenses: DOESNT_EXISTS
getExpenses: -8
addPrize: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
getPhone: 210
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=18, hight=0
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -167
isMember: False
makeMember: SUCCESS
getExpenses: INVALID_INPUT
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: column=22, hight=31
isMember: INVALID_INPUT
getPhone: 92
addCostumer: SUCCESS
getPlace: column=22, hight=50
addCostumer: SUCCESS
getPhone: 36
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
isMember: False
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: column=9, hight=5
addCostumer: INVALID_INPUT
getPhone: 139
getExpenses: DOESNT_EXISTS
isMember: False
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: INVALID_INPUT
addPrize: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
putOnTop: FAILURE
isMember: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: False
makeMember: ALREADY_EXISTS
isMember: False
addPrize: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
isMember: True
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
getPlace: column=20, hight=40
putOnTop: INVALID_INPUT
getPlace: column=18, hight=0
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
getExpenses: -23
getExpenses: -67
makeMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=2, hight=0
getPhone: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: 125
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=20, hight=74
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
isMember: False
buyRecord: SUCCESS
getPhone: 92
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=4, hight=73
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
addPrize: SUCCESS
isMember: True
makeMember: SUCCESS
addCostumer: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=4, hight=161
getPhone: 227
isMember: False
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: -38
putOnTop: SUCCESS
getPlace: INVALID_INPUT
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
isMember: True
getPhone: INVALID_INPUT
getPlace: column=17, hight=0
putOnTop: FAILURE
putOnTop: SUCCESS
getPhone: 20
getPhone: 9
getPlace: column=17, hight=37
addCostumer: SUCCESS
isMember: True
getExpenses: INVALID_INPUT
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: 139
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: column=17, hight=25
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=19, hight=0
putOnTop: FAILURE
addCostumer: INVALID_INPUT
isMember: False
makeMember: INVALID_INPUT
addPrize: SUCCESS
isMember: False
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 43
buyRecord: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: 37
getPhone: 44
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
isMember: False
addCostumer: INVALID_INPUT
makeMember: SUCCESS
buyRecord: SUCCESS
getExpenses: 100
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: INVALID_INPUT
getPhone: 214
getPhone: 27
getPlace: column=17, hight=120
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
isMember: True
makeMember: SUCCESS
addCostumer: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
getExpenses: -310
addPrize: INVALID_INPUT
getExpenses: -146
buyRecord: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=17, hight=37
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 190
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: -114
getPhone: 223
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: -139
getPhone: 186
addPrize: SUCCESS
getPhone: 159
getPlace: column=19, hight=0
addPrize: INVALID_INPUT
getExpenses: -308
makeMember: ALREADY_EXISTS
getExpenses: 0
getPlace: column=17, hight=139
isMember: False
isMember: False
getPlace: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: -42
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 70
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: True
addPrize: INVALID_INPUT
getPlace: column=17, hight=64
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=17, hight=119
getExpenses: -308
getPhone: 248
getPlace: column=17, hight=81
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: -246
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
isMember: False
addCostumer: SUCCESS
addPrize: INVALID_INPUT
isMember: True
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
getExpenses: -108
makeMember: DOESNT_EXISTS
getPlace: INVALID_INPUT
getPlace: column=6, hight=22
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: 0
buyRecord: SUCCESS
getPhone: 221
makeMember: SUCCESS
getExpenses: -76
getPlace: column=19, hight=0
getPhone: 125
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
isMember: False
getPlace: column=2, hight=40
addCostumer: SUCCESS
putOnTop: FAILURE
isMember: True
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 96
getExpenses: -345
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: True
isMember: True
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: INVALID_INPUT
getPhone: INVALID_INPUT
isMember: True
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: INVALID_INPUT
getPhone: 44
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
getPhone: 214
getPlace: column=2, hight=68
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: -171
getPhone: 104
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPhone: INVALID_INPUT
buyRecord: INVALID_INPUT
getPhone: 9
isMember: INVALID_INPUT
putOnTop: INVALID_INPUT
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPlace: column=2, hight=102
getPlace: column=19, hight=0
addCostumer: SUCCESS
getPhone: INVALID_INPUT
putOnTop: SUCCESS
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: -343
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
getExpenses: INVALID_INPUT
getPhone: 203
getExpenses: DOESNT_EXISTS
makeMember: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
getPhone: 110
putOnTop: FAILURE
buyRecord: INVALID_INPUT
getPlace: column=19, hight=100
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 150
putOnTop: FAILURE
getPlace: column=19, hight=193
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: True
getPlace: DOESNT_EXISTS
getPlace: column=19, hight=44
buyRecord: DOESNT_EXISTS
getPhone: 139
addPrize: INVALID_INPUT
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: 16
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=19, hight=215
putOnTop: FAILURE
getExpenses: -170
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=19, hight=152
addCostumer: ALREADY_EXISTS
getExpenses: -392
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
getPlace: column=19, hight=201
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
isMember: False
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: column=19, hight=158
getPhone: 125
getPlace: column=19, hight=118
buyRecord: SUCCESS
getPhone: 49
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
getPhone: 212
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=19, hight=118
makeMember: INVALID_INPUT
isMember: False
getPlace: column=19, hight=76
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: FAILURE
addPrize: INVALID_INPUT
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
addPrize: INVALID_INPUT
isMember: True
isMember: False
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
getPhone: 36
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: -290
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 227
addCostumer: SUCCESS
getPlace: column=19, hight=100
isMember: False
makeMember: SUCCESS
getPhone: 77
addCostumer: ALREADY_EXISTS
getPhone: 167
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
isMember: False
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: True
isMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
addCostumer: SUCCESS
getPhone: 36
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
getPlace: column=19, hight=44
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=19, hight=16
getPlace: column=19, hight=118
isMember: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: 0
buyRecord: SUCCESS
getExpenses: -406
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
isMember: False
buyRecord: SUCCESS
getPlace: column=19, hight=16
putOnTop: FAILURE
makeMember: SUCCESS
getExpenses: -213
getExpenses: INVALID_INPUT
getPhone: INVALID_INPUT
isMember: False
isMember: False
makeMember: SUCCESS
addPrize: INVALID_INPUT
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 44
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=19, hight=16
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
isMember: False
buyRecord: SUCCESS
getExpenses: -474
isMember: False
addPrize: INVALID_INPUT
makeMember: SUCCESS
getPlace: column=19, hight=158
getPhone: 213
buyRecord: SUCCESS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
addPrize: SUCCESS
isMember: True
getExpenses: 0
isMember: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 182
makeMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
getExpenses: INVALID_INPUT
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
getPlace: column=19, hight=56
getPlace: column=19, hight=51
getPhone: 5
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: -195
getPhone: 168
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPhone: 167
putOnTop: FAILURE
putOnTop: FAILURE
getPhone: 207
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: -714
makeMember: SUCCESS
putOnTop: FAILURE
isMember: True
addCostumer: SUCCESS
isMember: True
addPrize: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
isMember: True
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 110
makeMember: SUCCESS
addCostumer: SUCCESS
isMember: True
addCostumer: SUCCESS
getPlace: column=19, hight=176
buyRecord: INVALID_INPUT
isMember: True
addCostumer: SUCCESS
getPhone: 115
getPlace: column=19, hight=16
isMember: True
getExpenses: DOESNT_EXISTS
getPlace: column=19, hight=193
buyRecord: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: INVALID_INPUT
putOnTop: FAILURE
makeMember: SUCCESS
isMember: False
addPrize: SUCCESS
getPlace: column=19, hight=0
isMember: True
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: column=7, hight=0
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -395
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: 207
getPlace: column=19, hight=152
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getPlace: column=19, hight=152
putOnTop: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=19, hight=152
putOnTop: FAILURE
isMember: DOESNT_EXISTS
getPhone: 120
getPhone: 96
getExpenses: DOESNT_EXISTS
makeMember: INVALID_INPUT
putOnTop: FAILURE
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: column=19, hight=19
putOnTop: FAILURE
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 150
makeMember: SUCCESS
getPhone: 210
getPhone: 120
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=19, hight=139
getPhone: 242
buyRecord: SUCCESS
putOnTop: FAILURE
getPhone: 159
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 214
isMember: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -290
getPhone: 159
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPhone: 31
getPlace: column=19, hight=16
getPlace: column=19, hight=226
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
getPhone: 212
putOnTop: FAILURE
putOnTop: FAILURE
addPrize: SUCCESS
