newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 116
isMember: False
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPhone: 116
getPlace: column=0, hight=0
addPrize: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
getPlace: column=1, hight=0
getPlace: column=1, hight=0
putOnTop: SUCCESS
getPlace: column=4, hight=0
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
isMember: False
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 116
getPlace: column=4, hight=0
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=2, hight=7
isMember: False
isMember: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 195
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: INVALID_INPUT
getPhone: 244
makeMember: SUCCESS
isMember: True
getPhone: 104
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getPlace: column=3, hight=0
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: 191
putOnTop: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
getPhone: 218
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
getExpenses: 101
putOnTop: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
isMember: False
getPhone: 68
makeMember: SUCCESS
getExpenses: 76
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: INVALID_INPUT
getPlace: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
getPhone: 104
getPhone: INVALID_INPUT
getExpenses: -126
getExpenses: 102
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: True
addPrize: SUCCESS
isMember: True
isMember: True
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=1, hight=0
getExpenses: DOESNT_EXISTS
getPhone: 68
isMember: INVALID_INPUT
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
getPlace: column=4, hight=8
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 68
addCostumer: SUCCESS
getPhone: 56
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPhone: 56
getExpenses: 102
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 235
makeMember: SUCCESS
getPhone: 19
getPlace: DOESNT_EXISTS
getPhone: 131
getPhone: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
isMember: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
isMember: True
isMember: True
getPlace: column=4, hight=0
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: column=4, hight=1
isMember: False
addPrize: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 218
getPhone: INVALID_INPUT
isMember: True
isMember: True
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: True
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 193
addCostumer: SUCCESS
isMember: INVALID_INPUT
addPrize: SUCCESS
getExpenses: 25
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: INVALID_INPUT
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: False
putOnTop: INVALID_INPUT
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 148
isMember: True
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPhone: 110
addPrize: SUCCESS
getPhone: 235
getExpenses: -123
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
getPlace: column=0, hight=0
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: INVALID_INPUT
isMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=1, hight=8
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
isMember: True
getPhone: 104
addCostumer: SUCCESS
putOnTop: FAILURE
getExpenses: -257
getPlace: INVALID_INPUT
putOnTop: FAILURE
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: column=1, hight=8
isMember: False
getPhone: 19
buyRecord: SUCCESS
getExpenses: -391
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
isMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
isMember: False
getPhone: 110
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
getExpenses: -368
buyRecord: SUCCESS
getPhone: 114
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: -23
putOnTop: SUCCESS
putOnTop: INVALID_INPUT
makeMember: INVALID_INPUT
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 216
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: -336
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: INVALID_INPUT
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
getPhone: 68
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
putOnTop: INVALID_INPUT
getExpenses: INVALID_INPUT
getPlace: column=0, hight=29
putOnTop: FAILURE
getPhone: 193
putOnTop: FAILURE
isMember: INVALID_INPUT
getPlace: INVALID_INPUT
getExpenses: -82
getPlace: column=0, hight=49
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
isMember: True
isMember: DOESNT_EXISTS
isMember: INVALID_INPUT
isMember: True
isMember: True
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: FAILURE
buyRecord: DOESNT_EXISTS
isMember: False
getPlace: column=0, hight=49
getExpenses: 23
putOnTop: INVALID_INPUT
getPlace: column=0, hight=21
isMember: True
makeMember: SUCCESS
getPhone: 114
makeMember: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getExpenses: -24
getExpenses: -394
addCostumer: SUCCESS
getPlace: column=0, hight=49
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 50
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=0, hight=13
isMember: True
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: -600
getExpenses: -76
putOnTop: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: False
isMember: INVALID_INPUT
makeMember: SUCCESS
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
getPhone: 131
getExpenses: -354
buyRecord: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -536
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 148
getExpenses: -536
makeMember: INVALID_INPUT
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 50
getPlace: INVALID_INPUT
getPhone: 114
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
isMember: False
addPrize: INVALID_INPUT
isMember: True
putOnTop: DOESNT_EXISTS
getExpenses: INVALID_INPUT
addPrize: SUCCESS
getExpenses: -111
isMember: False
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: 42
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 105
isMember: False
getExpenses: -52
buyRecord: SUCCESS
isMember: False
makeMember: DOESNT_EXISTS
getExpenses: 0
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=0, hight=21
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPhone: 201
addCostumer: ALREADY_EXISTS
isMember: True
getPhone: 216
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
isMember: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=0, hight=49
getPlace: column=0, hight=22
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 136
makeMember: DOESNT_EXISTS
newMonth: SUCCESS
buyRecord: SUCCESS
getPlace: column=5, hight=0
getPhone: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 18
putOnTop: INVALID_INPUT
getPhone: 56
putOnTop: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
getPlace: column=2, hight=0
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getPhone: 116
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 166
isMember: False
addPrize: SUCCESS
getPhone: INVALID_INPUT
putOnTop: FAILURE
putOnTop: FAILURE
isMember: False
getPhone: DOESNT_EXISTS
getPhone: 79
addPrize: INVALID_INPUT
makeMember: SUCCESS
getPlace: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getExpenses: -51
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=2, hight=18
makeMember: SUCCESS
addPrize: SUCCESS
buyRecord: INVALID_INPUT
makeMember: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
getPhone: 110
getPhone: 198
isMember: False
getPlace: column=4, hight=0
addPrize: SUCCESS
isMember: True
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: 50
getPhone: 44
getPhone: 140
getExpenses: DOESNT_EXISTS
getExpenses: -140
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPhone: 110
getPhone: 136
addCostumer: INVALID_INPUT
getExpenses: -140
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=4, hight=0
isMember: True
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: column=2, hight=18
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 190
isMember: True
buyRecord: SUCCESS
isMember: True
getExpenses: -97
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=4, hight=0
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=2, hight=0
getPhone: 5
isMember: True
addPrize: INVALID_INPUT
getPlace: column=1, hight=0
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=1, hight=0
getPlace: INVALID_INPUT
getPhone: 218
makeMember: DOESNT_EXISTS
getPhone: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: True
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: FAILURE
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 73
addPrize: INVALID_INPUT
getExpenses: -65
putOnTop: FAILURE
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
getPhone: 19
addPrize: SUCCESS
getExpenses: -145
putOnTop: FAILURE
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
getExpenses: -97
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
isMember: DOESNT_EXISTS
putOnTop: FAILURE
isMember: False
putOnTop: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
makeMember: INVALID_INPUT
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: -116
getExpenses: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
buyRecord: SUCCESS
isMember: True
isMember: False
getExpenses: DOESNT_EXISTS
getExpenses: -114
isMember: True
getPlace: INVALID_INPUT
getExpenses: -132
isMember: False
addCostumer: SUCCESS
putOnTop: FAILURE
isMember: False
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
isMember: True
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
getPhone: 50
putOnTop: DOESNT_EXISTS
getExpenses: -15
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 19
getPhone: 225
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: -114
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
addPrize: INVALID_INPUT
isMember: INVALID_INPUT
getExpenses: -192
addPrize: INVALID_INPUT
putOnTop: FAILURE
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: 0
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
getPhone: 204
getPhone: 75
getExpenses: 20
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: -109
getExpenses: DOESNT_EXISTS
getPlace: column=2, hight=35
makeMember: SUCCESS
putOnTop: FAILURE
getPhone: 119
getPhone: 134
isMember: True
getPhone: 68
isMember: False
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
getPhone: 53
buyRecord: SUCCESS
getPlace: column=2, hight=53
buyRecord: SUCCESS
getPlace: column=2, hight=57
putOnTop: FAILURE
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: 100
getPhone: 52
addCostumer: SUCCESS
getPlace: INVALID_INPUT
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: -189
putOnTop: DOESNT_EXISTS
getExpenses: -198
getExpenses: -189
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
getPlace: INVALID_INPUT
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: INVALID_INPUT
makeMember: DOESNT_EXISTS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
makeMember: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getPhone: 149
addPrize: SUCCESS
isMember: False
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPhone: 68
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
isMember: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
isMember: True
putOnTop: INVALID_INPUT
addPrize: SUCCESS
getPhone: 213
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: -215
getPlace: DOESNT_EXISTS
getPhone: 191
getExpenses: 100
getExpenses: DOESNT_EXISTS
getExpenses: -133
addPrize: SUCCESS
isMember: True
buyRecord: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPhone: 215
getPhone: 235
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=2, hight=18
makeMember: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: INVALID_INPUT
isMember: False
addCostumer: INVALID_INPUT
getPhone: 79
getPlace: column=2, hight=28
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=2, hight=35
getPlace: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: -325
getExpenses: INVALID_INPUT
isMember: True
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getExpenses: -342
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 116
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: column=2, hight=57
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 52
isMember: False
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: False
getPlace: DOESNT_EXISTS
getExpenses: -420
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 149
makeMember: ALREADY_EXISTS
getPlace: column=2, hight=53
getPlace: column=2, hight=18
putOnTop: DOESNT_EXISTS
isMember: True
isMember: True
isMember: True
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 143
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
isMember: True
getPlace: column=2, hight=0
getExpenses: DOESNT_EXISTS
buyRecord: INVALID_INPUT
getPlace: column=2, hight=53
getPhone: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: INVALID_INPUT
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: column=2, hight=28
addPrize: INVALID_INPUT
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: INVALID_INPUT
getPlace: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: 39
makeMember: ALREADY_EXISTS
getPhone: 180
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
isMember: False
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
isMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 94
isMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: True
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
addPrize: SUCCESS
putOnTop: FAILURE
isMember: DOESNT_EXISTS
isMember: True
addPrize: SUCCESS
isMember: True
addCostumer: ALREADY_EXISTS
isMember: True
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 39
isMember: True
isMember: INVALID_INPUT
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 246
makeMember: SUCCESS
getPlace: column=2, hight=28
addPrize: INVALID_INPUT
getPhone: DOESNT_EXISTS
getPlace: column=2, hight=35
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=2, hight=0
isMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: column=2, hight=0
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
newMonth: SUCCESS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: True
getPhone: 223
getExpenses: 0
isMember: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
getPhone: 175
isMember: True
isMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 70
isMember: INVALID_INPUT
buyRecord: INVALID_INPUT
putOnTop: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 148
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=14, hight=0
makeMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=15, hight=0
getPhone: DOESNT_EXISTS
getExpenses: -86
putOnTop: SUCCESS
getExpenses: 0
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: column=3, hight=0
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
getPhone: INVALID_INPUT
putOnTop: SUCCESS
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: False
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=26, hight=0
buyRecord: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
