newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
getExpenses: 0
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: 69
addPrize: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=8, hight=0
getExpenses: DOESNT_EXISTS
getExpenses: -59
addCostumer: SUCCESS
getPlace: column=8, hight=0
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 223
isMember: True
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
getPhone: INVALID_INPUT
putOnTop: INVALID_INPUT
isMember: False
getPlace: column=14, hight=0
addCostumer: SUCCESS
getPhone: 223
addPrize: INVALID_INPUT
makeMember: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: True
getPlace: INVALID_INPUT
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
getPlace: column=9, hight=0
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
getExpenses: -184
putOnTop: DOESNT_EXISTS
getPlace: column=1, hight=0
addCostumer: INVALID_INPUT
makeMember: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=4, hight=0
addPrize: SUCCESS
isMember: True
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=5, hight=0
getPlace: column=2, hight=0
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 244
getExpenses: -25
makeMember: SUCCESS
addPrize: SUCCESS
addCostumer: INVALID_INPUT
getPhone: 214
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=17, hight=0
isMember: DOESNT_EXISTS
putOnTop: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: -36
buyRecord: SUCCESS
getPhone: 244
addPrize: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
isMember: True
isMember: False
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: False
isMember: False
buyRecord: SUCCESS
getPlace: column=13, hight=21
isMember: False
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
isMember: True
putOnTop: DOESNT_EXISTS
getPlace: column=24, hight=21
isMember: True
getPlace: column=11, hight=0
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
isMember: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
putOnTop: SUCCESS
getPhone: 244
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=11, hight=0
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: INVALID_INPUT
addCostumer: SUCCESS
getPhone: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=11, hight=0
addCostumer: SUCCESS
makeMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: FAILURE
putOnTop: SUCCESS
buyRecord: DOESNT_EXISTS
getPhone: 54
isMember: False
getPhone: 214
putOnTop: SUCCESS
isMember: True
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: -201
makeMember: SUCCESS
getPlace: column=17, hight=25
buyRecord: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: 0
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=7, hight=0
isMember: False
addPrize: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 214
getPlace: column=14, hight=0
getPlace: column=9, hight=11
getPhone: 211
buyRecord: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
getPhone: 223
getPhone: 113
getExpenses: -139
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
getPhone: 211
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: 54
isMember: True
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
getPlace: column=24, hight=65
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getPhone: 120
putOnTop: SUCCESS
buyRecord: SUCCESS
getPlace: column=15, hight=78
makeMember: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
getPhone: INVALID_INPUT
isMember: True
getExpenses: -276
getPhone: 113
addCostumer: SUCCESS
getPlace: column=13, hight=17
putOnTop: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
isMember: True
getPlace: column=13, hight=142
addCostumer: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
getPhone: 93
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: column=13, hight=161
addCostumer: SUCCESS
putOnTop: FAILURE
getPlace: column=13, hight=39
putOnTop: SUCCESS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
getExpenses: 0
addPrize: INVALID_INPUT
getPlace: column=25, hight=0
addCostumer: SUCCESS
getPhone: 113
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: INVALID_INPUT
getPhone: 120
getPhone: 113
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 214
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getExpenses: -176
buyRecord: SUCCESS
getExpenses: -459
addCostumer: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: True
isMember: False
putOnTop: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: 0
putOnTop: FAILURE
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getPhone: 171
buyRecord: DOESNT_EXISTS
isMember: False
getExpenses: 0
addCostumer: SUCCESS
isMember: True
putOnTop: FAILURE
getPhone: 214
getPlace: column=2, hight=0
buyRecord: SUCCESS
isMember: False
addCostumer: SUCCESS
isMember: False
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: 0
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getPlace: column=7, hight=86
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: INVALID_INPUT
isMember: False
getPhone: 128
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
isMember: True
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 211
isMember: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 69
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: -283
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: INVALID_INPUT
getPhone: 5
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getExpenses: -486
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: INVALID_INPUT
isMember: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=2, hight=151
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: True
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
makeMember: SUCCESS
getExpenses: -147
getPlace: column=2, hight=29
getPhone: 147
getPhone: 106
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
getPlace: column=2, hight=187
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 111
getPhone: 174
getPhone: 69
getExpenses: DOESNT_EXISTS
getPhone: 25
isMember: True
getPhone: 42
addPrize: SUCCESS
makeMember: INVALID_INPUT
getPlace: column=11, hight=16
getExpenses: -247
makeMember: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: False
addPrize: INVALID_INPUT
getPhone: DOESNT_EXISTS
getPlace: column=14, hight=31
isMember: True
putOnTop: SUCCESS
getPhone: 103
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
getPhone: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 93
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 145
putOnTop: INVALID_INPUT
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
getPlace: column=20, hight=123
getPlace: column=20, hight=158
makeMember: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getExpenses: -434
getPhone: 113
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
isMember: True
addPrize: INVALID_INPUT
getPhone: 137
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: True
putOnTop: SUCCESS
makeMember: DOESNT_EXISTS
getExpenses: INVALID_INPUT
isMember: True
addPrize: SUCCESS
getPlace: column=11, hight=207
getPhone: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: column=11, hight=29
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
getPlace: column=11, hight=229
buyRecord: SUCCESS
getExpenses: -315
isMember: False
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=11, hight=247
isMember: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
newMonth: SUCCESS
isMember: False
getPlace: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 244
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
makeMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
getPhone: 42
getPhone: 111
addPrize: SUCCESS
getExpenses: -30
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
getPhone: 7
getPlace: column=17, hight=0
putOnTop: SUCCESS
getPhone: 186
isMember: False
addPrize: INVALID_INPUT
isMember: False
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 186
putOnTop: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 244
getExpenses: DOESNT_EXISTS
getPhone: 148
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: INVALID_INPUT
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=7, hight=8
putOnTop: SUCCESS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
getExpenses: -52
putOnTop: DOESNT_EXISTS
getPlace: column=8, hight=0
getPhone: 78
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 93
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: INVALID_INPUT
isMember: True
getPlace: column=3, hight=24
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: -87
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 111
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
getPlace: column=15, hight=0
buyRecord: INVALID_INPUT
makeMember: SUCCESS
getExpenses: -65
buyRecord: SUCCESS
getExpenses: -87
addPrize: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
isMember: False
makeMember: INVALID_INPUT
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: INVALID_INPUT
getExpenses: -215
isMember: False
buyRecord: SUCCESS
isMember: INVALID_INPUT
isMember: False
putOnTop: INVALID_INPUT
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 72
isMember: False
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: -215
buyRecord: SUCCESS
getPhone: 153
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=8, hight=0
isMember: True
addPrize: SUCCESS
getPhone: 7
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
isMember: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: False
makeMember: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 211
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getPlace: column=12, hight=27
getPlace: column=1, hight=0
addPrize: SUCCESS
getPhone: 7
getExpenses: DOESNT_EXISTS
getPlace: column=12, hight=0
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: INVALID_INPUT
getPhone: 154
getPhone: 160
getPlace: column=12, hight=0
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=12, hight=10
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
getPhone: 142
getExpenses: 0
buyRecord: SUCCESS
getExpenses: -339
isMember: False
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
getPhone: 154
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: column=7, hight=0
getExpenses: INVALID_INPUT
getPhone: 27
isMember: False
getPhone: 147
makeMember: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=4, hight=0
putOnTop: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: -499
addCostumer: SUCCESS
getPlace: column=8, hight=0
putOnTop: SUCCESS
getPhone: 211
buyRecord: SUCCESS
isMember: INVALID_INPUT
buyRecord: INVALID_INPUT
addPrize: SUCCESS
putOnTop: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPhone: 54
isMember: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=4, hight=31
getPlace: column=21, hight=0
getPlace: column=19, hight=16
buyRecord: SUCCESS
isMember: True
makeMember: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getPlace: column=4, hight=4
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
makeMember: SUCCESS
getPhone: 113
addCostumer: SUCCESS
getPhone: 153
getPlace: column=19, hight=33
isMember: True
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
isMember: True
isMember: False
getExpenses: -675
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: INVALID_INPUT
putOnTop: FAILURE
getPhone: 106
getPhone: 218
addCostumer: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
getPhone: 187
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getPhone: 211
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: 0
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
isMember: True
getExpenses: -659
isMember: DOESNT_EXISTS
getPhone: 0
putOnTop: SUCCESS
getPlace: column=7, hight=0
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
putOnTop: INVALID_INPUT
addPrize: SUCCESS
getExpenses: -384
addCostumer: INVALID_INPUT
makeMember: DOESNT_EXISTS
isMember: False
getPhone: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
isMember: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: False
putOnTop: FAILURE
isMember: False
putOnTop: SUCCESS
putOnTop: FAILURE
getPlace: column=19, hight=70
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: True
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: column=19, hight=70
makeMember: SUCCESS
getPlace: column=19, hight=70
putOnTop: FAILURE
isMember: False
getPlace: column=19, hight=182
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: False
isMember: True
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: INVALID_INPUT
putOnTop: FAILURE
getExpenses: -92
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -683
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: -683
buyRecord: SUCCESS
getPlace: column=7, hight=8
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: True
isMember: False
getPhone: 22
putOnTop: FAILURE
getPhone: 223
addPrize: SUCCESS
isMember: True
isMember: False
isMember: False
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=19, hight=66
putOnTop: FAILURE
getPlace: column=19, hight=155
putOnTop: FAILURE
makeMember: INVALID_INPUT
getPlace: column=7, hight=0
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
isMember: False
getPlace: column=19, hight=164
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=19, hight=136
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: -562
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
getPhone: 235
getPlace: column=19, hight=179
getPlace: column=19, hight=155
putOnTop: INVALID_INPUT
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
getPhone: 103
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=19, hight=155
addPrize: SUCCESS
getPhone: INVALID_INPUT
makeMember: INVALID_INPUT
getPlace: column=19, hight=112
getPlace: column=19, hight=214
getPhone: 16
addCostumer: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
isMember: False
addCostumer: INVALID_INPUT
makeMember: INVALID_INPUT
getPlace: column=19, hight=182
getExpenses: -1116
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: column=19, hight=48
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getPlace: column=19, hight=155
isMember: False
getPlace: column=19, hight=66
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 184
buyRecord: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=19, hight=48
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: INVALID_INPUT
isMember: False
getExpenses: DOESNT_EXISTS
getPlace: column=19, hight=70
getPhone: 123
buyRecord: SUCCESS
putOnTop: FAILURE
getExpenses: INVALID_INPUT
getPhone: INVALID_INPUT
putOnTop: DOESNT_EXISTS
buyRecord: INVALID_INPUT
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
getExpenses: -942
putOnTop: FAILURE
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
getExpenses: INVALID_INPUT
makeMember: SUCCESS
getPlace: column=19, hight=155
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: column=19, hight=16
makeMember: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=7, hight=0
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=19, hight=0
putOnTop: FAILURE
