newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
isMember: False
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: 100
putOnTop: SUCCESS
addPrize: SUCCESS
isMember: False
addPrize: SUCCESS
isMember: True
makeMember: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 69
getExpenses: INVALID_INPUT
getExpenses: -57
buyRecord: SUCCESS
getPlace: column=20, hight=0
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 110
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: INVALID_INPUT
isMember: True
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 79
getExpenses: INVALID_INPUT
addCostumer: INVALID_INPUT
getPlace: column=9, hight=0
getExpenses: 92
addPrize: INVALID_INPUT
getPlace: column=2, hight=20
getExpenses: DOESNT_EXISTS
getPlace: column=6, hight=0
getExpenses: 43
getPlace: column=14, hight=0
addCostumer: SUCCESS
getPhone: 69
getExpenses: 92
getPhone: 176
addPrize: SUCCESS
getPlace: column=19, hight=0
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: False
makeMember: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: SUCCESS
isMember: True
makeMember: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=0, hight=25
putOnTop: SUCCESS
getPlace: column=24, hight=0
getExpenses: DOESNT_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
getPlace: column=13, hight=0
addPrize: INVALID_INPUT
getExpenses: -110
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 79
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: 110
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: 0
getPlace: column=4, hight=0
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
isMember: False
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=24, hight=0
addCostumer: SUCCESS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
getPlace: column=6, hight=0
addPrize: SUCCESS
makeMember: INVALID_INPUT
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
isMember: False
isMember: True
buyRecord: INVALID_INPUT
putOnTop: SUCCESS
putOnTop: SUCCESS
getPlace: column=21, hight=0
isMember: False
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: -53
getPhone: 203
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: column=14, hight=0
addCostumer: SUCCESS
putOnTop: SUCCESS
getPhone: 235
getExpenses: 0
isMember: INVALID_INPUT
getPlace: column=3, hight=1
getPlace: column=8, hight=0
getExpenses: 0
getPlace: column=15, hight=0
putOnTop: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=20, hight=0
getPlace: column=14, hight=37
isMember: DOESNT_EXISTS
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=9, hight=0
putOnTop: SUCCESS
addPrize: INVALID_INPUT
getExpenses: 0
getPhone: 8
isMember: INVALID_INPUT
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=14, hight=75
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 210
buyRecord: SUCCESS
addPrize: SUCCESS
getPlace: column=16, hight=0
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
isMember: False
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=3, hight=0
getPhone: 183
getExpenses: -326
getPhone: 203
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=4, hight=0
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
getPhone: 181
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 35
addCostumer: SUCCESS
isMember: False
putOnTop: SUCCESS
makeMember: SUCCESS
getExpenses: -84
getPhone: 110
getPhone: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPhone: INVALID_INPUT
makeMember: SUCCESS
getPhone: INVALID_INPUT
getPlace: column=3, hight=0
addCostumer: SUCCESS
getPlace: column=20, hight=112
getPhone: 148
makeMember: ALREADY_EXISTS
isMember: False
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=20, hight=119
addPrize: INVALID_INPUT
makeMember: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
isMember: True
isMember: False
makeMember: ALREADY_EXISTS
getPlace: column=20, hight=87
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
putOnTop: SUCCESS
getPlace: column=20, hight=63
addCostumer: SUCCESS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
getPhone: 183
putOnTop: SUCCESS
addCostumer: SUCCESS
getPhone: 39
makeMember: ALREADY_EXISTS
isMember: False
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=13, hight=0
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getExpenses: 0
makeMember: ALREADY_EXISTS
getExpenses: 77
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPhone: 211
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: SUCCESS
getPlace: column=2, hight=66
addCostumer: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
buyRecord: DOESNT_EXISTS
isMember: True
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 16
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 183
getPlace: column=2, hight=164
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: True
isMember: True
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPlace: INVALID_INPUT
addPrize: SUCCESS
getExpenses: INVALID_INPUT
getPhone: 115
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
buyRecord: DOESNT_EXISTS
getPhone: 44
makeMember: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPhone: 152
getPhone: 8
addCostumer: SUCCESS
isMember: True
getPhone: 116
addPrize: SUCCESS
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getPlace: column=2, hight=133
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getPlace: column=2, hight=0
getPlace: column=2, hight=48
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: INVALID_INPUT
isMember: False
getPlace: column=2, hight=195
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -159
addPrize: SUCCESS
isMember: True
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=2, hight=185
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPlace: INVALID_INPUT
isMember: True
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: column=10, hight=0
makeMember: ALREADY_EXISTS
isMember: True
isMember: True
getPhone: 39
isMember: True
isMember: False
makeMember: SUCCESS
getExpenses: -277
addPrize: SUCCESS
putOnTop: FAILURE
isMember: True
makeMember: ALREADY_EXISTS
isMember: False
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
addCostumer: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: False
getPlace: column=2, hight=158
getExpenses: DOESNT_EXISTS
getPhone: INVALID_INPUT
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
newMonth: SUCCESS
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
getPlace: column=15, hight=0
isMember: True
getPhone: 87
addCostumer: SUCCESS
getPlace: column=1, hight=0
getPhone: 239
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPlace: column=9, hight=0
buyRecord: SUCCESS
addCostumer: INVALID_INPUT
getPhone: 39
getExpenses: INVALID_INPUT
getPlace: column=4, hight=0
putOnTop: SUCCESS
getPhone: 35
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: False
getPlace: column=25, hight=0
getPhone: 48
getExpenses: -7
makeMember: SUCCESS
getPlace: column=13, hight=0
getPlace: INVALID_INPUT
isMember: True
getExpenses: -7
putOnTop: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: 35
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
getExpenses: -7
getExpenses: -7
isMember: True
addPrize: SUCCESS
putOnTop: SUCCESS
getExpenses: -20
getPhone: 35
putOnTop: SUCCESS
getPhone: 8
newMonth: SUCCESS
makeMember: SUCCESS
isMember: INVALID_INPUT
getPlace: column=6, hight=0
addPrize: INVALID_INPUT
putOnTop: SUCCESS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 181
makeMember: INVALID_INPUT
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: INVALID_INPUT
putOnTop: FAILURE
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
getPhone: 182
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: INVALID_INPUT
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
isMember: False
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: -22
putOnTop: SUCCESS
getPlace: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
isMember: False
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: column=3, hight=8
getPlace: INVALID_INPUT
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: -1
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=9, hight=34
buyRecord: SUCCESS
getPlace: column=2, hight=0
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: -22
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getExpenses: -22
isMember: True
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
isMember: False
getPhone: 176
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: INVALID_INPUT
getPlace: column=10, hight=0
isMember: True
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
isMember: False
buyRecord: SUCCESS
isMember: True
addCostumer: SUCCESS
getExpenses: -1
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
addPrize: INVALID_INPUT
getPhone: 85
getExpenses: 0
getPlace: column=7, hight=39
getExpenses: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
getPlace: column=10, hight=0
makeMember: SUCCESS
addPrize: INVALID_INPUT
getPhone: 79
addCostumer: SUCCESS
getPhone: 190
addCostumer: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
getPlace: column=4, hight=0
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
isMember: True
addPrize: INVALID_INPUT
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: SUCCESS
getExpenses: -11
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
getPhone: 102
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
isMember: False
getPhone: 120
addCostumer: SUCCESS
getPlace: INVALID_INPUT
isMember: True
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
isMember: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: SUCCESS
getPlace: column=2, hight=0
putOnTop: FAILURE
getPhone: 13
isMember: True
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
getPlace: column=0, hight=0
isMember: False
getExpenses: -53
makeMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
isMember: False
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: -33
makeMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 68
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: False
getPhone: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=4, hight=56
addPrize: INVALID_INPUT
getExpenses: 67
isMember: True
addCostumer: ALREADY_EXISTS
getPlace: column=0, hight=0
putOnTop: FAILURE
putOnTop: FAILURE
isMember: True
getPhone: 190
getPlace: column=4, hight=0
isMember: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
isMember: True
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: True
putOnTop: FAILURE
buyRecord: SUCCESS
isMember: False
isMember: True
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: -128
getPhone: 168
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPhone: 71
getPhone: 145
getPhone: 87
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
isMember: False
isMember: False
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=4, hight=36
addPrize: SUCCESS
getPhone: 210
buyRecord: SUCCESS
getExpenses: 63
putOnTop: DOESNT_EXISTS
getPlace: column=4, hight=70
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
getPhone: 94
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 141
addPrize: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: False
isMember: True
addPrize: INVALID_INPUT
buyRecord: INVALID_INPUT
getPlace: column=4, hight=70
buyRecord: SUCCESS
addPrize: INVALID_INPUT
makeMember: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
getPhone: 241
getExpenses: -474
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: True
getPlace: column=4, hight=70
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
getPhone: 132
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
getPhone: 210
getPlace: column=4, hight=28
getExpenses: -490
putOnTop: FAILURE
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
isMember: False
isMember: True
makeMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: 179
buyRecord: SUCCESS
getPhone: 234
getPhone: DOESNT_EXISTS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
getPlace: DOESNT_EXISTS
getExpenses: -579
getExpenses: -398
isMember: False
getPlace: DOESNT_EXISTS
getPhone: 68
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: INVALID_INPUT
buyRecord: SUCCESS
getPhone: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: 141
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 216
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -218
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
putOnTop: FAILURE
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 44
getPhone: 110
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: True
isMember: False
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=4, hight=83
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
isMember: True
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: INVALID_INPUT
getPhone: 144
getExpenses: DOESNT_EXISTS
isMember: False
getPhone: 102
getExpenses: -375
getExpenses: DOESNT_EXISTS
getExpenses: -414
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -210
addPrize: SUCCESS
makeMember: INVALID_INPUT
isMember: True
getPlace: column=4, hight=72
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: True
getPhone: 133
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: INVALID_INPUT
buyRecord: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getPlace: column=4, hight=20
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=4, hight=70
getPhone: INVALID_INPUT
makeMember: INVALID_INPUT
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 219
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: FAILURE
getExpenses: -362
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
getExpenses: INVALID_INPUT
isMember: False
getPlace: column=0, hight=0
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: column=4, hight=56
isMember: False
addPrize: SUCCESS
getPhone: 58
isMember: True
isMember: INVALID_INPUT
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: column=0, hight=0
addPrize: SUCCESS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=4, hight=81
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: INVALID_INPUT
getPhone: 94
buyRecord: INVALID_INPUT
isMember: False
isMember: False
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 5
addCostumer: SUCCESS
isMember: True
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
isMember: True
getExpenses: -142
isMember: INVALID_INPUT
putOnTop: FAILURE
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
addCostumer: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
isMember: True
getPhone: 16
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: False
getPhone: 25
addPrize: INVALID_INPUT
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getPlace: column=4, hight=83
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=4, hight=20
addCostumer: SUCCESS
getExpenses: -596
isMember: False
putOnTop: DOESNT_EXISTS
getPhone: 183
getPhone: 15
isMember: False
makeMember: ALREADY_EXISTS
getPlace: column=4, hight=56
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
buyRecord: INVALID_INPUT
getPhone: 145
isMember: True
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 220
buyRecord: INVALID_INPUT
getPhone: 133
getExpenses: DOESNT_EXISTS
getPlace: column=4, hight=81
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
isMember: INVALID_INPUT
getExpenses: -1197
isMember: True
addCostumer: ALREADY_EXISTS
getPhone: 201
getExpenses: -484
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
isMember: False
