newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
putOnTop: SUCCESS
makeMember: DOESNT_EXISTS
isMember: False
getPlace: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPhone: 103
isMember: False
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: False
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: INVALID_INPUT
getPhone: 48
getPhone: 110
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
buyRecord: SUCCESS
isMember: True
makeMember: DOESNT_EXISTS
putOnTop: SUCCESS
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: INVALID_INPUT
isMember: INVALID_INPUT
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: INVALID_INPUT
isMember: False
getExpenses: 0
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 14
addPrize: INVALID_INPUT
isMember: False
getPlace: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: True
addPrize: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=2, hight=4
putOnTop: SUCCESS
getPhone: 215
getExpenses: 0
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 15
putOnTop: INVALID_INPUT
getExpenses: 0
getPlace: column=0, hight=0
makeMember: SUCCESS
getPhone: 15
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
isMember: True
makeMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPhone: 103
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
getPhone: 48
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: 6
getPhone: 14
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: True
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=5, hight=11
addCostumer: SUCCESS
isMember: INVALID_INPUT
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=5, hight=25
getExpenses: DOESNT_EXISTS
isMember: True
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: 103
makeMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
isMember: False
isMember: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: INVALID_INPUT
putOnTop: FAILURE
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 172
isMember: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: 74
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: False
getPlace: column=5, hight=25
addPrize: INVALID_INPUT
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
isMember: False
getExpenses: -9
isMember: True
getPhone: 172
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: True
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getPhone: 140
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
addPrize: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 51
getPlace: column=0, hight=0
putOnTop: FAILURE
getPhone: 86
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
makeMember: ALREADY_EXISTS
getPhone: 70
addPrize: SUCCESS
putOnTop: FAILURE
buyRecord: INVALID_INPUT
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 215
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: INVALID_INPUT
isMember: False
isMember: False
getPhone: 48
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 70
makeMember: ALREADY_EXISTS
getPhone: 51
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: INVALID_INPUT
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
getExpenses: 80
isMember: True
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
getPhone: 103
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=5, hight=0
getExpenses: INVALID_INPUT
getPhone: 51
getPlace: DOESNT_EXISTS
getPhone: 22
isMember: True
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getExpenses: -521
getPlace: column=5, hight=0
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getPhone: 81
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=5, hight=29
makeMember: SUCCESS
getPhone: 211
getExpenses: DOESNT_EXISTS
getPhone: 247
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: -443
isMember: DOESNT_EXISTS
getPhone: 44
buyRecord: DOESNT_EXISTS
getPhone: 22
getPlace: DOESNT_EXISTS
getPhone: 215
isMember: True
getPhone: 64
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
getPhone: 215
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
isMember: True
buyRecord: SUCCESS
isMember: False
getPlace: column=0, hight=0
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 20
addCostumer: ALREADY_EXISTS
getPhone: INVALID_INPUT
getPhone: 198
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 70
getExpenses: DOESNT_EXISTS
isMember: True
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPlace: INVALID_INPUT
putOnTop: INVALID_INPUT
getPlace: column=5, hight=25
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -616
addPrize: SUCCESS
addPrize: SUCCESS
isMember: True
makeMember: SUCCESS
makeMember: SUCCESS
getPlace: column=5, hight=29
getPhone: INVALID_INPUT
getPhone: 198
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
isMember: True
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 101
getPhone: 14
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
isMember: True
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 193
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -294
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
isMember: False
isMember: True
getPlace: DOESNT_EXISTS
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: DOESNT_EXISTS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: 200
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
isMember: True
getExpenses: -131
getExpenses: -702
getPhone: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPlace: column=0, hight=0
addPrize: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 81
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=0, hight=0
addPrize: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
getPhone: 110
addPrize: SUCCESS
getExpenses: -266
getPhone: 70
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 22
isMember: False
isMember: False
getExpenses: -70
isMember: True
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
isMember: INVALID_INPUT
getPhone: 93
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
isMember: False
getPlace: column=5, hight=29
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
makeMember: ALREADY_EXISTS
getExpenses: -972
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: 245
getPhone: 211
getExpenses: DOESNT_EXISTS
getPlace: column=5, hight=0
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
makeMember: DOESNT_EXISTS
getExpenses: INVALID_INPUT
isMember: True
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
isMember: True
isMember: False
isMember: False
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getPhone: 58
putOnTop: DOESNT_EXISTS
getExpenses: INVALID_INPUT
addCostumer: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
getPhone: 64
isMember: False
putOnTop: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPhone: 207
isMember: False
getExpenses: DOESNT_EXISTS
isMember: True
getExpenses: 80
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: -131
makeMember: SUCCESS
getPhone: 143
getPhone: INVALID_INPUT
isMember: False
getPhone: 43
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: INVALID_INPUT
putOnTop: FAILURE
getPhone: 112
getPlace: column=0, hight=31
getExpenses: DOESNT_EXISTS
isMember: False
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: -384
addPrize: INVALID_INPUT
getPhone: 58
addCostumer: SUCCESS
addPrize: INVALID_INPUT
isMember: True
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 25
buyRecord: SUCCESS
getPlace: column=0, hight=20
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=0, hight=41
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
getPlace: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 103
getPlace: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
getPhone: 25
addCostumer: SUCCESS
isMember: True
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: INVALID_INPUT
getPlace: column=0, hight=20
isMember: False
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=0, hight=20
isMember: False
getPhone: 64
makeMember: SUCCESS
getPlace: INVALID_INPUT
getPhone: 147
addCostumer: SUCCESS
addCostumer: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
getPhone: 14
isMember: True
makeMember: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
isMember: INVALID_INPUT
addPrize: SUCCESS
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 15
isMember: True
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
putOnTop: INVALID_INPUT
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=0, hight=0
getExpenses: 80
addPrize: SUCCESS
isMember: False
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=0, hight=31
getPlace: INVALID_INPUT
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: INVALID_INPUT
getPhone: 70
getExpenses: -73
getPhone: DOESNT_EXISTS
getPhone: 4
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: DOESNT_EXISTS
isMember: True
putOnTop: DOESNT_EXISTS
isMember: True
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
getPlace: column=0, hight=31
getPlace: DOESNT_EXISTS
getPlace: column=0, hight=20
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
isMember: False
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: -182
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
isMember: False
getExpenses: -714
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
getPhone: 146
getPhone: 80
isMember: False
getPhone: 235
buyRecord: SUCCESS
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
getPlace: DOESNT_EXISTS
isMember: True
addPrize: SUCCESS
buyRecord: INVALID_INPUT
putOnTop: INVALID_INPUT
getExpenses: INVALID_INPUT
getPlace: column=0, hight=0
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
isMember: True
getPlace: column=0, hight=31
getPlace: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
makeMember: INVALID_INPUT
putOnTop: FAILURE
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPhone: 58
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: True
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
getExpenses: 0
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: True
isMember: False
getPhone: 200
isMember: False
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: -1258
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=0, hight=31
addCostumer: ALREADY_EXISTS
getPlace: column=0, hight=0
putOnTop: INVALID_INPUT
putOnTop: FAILURE
isMember: False
getPlace: DOESNT_EXISTS
getPhone: 186
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: 116
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getExpenses: -242
addPrize: INVALID_INPUT
isMember: True
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 188
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: 143
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 147
getExpenses: -331
makeMember: INVALID_INPUT
getPlace: column=0, hight=20
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -1449
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getPhone: 93
getPhone: 14
getPlace: column=0, hight=41
buyRecord: SUCCESS
isMember: False
getPhone: 200
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
putOnTop: FAILURE
addPrize: SUCCESS
addCostumer: SUCCESS
getExpenses: 4
getPhone: 81
isMember: False
addPrize: SUCCESS
getPhone: 188
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: -342
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
getPlace: column=0, hight=41
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=0, hight=41
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
isMember: False
getPhone: INVALID_INPUT
getPhone: 119
getPlace: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=0, hight=41
buyRecord: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
isMember: DOESNT_EXISTS
isMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
getExpenses: INVALID_INPUT
makeMember: DOESNT_EXISTS
isMember: False
addCostumer: ALREADY_EXISTS
getPhone: 14
getPlace: column=0, hight=31
getPhone: 4
addPrize: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: FAILURE
isMember: False
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: -285
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: -751
getPlace: INVALID_INPUT
makeMember: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: -1006
addPrize: SUCCESS
getPhone: 81
getPlace: INVALID_INPUT
isMember: False
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: -229
buyRecord: SUCCESS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: column=0, hight=49
getExpenses: 0
putOnTop: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getPhone: 148
getPlace: column=0, hight=45
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: 119
getPhone: 247
makeMember: SUCCESS
getPhone: 136
getPhone: 198
getExpenses: -318
buyRecord: SUCCESS
isMember: False
isMember: True
isMember: True
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: -730
buyRecord: DOESNT_EXISTS
getPhone: 147
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getPhone: 89
putOnTop: FAILURE
getPhone: 50
makeMember: SUCCESS
getPhone: 247
makeMember: INVALID_INPUT
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: -1470
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: INVALID_INPUT
getPhone: 58
getExpenses: -226
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addCostumer: SUCCESS
getPhone: 204
addCostumer: ALREADY_EXISTS
isMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPhone: 197
putOnTop: FAILURE
getPhone: 58
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: 230
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 48
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=0, hight=0
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
makeMember: INVALID_INPUT
isMember: False
addPrize: SUCCESS
makeMember: SUCCESS
getPlace: INVALID_INPUT
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
isMember: True
getPlace: column=0, hight=49
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 93
getPhone: 44
getPlace: column=0, hight=31
getPhone: 44
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 247
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
getPhone: 43
addPrize: SUCCESS
putOnTop: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: column=0, hight=20
addPrize: SUCCESS
