newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
getExpenses: 0
getPhone: 206
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: True
isMember: DOESNT_EXISTS
getPhone: 206
putOnTop: SUCCESS
makeMember: SUCCESS
getPlace: column=25, hight=0
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
makeMember: SUCCESS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=5, hight=0
addCostumer: SUCCESS
makeMember: SUCCESS
getPhone: 226
isMember: False
putOnTop: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
getPhone: 206
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=0, hight=0
addCostumer: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
getExpenses: 0
isMember: True
getPlace: column=2, hight=0
getPhone: 226
isMember: False
addPrize: SUCCESS
isMember: DOESNT_EXISTS
getExpenses: 0
getExpenses: DOESNT_EXISTS
getPhone: 230
buyRecord: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: 0
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 230
getPlace: column=28, hight=37
isMember: True
getPlace: column=16, hight=30
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: 0
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: 154
addPrize: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=18, hight=0
getExpenses: 41
getPhone: 206
putOnTop: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=13, hight=0
getExpenses: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: False
buyRecord: SUCCESS
putOnTop: SUCCESS
getPlace: column=5, hight=0
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=8, hight=0
getPlace: column=8, hight=0
putOnTop: SUCCESS
getPhone: 223
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getPhone: 171
getPhone: 187
buyRecord: DOESNT_EXISTS
getExpenses: INVALID_INPUT
isMember: INVALID_INPUT
putOnTop: FAILURE
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: 89
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: column=19, hight=75
getPhone: INVALID_INPUT
isMember: False
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: -200
isMember: True
putOnTop: SUCCESS
addCostumer: SUCCESS
getPlace: column=22, hight=0
getExpenses: 10
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: column=16, hight=10
addPrize: SUCCESS
putOnTop: SUCCESS
isMember: True
addCostumer: SUCCESS
getPlace: column=19, hight=38
getPhone: 187
makeMember: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: False
getPhone: 31
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getPhone: 171
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
getPlace: column=6, hight=45
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: 203
getExpenses: -82
addCostumer: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 186
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=0, hight=0
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=25, hight=16
getPlace: column=18, hight=0
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 5
isMember: True
getPlace: column=25, hight=16
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: INVALID_INPUT
addPrize: SUCCESS
getExpenses: 0
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
getPhone: 118
getPlace: column=6, hight=111
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
putOnTop: SUCCESS
getExpenses: -202
getPlace: column=2, hight=0
getPhone: 186
putOnTop: SUCCESS
getPhone: 56
isMember: True
addPrize: SUCCESS
getPlace: column=24, hight=0
isMember: True
putOnTop: SUCCESS
getPhone: 5
buyRecord: SUCCESS
makeMember: SUCCESS
getPlace: column=6, hight=16
addPrize: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPhone: 187
makeMember: DOESNT_EXISTS
addCostumer: INVALID_INPUT
getPhone: 187
buyRecord: SUCCESS
isMember: False
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
isMember: False
getPhone: DOESNT_EXISTS
getPhone: 31
getPlace: column=6, hight=159
getExpenses: -223
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
buyRecord: INVALID_INPUT
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: SUCCESS
getPhone: 206
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=20, hight=0
putOnTop: FAILURE
getPlace: column=2, hight=0
getPhone: 223
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 61
buyRecord: SUCCESS
getPhone: 118
addPrize: INVALID_INPUT
getPlace: column=2, hight=0
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: True
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: 226
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: -337
getExpenses: DOESNT_EXISTS
isMember: False
getExpenses: -102
isMember: False
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=0, hight=225
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=0, hight=130
putOnTop: FAILURE
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
getPhone: 223
putOnTop: FAILURE
addCostumer: ALREADY_EXISTS
getPlace: column=27, hight=50
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=27, hight=108
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
isMember: True
addCostumer: SUCCESS
getPhone: 89
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=27, hight=174
getExpenses: INVALID_INPUT
isMember: INVALID_INPUT
putOnTop: SUCCESS
getPlace: column=24, hight=0
buyRecord: SUCCESS
getPhone: 56
isMember: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 223
getPhone: 230
addPrize: INVALID_INPUT
getPlace: column=27, hight=127
buyRecord: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
getPhone: 40
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: INVALID_INPUT
putOnTop: FAILURE
makeMember: SUCCESS
getExpenses: -750
isMember: True
putOnTop: FAILURE
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
isMember: False
getPhone: 41
addPrize: SUCCESS
newMonth: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: INVALID_INPUT
getPlace: column=17, hight=0
putOnTop: SUCCESS
putOnTop: SUCCESS
getPlace: column=21, hight=0
buyRecord: SUCCESS
getPhone: 43
getPhone: INVALID_INPUT
putOnTop: SUCCESS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: INVALID_INPUT
buyRecord: INVALID_INPUT
putOnTop: SUCCESS
getPlace: column=15, hight=0
putOnTop: DOESNT_EXISTS
isMember: True
addPrize: INVALID_INPUT
getPlace: column=18, hight=12
getPhone: 40
getPlace: column=23, hight=0
getPlace: column=1, hight=0
getPhone: 56
makeMember: SUCCESS
getPhone: 227
getPhone: 89
getPlace: column=2, hight=0
getPlace: column=23, hight=0
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 1
isMember: False
getPlace: column=18, hight=0
isMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: INVALID_INPUT
getPhone: 108
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
getPhone: 202
buyRecord: SUCCESS
getExpenses: 0
buyRecord: SUCCESS
getPhone: 203
putOnTop: SUCCESS
putOnTop: SUCCESS
buyRecord: SUCCESS
getPhone: 4
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: 0
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: column=21, hight=0
getPhone: 59
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=8, hight=0
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
getPhone: 56
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: INVALID_INPUT
isMember: DOESNT_EXISTS
getPhone: INVALID_INPUT
getPhone: 148
addCostumer: ALREADY_EXISTS
putOnTop: SUCCESS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
getExpenses: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
isMember: False
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
getExpenses: INVALID_INPUT
getExpenses: -53
makeMember: SUCCESS
getPhone: 206
getPhone: 234
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 108
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: 31
isMember: True
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
getPhone: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
addPrize: SUCCESS
getExpenses: -15
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: INVALID_INPUT
isMember: True
getPhone: 59
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 163
getPlace: column=20, hight=30
addCostumer: ALREADY_EXISTS
getPhone: 108
getPhone: 118
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=9, hight=18
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=25, hight=0
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: -181
makeMember: ALREADY_EXISTS
getPhone: 118
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=20, hight=0
getExpenses: INVALID_INPUT
getPhone: 49
isMember: False
isMember: False
buyRecord: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: 0
getPlace: column=20, hight=0
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
getPhone: 31
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
isMember: True
addPrize: SUCCESS
isMember: True
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPhone: 5
putOnTop: SUCCESS
isMember: True
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: True
getPlace: column=2, hight=0
getPlace: column=14, hight=14
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=25, hight=13
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 108
buyRecord: INVALID_INPUT
isMember: False
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
isMember: False
putOnTop: SUCCESS
getPhone: 1
getPhone: 163
getPlace: column=20, hight=36
buyRecord: DOESNT_EXISTS
makeMember: SUCCESS
getPlace: column=25, hight=0
isMember: True
getExpenses: DOESNT_EXISTS
getPhone: 247
getPhone: 163
addCostumer: SUCCESS
makeMember: SUCCESS
isMember: False
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 118
getExpenses: -12
getExpenses: INVALID_INPUT
getPhone: 21
addPrize: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
getPlace: column=25, hight=0
addPrize: SUCCESS
getPlace: column=20, hight=46
addPrize: INVALID_INPUT
isMember: True
getExpenses: -227
getPhone: 56
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: INVALID_INPUT
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: column=25, hight=0
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
getPhone: 199
buyRecord: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getPhone: 226
getExpenses: -214
getPlace: column=20, hight=46
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: SUCCESS
getPhone: 123
putOnTop: SUCCESS
makeMember: INVALID_INPUT
putOnTop: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
getPhone: 197
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
getPhone: 117
addPrize: INVALID_INPUT
getPhone: 118
getPhone: 31
addPrize: INVALID_INPUT
getPhone: 61
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: -243
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=11, hight=178
addCostumer: SUCCESS
isMember: False
isMember: INVALID_INPUT
putOnTop: SUCCESS
getPhone: INVALID_INPUT
getPlace: column=25, hight=13
isMember: True
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=11, hight=188
addPrize: SUCCESS
buyRecord: INVALID_INPUT
getPhone: 242
getExpenses: -390
isMember: False
getPhone: 61
addPrize: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
getPlace: column=11, hight=89
putOnTop: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
isMember: True
getPhone: 197
isMember: True
putOnTop: SUCCESS
putOnTop: SUCCESS
addCostumer: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
getExpenses: -152
getExpenses: -643
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPhone: 187
getPhone: 117
getExpenses: -152
addPrize: SUCCESS
putOnTop: FAILURE
getExpenses: -442
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: FAILURE
getPhone: 59
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: SUCCESS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getExpenses: -80
makeMember: SUCCESS
isMember: False
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: -619
buyRecord: SUCCESS
makeMember: SUCCESS
getPlace: column=3, hight=60
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: True
getExpenses: 0
getPhone: 206
putOnTop: FAILURE
addCostumer: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
buyRecord: SUCCESS
getExpenses: -80
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=3, hight=209
getExpenses: DOESNT_EXISTS
getPhone: INVALID_INPUT
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: False
getPhone: 144
isMember: False
getPlace: column=3, hight=229
getPlace: column=3, hight=260
buyRecord: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: -883
putOnTop: FAILURE
makeMember: SUCCESS
putOnTop: FAILURE
getExpenses: -714
getPhone: 206
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=3, hight=276
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
getPhone: 89
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: column=3, hight=111
putOnTop: FAILURE
addPrize: INVALID_INPUT
isMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: 0
addPrize: INVALID_INPUT
getPhone: 197
getPhone: 154
isMember: False
addPrize: SUCCESS
putOnTop: INVALID_INPUT
getPhone: 52
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: INVALID_INPUT
putOnTop: FAILURE
getExpenses: -161
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: column=3, hight=94
getPlace: column=3, hight=120
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
getPlace: column=3, hight=261
getPhone: 118
putOnTop: FAILURE
getPlace: column=3, hight=16
buyRecord: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=3, hight=60
getPlace: column=3, hight=89
putOnTop: INVALID_INPUT
getPlace: column=3, hight=219
getPlace: column=3, hight=0
getPhone: 226
putOnTop: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
isMember: False
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: 202
getExpenses: -867
getPhone: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=3, hight=77
addPrize: SUCCESS
putOnTop: FAILURE
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 197
putOnTop: FAILURE
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: -732
buyRecord: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
isMember: False
getPlace: column=3, hight=94
addPrize: INVALID_INPUT
putOnTop: FAILURE
addPrize: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPhone: 117
getPhone: 40
getExpenses: -981
isMember: True
getPhone: 108
getPlace: column=3, hight=120
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 59
getPlace: column=3, hight=229
makeMember: ALREADY_EXISTS
getPhone: 247
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getPhone: 49
getExpenses: INVALID_INPUT
isMember: True
getPlace: column=3, hight=60
buyRecord: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: -39
putOnTop: FAILURE
makeMember: SUCCESS
getPlace: column=3, hight=276
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
getPhone: 223
buyRecord: INVALID_INPUT
isMember: True
addCostumer: SUCCESS
isMember: False
isMember: True
addPrize: SUCCESS
isMember: False
putOnTop: FAILURE
getPhone: 43
addCostumer: ALREADY_EXISTS
isMember: False
addPrize: SUCCESS
getPlace: column=3, hight=156
isMember: True
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: True
isMember: False
isMember: INVALID_INPUT
makeMember: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=3, hight=156
getPhone: 226
addPrize: SUCCESS
getPlace: column=3, hight=42
buyRecord: SUCCESS
isMember: True
putOnTop: FAILURE
isMember: False
getPlace: column=3, hight=229
getPhone: 130
getExpenses: -190
buyRecord: SUCCESS
getPlace: column=3, hight=3
isMember: False
isMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
isMember: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
isMember: False
getPhone: 206
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
putOnTop: FAILURE
getPlace: column=3, hight=276
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=3, hight=120
putOnTop: FAILURE
getPhone: 242
isMember: True
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
getPhone: 59
addPrize: SUCCESS
isMember: True
getPlace: DOESNT_EXISTS
getPhone: 108
addCostumer: SUCCESS
putOnTop: FAILURE
isMember: True
isMember: False
isMember: True
buyRecord: DOESNT_EXISTS
