newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getExpenses: 100
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 98
putOnTop: SUCCESS
getPhone: 98
isMember: False
getPhone: 172
getPlace: column=3, hight=0
getPhone: 240
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
buyRecord: INVALID_INPUT
getPlace: DOESNT_EXISTS
buyRecord: INVALID_INPUT
makeMember: SUCCESS
getPhone: 172
buyRecord: SUCCESS
addPrize: SUCCESS
getPhone: 240
makeMember: SUCCESS
buyRecord: SUCCESS
getExpenses: -76
addCostumer: SUCCESS
isMember: True
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
getPhone: 98
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
isMember: True
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
getPhone: 247
getExpenses: DOESNT_EXISTS
getPhone: 155
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 247
makeMember: INVALID_INPUT
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: True
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
putOnTop: FAILURE
addPrize: SUCCESS
isMember: True
addPrize: SUCCESS
makeMember: SUCCESS
getPlace: column=2, hight=23
getPlace: column=2, hight=36
getPhone: 98
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
makeMember: SUCCESS
isMember: True
buyRecord: INVALID_INPUT
getExpenses: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: 0
buyRecord: DOESNT_EXISTS
getPlace: column=5, hight=0
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: -227
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=6, hight=0
getPhone: 172
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: INVALID_INPUT
addCostumer: SUCCESS
isMember: True
