newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: column=0, hight=0
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
makeMember: SUCCESS
makeMember: INVALID_INPUT
isMember: True
isMember: False
getExpenses: DOESNT_EXISTS
makeMember: SUCCESS
addPrize: SUCCESS
getPhone: 186
getPhone: 77
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
buyRecord: INVALID_INPUT
putOnTop: SUCCESS
isMember: True
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getPlace: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPhone: 186
buyRecord: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
getExpenses: 0
getPhone: 214
makeMember: ALREADY_EXISTS
getPlace: column=16, hight=0
getExpenses: -82
getPhone: DOESNT_EXISTS
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
putOnTop: SUCCESS
isMember: True
getPhone: 77
getPlace: column=20, hight=0
addPrize: INVALID_INPUT
putOnTop: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: 214
getExpenses: -84
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
getExpenses: -2
putOnTop: SUCCESS
getPhone: 69
putOnTop: SUCCESS
makeMember: SUCCESS
getPlace: INVALID_INPUT
getPhone: 168
addPrize: SUCCESS
getPlace: column=12, hight=0
addPrize: SUCCESS
getPhone: 168
isMember: True
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getPhone: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPlace: column=13, hight=0
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: True
addCostumer: ALREADY_EXISTS
putOnTop: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: INVALID_INPUT
getExpenses: -148
getPhone: 77
putOnTop: SUCCESS
isMember: True
getPhone: 93
getExpenses: DOESNT_EXISTS
getPhone: 233
buyRecord: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
isMember: INVALID_INPUT
getPlace: column=16, hight=13
getPhone: 57
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 69
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
makeMember: DOESNT_EXISTS
makeMember: INVALID_INPUT
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
getExpenses: 97
putOnTop: SUCCESS
getPlace: column=13, hight=0
addCostumer: SUCCESS
getPlace: INVALID_INPUT
makeMember: SUCCESS
addPrize: INVALID_INPUT
getPhone: 77
getPlace: column=16, hight=47
buyRecord: SUCCESS
isMember: True
addPrize: INVALID_INPUT
putOnTop: FAILURE
isMember: False
getPhone: 93
buyRecord: SUCCESS
getPlace: column=10, hight=58
addCostumer: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
makeMember: SUCCESS
putOnTop: SUCCESS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=22, hight=76
putOnTop: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
makeMember: INVALID_INPUT
putOnTop: FAILURE
isMember: True
putOnTop: FAILURE
getExpenses: 97
putOnTop: DOESNT_EXISTS
getPlace: column=8, hight=9
getPlace: INVALID_INPUT
getPhone: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: False
putOnTop: INVALID_INPUT
putOnTop: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
isMember: True
isMember: True
buyRecord: SUCCESS
isMember: False
getPhone: DOESNT_EXISTS
getPlace: column=8, hight=154
getExpenses: DOESNT_EXISTS
putOnTop: SUCCESS
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: column=8, hight=108
makeMember: SUCCESS
isMember: INVALID_INPUT
isMember: False
addCostumer: SUCCESS
getPhone: 233
getExpenses: -327
buyRecord: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: INVALID_INPUT
getPlace: column=8, hight=154
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: True
buyRecord: SUCCESS
makeMember: SUCCESS
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
isMember: True
makeMember: ALREADY_EXISTS
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 67
addPrize: SUCCESS
getPlace: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: SUCCESS
getPhone: 179
addCostumer: SUCCESS
getPlace: column=8, hight=31
isMember: False
getPlace: column=8, hight=95
makeMember: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 216
getPlace: column=8, hight=173
getPlace: column=8, hight=158
putOnTop: SUCCESS
getExpenses: -77
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPhone: 135
putOnTop: FAILURE
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=15, hight=125
getPlace: column=11, hight=0
addCostumer: ALREADY_EXISTS
isMember: True
makeMember: INVALID_INPUT
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: 0
getExpenses: 0
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
getPlace: column=20, hight=0
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: INVALID_INPUT
addPrize: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=15, hight=30
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: -152
addCostumer: SUCCESS
isMember: True
makeMember: SUCCESS
getPlace: column=11, hight=0
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
getPhone: 216
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
putOnTop: FAILURE
getPlace: column=11, hight=0
getExpenses: -557
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPlace: column=13, hight=0
putOnTop: SUCCESS
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
isMember: True
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
putOnTop: SUCCESS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=13, hight=218
isMember: INVALID_INPUT
getExpenses: 0
makeMember: ALREADY_EXISTS
isMember: False
getExpenses: -59
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
isMember: DOESNT_EXISTS
makeMember: INVALID_INPUT
putOnTop: FAILURE
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: DOESNT_EXISTS
getPlace: column=13, hight=29
getPhone: 247
makeMember: SUCCESS
isMember: True
getExpenses: -506
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: 214
getPlace: column=13, hight=73
buyRecord: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
isMember: False
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
getExpenses: -117
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getPlace: INVALID_INPUT
getPlace: column=20, hight=81
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
isMember: INVALID_INPUT
makeMember: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: INVALID_INPUT
addPrize: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPlace: column=20, hight=81
getPlace: column=11, hight=0
getExpenses: DOESNT_EXISTS
getPlace: column=20, hight=179
buyRecord: SUCCESS
getExpenses: -43
isMember: True
getPlace: column=20, hight=247
isMember: INVALID_INPUT
addPrize: SUCCESS
getExpenses: -611
getExpenses: DOESNT_EXISTS
isMember: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
addPrize: INVALID_INPUT
getPhone: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: FAILURE
isMember: False
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: -170
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 137
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
getExpenses: -94
getPhone: 85
makeMember: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
getPhone: 237
getPlace: DOESNT_EXISTS
isMember: INVALID_INPUT
addCostumer: SUCCESS
isMember: True
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: column=20, hight=8
getPhone: 67
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: 18
putOnTop: FAILURE
getPlace: column=20, hight=8
getPhone: DOESNT_EXISTS
isMember: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
getPlace: column=20, hight=84
getExpenses: -621
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: column=20, hight=62
addCostumer: SUCCESS
getExpenses: -94
makeMember: SUCCESS
buyRecord: SUCCESS
getPlace: column=11, hight=0
putOnTop: FAILURE
getExpenses: -173
getPlace: column=20, hight=62
putOnTop: FAILURE
getPhone: 186
getExpenses: 0
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
getPhone: 130
getPhone: 237
addCostumer: SUCCESS
getPlace: column=20, hight=214
addCostumer: SUCCESS
isMember: True
addPrize: SUCCESS
getPlace: column=20, hight=233
isMember: True
putOnTop: FAILURE
addCostumer: SUCCESS
putOnTop: FAILURE
getPhone: 135
getPlace: INVALID_INPUT
makeMember: SUCCESS
getPhone: INVALID_INPUT
getPhone: 66
getPlace: column=11, hight=0
addPrize: INVALID_INPUT
getPlace: column=20, hight=23
isMember: False
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
getPlace: column=20, hight=8
getPhone: 75
buyRecord: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
putOnTop: SUCCESS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -172
makeMember: ALREADY_EXISTS
getPlace: column=20, hight=227
getExpenses: -157
buyRecord: SUCCESS
getPlace: column=20, hight=192
addCostumer: SUCCESS
isMember: True
putOnTop: FAILURE
makeMember: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
getPhone: 184
addCostumer: SUCCESS
isMember: False
makeMember: DOESNT_EXISTS
getExpenses: -482
getPlace: INVALID_INPUT
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
getPlace: column=20, hight=227
addCostumer: SUCCESS
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
putOnTop: FAILURE
getPlace: column=20, hight=211
isMember: False
isMember: False
addCostumer: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
getExpenses: -318
getPlace: column=20, hight=138
addCostumer: SUCCESS
getPlace: column=20, hight=207
makeMember: DOESNT_EXISTS
getPhone: 134
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: True
getPlace: column=20, hight=226
getExpenses: INVALID_INPUT
isMember: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: column=20, hight=120
isMember: True
getExpenses: DOESNT_EXISTS
getPhone: 242
isMember: False
getPlace: column=20, hight=247
isMember: True
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 34
getPhone: 237
putOnTop: FAILURE
isMember: True
putOnTop: FAILURE
putOnTop: FAILURE
getExpenses: -1035
buyRecord: SUCCESS
getPlace: column=20, hight=192
getPhone: 233
getPlace: column=20, hight=179
getPhone: 46
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
isMember: False
getExpenses: INVALID_INPUT
getExpenses: -146
isMember: False
getPhone: 184
addPrize: INVALID_INPUT
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 29
buyRecord: DOESNT_EXISTS
isMember: True
makeMember: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=20, hight=81
makeMember: ALREADY_EXISTS
getPlace: column=20, hight=23
addCostumer: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
getPlace: column=20, hight=0
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
putOnTop: FAILURE
buyRecord: SUCCESS
putOnTop: FAILURE
buyRecord: INVALID_INPUT
putOnTop: FAILURE
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
putOnTop: INVALID_INPUT
isMember: False
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
isMember: True
putOnTop: FAILURE
getPlace: column=20, hight=211
getPlace: column=20, hight=192
getPhone: 4
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: SUCCESS
isMember: True
putOnTop: FAILURE
makeMember: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
isMember: False
makeMember: ALREADY_EXISTS
getPhone: 137
getPhone: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
getPlace: column=20, hight=37
addPrize: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 167
putOnTop: FAILURE
getPlace: column=20, hight=192
addPrize: SUCCESS
getExpenses: -497
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
putOnTop: FAILURE
getPhone: 130
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
putOnTop: FAILURE
isMember: DOESNT_EXISTS
buyRecord: SUCCESS
putOnTop: FAILURE
isMember: True
getPhone: DOESNT_EXISTS
getPlace: INVALID_INPUT
getPhone: DOESNT_EXISTS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
isMember: True
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
getExpenses: -203
isMember: False
addPrize: SUCCESS
makeMember: SUCCESS
getPlace: column=20, hight=84
getPhone: 43
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
addCostumer: SUCCESS
isMember: True
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
getPhone: 135
addPrize: SUCCESS
getPhone: 242
addPrize: SUCCESS
getPlace: column=20, hight=53
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: -353
getPlace: column=20, hight=161
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
getPlace: column=20, hight=211
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=20, hight=11
addCostumer: ALREADY_EXISTS
getExpenses: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=20, hight=207
addCostumer: ALREADY_EXISTS
getPlace: column=20, hight=8
buyRecord: SUCCESS
getPhone: 182
getPlace: column=20, hight=84
putOnTop: FAILURE
getExpenses: -379
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPhone: INVALID_INPUT
getPlace: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
isMember: INVALID_INPUT
getPlace: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
isMember: False
getPlace: INVALID_INPUT
getPhone: 9
getPhone: 67
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
addPrize: INVALID_INPUT
getPhone: 119
getExpenses: INVALID_INPUT
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=20, hight=8
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: -1082
makeMember: SUCCESS
putOnTop: FAILURE
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=20, hight=211
buyRecord: SUCCESS
addPrize: INVALID_INPUT
isMember: False
putOnTop: FAILURE
getExpenses: -460
buyRecord: SUCCESS
addCostumer: INVALID_INPUT
isMember: DOESNT_EXISTS
getExpenses: -1287
putOnTop: FAILURE
putOnTop: FAILURE
getPhone: 42
putOnTop: FAILURE
getPhone: 18
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: SUCCESS
getPhone: 85
getPlace: column=20, hight=81
isMember: True
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: INVALID_INPUT
getExpenses: -398
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: True
addPrize: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPhone: 41
getPhone: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: column=20, hight=192
addPrize: SUCCESS
getExpenses: -659
getPhone: 179
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getPlace: column=20, hight=23
getExpenses: -778
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPlace: column=20, hight=214
getPlace: INVALID_INPUT
getPlace: column=20, hight=179
getPhone: 86
addCostumer: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: True
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getExpenses: 127
addCostumer: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -739
isMember: INVALID_INPUT
getPhone: 67
addPrize: INVALID_INPUT
isMember: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
getPhone: 77
buyRecord: SUCCESS
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: INVALID_INPUT
isMember: True
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
getPhone: DOESNT_EXISTS
isMember: True
getPlace: column=20, hight=84
getPhone: 92
makeMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: FAILURE
getExpenses: -1160
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
getPlace: column=20, hight=120
isMember: True
getExpenses: -1631
addPrize: INVALID_INPUT
isMember: True
addPrize: INVALID_INPUT
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
getPlace: column=20, hight=37
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
isMember: False
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: -1331
makeMember: SUCCESS
getPhone: 86
getPhone: DOESNT_EXISTS
isMember: DOESNT_EXISTS
isMember: True
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=20, hight=0
getPlace: column=20, hight=37
getPhone: 184
newMonth: SUCCESS
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: True
getExpenses: 0
putOnTop: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: False
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
getPhone: 18
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getPlace: column=7, hight=0
getPlace: INVALID_INPUT
getExpenses: INVALID_INPUT
getPhone: 237
getPhone: DOESNT_EXISTS
putOnTop: SUCCESS
putOnTop: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
getPlace: column=5, hight=0
getExpenses: 0
addPrize: SUCCESS
getPlace: INVALID_INPUT
putOnTop: FAILURE
getPlace: column=13, hight=11
getPhone: 225
makeMember: ALREADY_EXISTS
isMember: False
isMember: False
makeMember: ALREADY_EXISTS
getPhone: INVALID_INPUT
getPlace: column=10, hight=0
makeMember: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=13, hight=0
isMember: True
isMember: False
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
putOnTop: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: INVALID_INPUT
isMember: False
addPrize: SUCCESS
getPlace: column=5, hight=0
getPlace: column=14, hight=6
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
putOnTop: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: False
getPhone: 223
makeMember: SUCCESS
isMember: True
addCostumer: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: False
getPhone: 18
buyRecord: INVALID_INPUT
makeMember: SUCCESS
isMember: True
getExpenses: -10
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 109
getPhone: 214
getExpenses: -83
putOnTop: SUCCESS
makeMember: SUCCESS
getPhone: 223
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
addCostumer: SUCCESS
getPhone: 77
buyRecord: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: SUCCESS
getExpenses: -184
buyRecord: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 29
getPlace: column=8, hight=1
