newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
getPlace: column=7, hight=0
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 113
isMember: False
isMember: False
addPrize: SUCCESS
putOnTop: SUCCESS
putOnTop: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: INVALID_INPUT
getPhone: 77
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: False
buyRecord: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 44
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
isMember: False
makeMember: ALREADY_EXISTS
getPhone: 112
getPlace: DOESNT_EXISTS
getPhone: 77
isMember: False
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
getPhone: 113
getPlace: column=1, hight=0
getPhone: 44
addCostumer: SUCCESS
isMember: INVALID_INPUT
buyRecord: INVALID_INPUT
makeMember: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
getPhone: 30
isMember: False
isMember: False
isMember: False
putOnTop: SUCCESS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
getPhone: 21
addCostumer: SUCCESS
isMember: True
buyRecord: SUCCESS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
isMember: False
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: column=0, hight=17
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: True
getPlace: column=1, hight=0
makeMember: ALREADY_EXISTS
isMember: True
makeMember: SUCCESS
getPhone: 78
getPhone: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
buyRecord: SUCCESS
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 78
buyRecord: SUCCESS
getPlace: column=0, hight=0
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: INVALID_INPUT
putOnTop: SUCCESS
getPhone: 74
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPhone: 103
getExpenses: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
addPrize: INVALID_INPUT
putOnTop: DOESNT_EXISTS
isMember: True
getPlace: INVALID_INPUT
getExpenses: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: True
addPrize: INVALID_INPUT
putOnTop: FAILURE
getExpenses: INVALID_INPUT
makeMember: SUCCESS
isMember: False
isMember: False
getExpenses: 63
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: DOESNT_EXISTS
isMember: False
putOnTop: FAILURE
getExpenses: 0
getExpenses: DOESNT_EXISTS
getPlace: column=2, hight=0
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
getExpenses: 0
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=0, hight=24
isMember: False
putOnTop: SUCCESS
getPlace: column=2, hight=0
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPlace: column=2, hight=1
putOnTop: SUCCESS
isMember: True
getPhone: 247
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPhone: 44
buyRecord: SUCCESS
makeMember: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: -87
getPhone: INVALID_INPUT
buyRecord: SUCCESS
isMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
isMember: True
getPhone: 214
isMember: True
isMember: True
buyRecord: INVALID_INPUT
getPhone: 77
getPlace: INVALID_INPUT
getPhone: 125
getPhone: 193
getPhone: INVALID_INPUT
getExpenses: -87
addCostumer: SUCCESS
getPlace: INVALID_INPUT
makeMember: INVALID_INPUT
isMember: True
getExpenses: 101
addCostumer: SUCCESS
addPrize: SUCCESS
makeMember: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: FAILURE
putOnTop: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getExpenses: 101
getPhone: 41
getExpenses: -193
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: INVALID_INPUT
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
isMember: False
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: INVALID_INPUT
addCostumer: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 183
putOnTop: DOESNT_EXISTS
isMember: True
putOnTop: FAILURE
isMember: False
getPhone: 23
getPlace: column=1, hight=28
addCostumer: INVALID_INPUT
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
getPhone: 193
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: DOESNT_EXISTS
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getPhone: 78
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
isMember: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: 0
putOnTop: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
getPhone: 110
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: INVALID_INPUT
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: DOESNT_EXISTS
putOnTop: INVALID_INPUT
addCostumer: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 30
getPhone: 15
buyRecord: SUCCESS
makeMember: SUCCESS
isMember: False
addCostumer: SUCCESS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: True
putOnTop: FAILURE
getPhone: INVALID_INPUT
buyRecord: INVALID_INPUT
isMember: False
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=1, hight=28
isMember: False
getPhone: INVALID_INPUT
makeMember: SUCCESS
makeMember: SUCCESS
makeMember: SUCCESS
addCostumer: SUCCESS
isMember: True
addPrize: INVALID_INPUT
getExpenses: -548
isMember: True
putOnTop: FAILURE
buyRecord: SUCCESS
putOnTop: FAILURE
makeMember: ALREADY_EXISTS
getPlace: column=1, hight=58
addPrize: INVALID_INPUT
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: -349
addPrize: SUCCESS
buyRecord: SUCCESS
getPhone: 247
addCostumer: SUCCESS
buyRecord: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: -468
getExpenses: DOESNT_EXISTS
getExpenses: -37
addPrize: INVALID_INPUT
isMember: False
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPhone: 15
isMember: False
isMember: False
getExpenses: DOESNT_EXISTS
getPhone: 223
isMember: True
getExpenses: 103
getPhone: 15
getPlace: DOESNT_EXISTS
getPhone: 183
getExpenses: INVALID_INPUT
getPhone: 74
isMember: False
getPhone: 207
makeMember: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
isMember: True
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
buyRecord: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: column=1, hight=76
isMember: False
getExpenses: 67
buyRecord: SUCCESS
isMember: True
getExpenses: INVALID_INPUT
getPlace: DOESNT_EXISTS
getPhone: 31
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: True
makeMember: ALREADY_EXISTS
getExpenses: INVALID_INPUT
makeMember: INVALID_INPUT
buyRecord: INVALID_INPUT
makeMember: ALREADY_EXISTS
getPlace: column=1, hight=28
addPrize: INVALID_INPUT
isMember: True
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
addPrize: SUCCESS
addCostumer: SUCCESS
isMember: False
isMember: True
putOnTop: FAILURE
addCostumer: SUCCESS
getPhone: 156
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
makeMember: INVALID_INPUT
putOnTop: DOESNT_EXISTS
getPhone: 197
getPlace: column=1, hight=41
isMember: False
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getPhone: 134
putOnTop: FAILURE
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
getPhone: 103
getExpenses: DOESNT_EXISTS
getPhone: 30
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
isMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getExpenses: -158
makeMember: SUCCESS
isMember: False
addPrize: INVALID_INPUT
isMember: True
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=1, hight=58
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
isMember: False
getPhone: 193
putOnTop: DOESNT_EXISTS
getPhone: 21
isMember: False
putOnTop: INVALID_INPUT
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: INVALID_INPUT
buyRecord: SUCCESS
addPrize: SUCCESS
putOnTop: FAILURE
getPlace: column=1, hight=35
addPrize: SUCCESS
addPrize: SUCCESS
getPlace: column=1, hight=11
isMember: True
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 113
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
makeMember: SUCCESS
addPrize: INVALID_INPUT
isMember: False
makeMember: SUCCESS
addPrize: SUCCESS
getPhone: 214
getExpenses: -758
makeMember: ALREADY_EXISTS
getPhone: 223
makeMember: ALREADY_EXISTS
getPlace: column=1, hight=41
buyRecord: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
isMember: False
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
makeMember: SUCCESS
getPhone: 223
addPrize: SUCCESS
makeMember: SUCCESS
putOnTop: FAILURE
makeMember: INVALID_INPUT
buyRecord: SUCCESS
isMember: INVALID_INPUT
getPlace: column=1, hight=58
makeMember: SUCCESS
makeMember: SUCCESS
addPrize: INVALID_INPUT
makeMember: ALREADY_EXISTS
isMember: True
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
putOnTop: FAILURE
buyRecord: SUCCESS
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getPlace: column=1, hight=75
getPlace: DOESNT_EXISTS
addPrize: SUCCESS
getPlace: column=1, hight=11
putOnTop: FAILURE
getPlace: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: FAILURE
addCostumer: SUCCESS
isMember: True
getPhone: 23
getPlace: DOESNT_EXISTS
getExpenses: -625
makeMember: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: INVALID_INPUT
putOnTop: FAILURE
isMember: True
getExpenses: -35
putOnTop: FAILURE
putOnTop: DOESNT_EXISTS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getExpenses: 116
getPlace: column=1, hight=11
getPlace: column=1, hight=11
getPhone: 107
isMember: INVALID_INPUT
addPrize: SUCCESS
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getExpenses: 0
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: True
isMember: INVALID_INPUT
getExpenses: -122
isMember: True
makeMember: DOESNT_EXISTS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
isMember: True
addCostumer: SUCCESS
addPrize: SUCCESS
getPlace: DOESNT_EXISTS
isMember: False
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
getPlace: INVALID_INPUT
getPlace: column=1, hight=58
putOnTop: FAILURE
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=1, hight=11
putOnTop: FAILURE
getPlace: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
isMember: True
getPlace: column=1, hight=75
getExpenses: 116
isMember: False
getExpenses: 116
getPhone: INVALID_INPUT
getExpenses: -254
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: True
addPrize: SUCCESS
getPhone: 247
getPlace: column=1, hight=76
getPhone: 173
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
buyRecord: DOESNT_EXISTS
getPlace: column=1, hight=76
buyRecord: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
makeMember: SUCCESS
putOnTop: INVALID_INPUT
putOnTop: INVALID_INPUT
addPrize: SUCCESS
getPhone: 21
makeMember: SUCCESS
addCostumer: SUCCESS
getPlace: column=1, hight=41
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 15
addPrize: INVALID_INPUT
getPhone: 214
addPrize: SUCCESS
makeMember: INVALID_INPUT
isMember: True
putOnTop: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: INVALID_INPUT
getPlace: column=1, hight=28
getPhone: 185
buyRecord: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: 103
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
getPlace: column=1, hight=75
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=1, hight=58
makeMember: SUCCESS
buyRecord: INVALID_INPUT
getExpenses: -950
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=1, hight=75
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
putOnTop: FAILURE
addPrize: SUCCESS
isMember: INVALID_INPUT
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
getPlace: column=1, hight=11
getPhone: 23
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
getPlace: column=1, hight=0
addPrize: SUCCESS
getPlace: column=1, hight=76
addPrize: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=1, hight=41
addPrize: SUCCESS
addPrize: SUCCESS
buyRecord: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
isMember: True
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 173
makeMember: SUCCESS
getPhone: 15
getExpenses: -190
addCostumer: SUCCESS
makeMember: SUCCESS
addPrize: SUCCESS
getPhone: 173
makeMember: ALREADY_EXISTS
getPlace: column=1, hight=11
addCostumer: SUCCESS
buyRecord: SUCCESS
getPlace: INVALID_INPUT
isMember: False
addPrize: INVALID_INPUT
getExpenses: 156
addPrize: INVALID_INPUT
buyRecord: SUCCESS
isMember: True
putOnTop: FAILURE
makeMember: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=1, hight=41
isMember: INVALID_INPUT
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
getExpenses: -146
makeMember: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
addCostumer: SUCCESS
addPrize: SUCCESS
addPrize: SUCCESS
addPrize: INVALID_INPUT
getPhone: 165
getExpenses: -1128
getPhone: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
addCostumer: SUCCESS
getPhone: DOESNT_EXISTS
getPhone: INVALID_INPUT
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
getPhone: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPlace: column=1, hight=75
getPlace: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
isMember: INVALID_INPUT
putOnTop: FAILURE
makeMember: DOESNT_EXISTS
isMember: INVALID_INPUT
getPhone: 156
isMember: INVALID_INPUT
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
buyRecord: SUCCESS
getPhone: 156
getPlace: INVALID_INPUT
addCostumer: SUCCESS
getPlace: column=1, hight=28
getPhone: 183
addPrize: SUCCESS
putOnTop: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPlace: DOESNT_EXISTS
isMember: INVALID_INPUT
getPlace: column=1, hight=0
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
putOnTop: FAILURE
addPrize: SUCCESS
getExpenses: -870
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getPhone: 152
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
makeMember: INVALID_INPUT
addCostumer: SUCCESS
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: DOESNT_EXISTS
getPhone: 134
makeMember: ALREADY_EXISTS
makeMember: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
putOnTop: INVALID_INPUT
getPlace: column=1, hight=11
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
putOnTop: INVALID_INPUT
buyRecord: SUCCESS
getPlace: column=1, hight=35
getPhone: DOESNT_EXISTS
addPrize: SUCCESS
isMember: True
getPhone: 66
addCostumer: SUCCESS
getPhone: 201
addCostumer: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
getExpenses: -487
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: -805
isMember: True
getPlace: INVALID_INPUT
getPlace: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: -1303
putOnTop: DOESNT_EXISTS
addPrize: SUCCESS
makeMember: SUCCESS
putOnTop: FAILURE
addPrize: INVALID_INPUT
putOnTop: FAILURE
makeMember: INVALID_INPUT
putOnTop: FAILURE
getExpenses: INVALID_INPUT
putOnTop: INVALID_INPUT
isMember: False
isMember: DOESNT_EXISTS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=1, hight=0
getPhone: 214
makeMember: SUCCESS
putOnTop: FAILURE
isMember: False
getPlace: DOESNT_EXISTS
getPlace: column=1, hight=0
addCostumer: ALREADY_EXISTS
addCostumer: ALREADY_EXISTS
addPrize: SUCCESS
isMember: False
addCostumer: ALREADY_EXISTS
isMember: False
buyRecord: SUCCESS
isMember: True
isMember: False
getExpenses: DOESNT_EXISTS
getPlace: DOESNT_EXISTS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: 165
addCostumer: SUCCESS
buyRecord: INVALID_INPUT
getPlace: column=1, hight=35
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: True
getPlace: DOESNT_EXISTS
putOnTop: INVALID_INPUT
getPhone: 41
addPrize: SUCCESS
makeMember: ALREADY_EXISTS
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: INVALID_INPUT
isMember: False
buyRecord: SUCCESS
isMember: True
isMember: True
buyRecord: SUCCESS
getPlace: column=1, hight=11
addPrize: INVALID_INPUT
getPlace: INVALID_INPUT
addCostumer: SUCCESS
addPrize: SUCCESS
isMember: False
getPhone: DOESNT_EXISTS
buyRecord: SUCCESS
getPlace: column=1, hight=0
isMember: True
isMember: False
buyRecord: SUCCESS
putOnTop: FAILURE
putOnTop: INVALID_INPUT
addPrize: INVALID_INPUT
makeMember: SUCCESS
getPlace: column=1, hight=11
isMember: True
isMember: True
getPlace: column=1, hight=41
getExpenses: -766
putOnTop: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
addCostumer: ALREADY_EXISTS
getPlace: column=1, hight=35
getPlace: column=1, hight=35
getPhone: 59
getPhone: 214
buyRecord: INVALID_INPUT
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: False
putOnTop: DOESNT_EXISTS
isMember: True
getPlace: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: -475
getPlace: column=1, hight=41
makeMember: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
isMember: False
getPhone: 68
makeMember: ALREADY_EXISTS
getPhone: INVALID_INPUT
putOnTop: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
makeMember: ALREADY_EXISTS
getPhone: 31
getPlace: column=1, hight=75
getPlace: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
getPhone: INVALID_INPUT
addCostumer: INVALID_INPUT
makeMember: INVALID_INPUT
addCostumer: SUCCESS
isMember: True
getPlace: DOESNT_EXISTS
buyRecord: SUCCESS
makeMember: SUCCESS
putOnTop: DOESNT_EXISTS
isMember: False
addPrize: SUCCESS
addCostumer: SUCCESS
addPrize: INVALID_INPUT
getPhone: 23
getPlace: column=1, hight=28
isMember: DOESNT_EXISTS
addPrize: INVALID_INPUT
isMember: True
getPlace: DOESNT_EXISTS
getExpenses: -514
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPhone: 23
isMember: True
getPhone: DOESNT_EXISTS
putOnTop: FAILURE
getExpenses: DOESNT_EXISTS
makeMember: DOESNT_EXISTS
isMember: False
addCostumer: ALREADY_EXISTS
buyRecord: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=1, hight=76
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
buyRecord: DOESNT_EXISTS
putOnTop: DOESNT_EXISTS
getExpenses: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
buyRecord: SUCCESS
getExpenses: -1333
addPrize: SUCCESS
isMember: False
newMonth: SUCCESS
isMember: True
makeMember: SUCCESS
addPrize: SUCCESS
isMember: True
addPrize: SUCCESS
addCostumer: ALREADY_EXISTS
isMember: True
getPlace: column=2, hight=0
getPlace: column=15, hight=0
buyRecord: SUCCESS
getExpenses: 0
getPhone: 201
getExpenses: DOESNT_EXISTS
getPlace: column=8, hight=0
makeMember: DOESNT_EXISTS
addPrize: SUCCESS
putOnTop: SUCCESS
isMember: True
isMember: True
addCostumer: SUCCESS
isMember: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
makeMember: SUCCESS
getPhone: 103
buyRecord: SUCCESS
makeMember: INVALID_INPUT
addPrize: SUCCESS
getPlace: column=19, hight=0
makeMember: ALREADY_EXISTS
putOnTop: SUCCESS
putOnTop: SUCCESS
isMember: False
putOnTop: FAILURE
getPlace: column=5, hight=0
putOnTop: DOESNT_EXISTS
putOnTop: SUCCESS
putOnTop: SUCCESS
getPhone: 173
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
getExpenses: -16
addCostumer: SUCCESS
buyRecord: SUCCESS
getPhone: 31
getExpenses: -132
putOnTop: DOESNT_EXISTS
makeMember: ALREADY_EXISTS
getPlace: DOESNT_EXISTS
getExpenses: INVALID_INPUT
makeMember: ALREADY_EXISTS
addPrize: INVALID_INPUT
addCostumer: ALREADY_EXISTS
getPhone: DOESNT_EXISTS
addCostumer: SUCCESS
isMember: True
getPlace: column=5, hight=0
getPhone: 130
makeMember: ALREADY_EXISTS
addCostumer: SUCCESS
isMember: INVALID_INPUT
getPlace: column=6, hight=0
putOnTop: DOESNT_EXISTS
addCostumer: ALREADY_EXISTS
