newMonth: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
addCostumer: SUCCESS
isMember: False
getExpenses: DOESNT_EXISTS
buyRecord: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
isMember: False
getPhone: DOESNT_EXISTS
getPhone: 98
buyRecord: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
isMember: False
addPrize: SUCCESS
addCostumer: SUCCESS
getPhone: 98
addPrize: INVALID_INPUT
addPrize: INVALID_INPUT
isMember: False
getPhone: DOESNT_EXISTS
isMember: False
buyRecord: DOESNT_EXISTS
buyRecord: DOESNT_EXISTS
isMember: False
buyRecord: SUCCESS
buyRecord: SUCCESS
getPlace: column=22, hight=0
buyRecord: SUCCESS
addCostumer: SUCCESS
getExpenses: DOESNT_EXISTS
addCostumer: SUCCESS
getPlace: column=27, hight=0
getPlace: column=20, hight=0
buyRecord: SUCCESS
getPhone: INVALID_INPUT
putOnTop: SUCCESS
getPhone: 98
addCostumer: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
buyRecord: SUCCESS
putOnTop: DOESNT_EXISTS
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
getPlace: column=19, hight=0
isMember: False
makeMember: SUCCESS
getExpenses: DOESNT_EXISTS
isMember: False
getPlace: column=10, hight=0
buyRecord: SUCCESS
getExpenses: 0
buyRecord: SUCCESS
getPhone: DOESNT_EXISTS
isMember: DOESNT_EXISTS
getPlace: column=24, hight=0
addPrize: SUCCESS
addCostumer: SUCCESS
putOnTop: SUCCESS
isMember: False
getExpenses: -74
putOnTop: SUCCESS
buyRecord: SUCCESS
buyRecord: SUCCESS
putOnTop: SUCCESS
getExpenses: INVALID_INPUT
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
addPrize: SUCCESS
addPrize: SUCCESS
isMember: True
buyRecord: SUCCESS
isMember: True
getPhone: 157
addPrize: INVALID_INPUT
getExpenses: DOESNT_EXISTS
isMember: False
isMember: True
addPrize: SUCCESS
putOnTop: SUCCESS
addPrize: INVALID_INPUT
addPrize: SUCCESS
addPrize: SUCCESS
makeMember: DOESNT_EXISTS
getPlace: column=4, hight=0
makeMember: SUCCESS
getPhone: 142
getExpenses: DOESNT_EXISTS
getPhone: 20
addPrize: SUCCESS
addCostumer: INVALID_INPUT
putOnTop: SUCCESS
getPhone: 127
addPrize: SUCCESS
addCostumer: SUCCESS
getPlace: column=3, hight=0
getExpenses: DOESNT_EXISTS
getPlace: INVALID_INPUT
isMember: False
addPrize: SUCCESS
